// <auto-generated/>
// CS2OpenSchema — Soundsystem/CSosGroupActionTimeLimitSchema
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Soundsystem;

/// <summary>
///     CSosGroupActionTimeLimitSchema
/// </summary>
/// <remarks>
///     Module: <c>soundsystem</c> — 16 bytes, align 8.
/// </remarks>
[NativeSize(16)]
public partial class CSosGroupActionTimeLimitSchema : CSosGroupActionSchema
{
    /// <summary>
    ///     Gets or sets MaxDuration.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flMaxDuration</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_flMaxDuration")]
    public float MaxDuration { get; set; }
}
