// <auto-generated/>
// CS2OpenSchema — Particleslib/CParticleVariableRef
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particleslib;

/// <summary>
///     CParticleVariableRef.
/// </summary>
/// <remarks>
///     Module: <c>particleslib</c> — 80 bytes, align 8.
/// </remarks>
[NativeSize(80)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_variableName\": \"\",\n\t\"m_variableType\": \"PVAL_VOID\"\n}")]
[NativeMetadata("MPropertyCustomEditor", "ParticleVariableRef()")]
public partial class CParticleVariableRef
{
    /// <summary>
    ///     Gets or sets VariableName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_variableName</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_variableName")]
    [NativeMetadata("MFgdFromSchemaCompletelySkipField", "")]
    public string VariableName { get; set; }

    /// <summary>
    ///     Gets or sets VariableType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_variableType</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_variableType")]
    [NativeMetadata("MFgdFromSchemaCompletelySkipField", "")]
    public object? VariableType { get; set; }
}
