// <auto-generated/>
// CS2OpenSchema — Particleslib/CParticleCollectionBindingInstance
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.PulseRuntimeLib;

#endregion

namespace CS2OpenSchema.Particleslib;

/// <summary>
///     CParticleCollectionBindingInstance.
/// </summary>
/// <remarks>
///     Module: <c>particleslib</c> — 304 bytes.
/// </remarks>
[NativeSize(304)]
public partial class CParticleCollectionBindingInstance : CBasePulseGraphInstance
{
}
