// <auto-generated/>
// CS2OpenSchema — Worldrenderer/AggregateMeshInfo
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Worldrenderer;

/// <summary>
///     AggregateMeshInfo_t
/// </summary>
/// <remarks>
///     Module: <c>worldrenderer</c> — 36 bytes, align 4.
/// </remarks>
[NativeSize(36)]
[NativeName("AggregateMeshInfo_t")]
public partial class AggregateMeshInfo
{
    /// <summary>
    ///     Gets or sets DrawCallIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nDrawCallIndex</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_nDrawCallIndex")]
    public short DrawCallIndex { get; set; }

    /// <summary>
    ///     Gets or sets HasTransform.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bHasTransform</c> at offset <c>0x5</c>.
    /// </remarks>
    [NativeOffset(0x5)]
    [NativeName("m_bHasTransform")]
    public bool HasTransform { get; set; }

    /// <summary>
    ///     Gets or sets InstanceStreamOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nInstanceStreamOffset</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_nInstanceStreamOffset")]
    public uint InstanceStreamOffset { get; set; }

    /// <summary>
    ///     Gets or sets InstanceStreams.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_instanceStreams</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_instanceStreams")]
    public AggregateInstanceStream InstanceStreams { get; set; }

    /// <summary>
    ///     Gets or sets LODGroupMask.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nLODGroupMask</c> at offset <c>0x6</c>.
    /// </remarks>
    [NativeOffset(0x6)]
    [NativeName("m_nLODGroupMask")]
    public byte LODGroupMask { get; set; }

    /// <summary>
    ///     Gets or sets LODSetupIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nLODSetupIndex</c> at offset <c>0xA</c>.
    /// </remarks>
    [NativeOffset(0xA)]
    [NativeName("m_nLODSetupIndex")]
    public short LODSetupIndex { get; set; }

    /// <summary>
    ///     Gets or sets LightProbeVolumePrecomputedHandshake.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nLightProbeVolumePrecomputedHandshake</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_nLightProbeVolumePrecomputedHandshake")]
    public int LightProbeVolumePrecomputedHandshake { get; set; }

    /// <summary>
    ///     Gets or sets ObjectFlags.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_objectFlags</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_objectFlags")]
    public ObjectTypeFlags ObjectFlags { get; set; }

    /// <summary>
    ///     Gets or sets TintColor.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vTintColor</c> at offset <c>0xC</c>.
    /// </remarks>
    [NativeOffset(0xC)]
    [NativeName("m_vTintColor")]
    public Color TintColor { get; set; }

    /// <summary>
    ///     Gets or sets VertexAlbedoStreamOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nVertexAlbedoStreamOffset</c> at offset <c>0x1C</c>.
    /// </remarks>
    [NativeOffset(0x1C)]
    [NativeName("m_nVertexAlbedoStreamOffset")]
    public uint VertexAlbedoStreamOffset { get; set; }

    /// <summary>
    ///     Gets or sets VisClusterMemberCount.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nVisClusterMemberCount</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_nVisClusterMemberCount")]
    public byte VisClusterMemberCount { get; set; }

    /// <summary>
    ///     Gets or sets VisClusterMemberOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nVisClusterMemberOffset</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_nVisClusterMemberOffset")]
    public uint VisClusterMemberOffset { get; set; }
}
