// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmClipDocument
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmClipDocument
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 248 bytes, align 8.
/// </remarks>
[NativeSize(248)]
public partial class CNmClipDocument : CNmAnimDocument
{
    /// <summary>
    ///     Gets or sets AdditiveBaseFilename.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_additiveBaseFilename</c> at offset <c>0xB8</c>.
    /// </remarks>
    [NativeOffset(0xB8)]
    [NativeName("m_additiveBaseFilename")]
    [NativeMetadata("MPropertyGroupName", "\"+Additive\"")]
    [NativeMetadata("MPropertyAttributeEditor", "\"AssetBrowse( dmx, fbx, *requiredoubleclick )\"")]
    [NativeMetadata("MPropertyDescription", "\"The source file to use as the base of the additive\"")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public string AdditiveBaseFilename { get; set; }

    /// <summary>
    ///     Gets or sets AdditiveBaseFrame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_additiveBaseFrame</c> at offset <c>0xC0</c>.
    /// </remarks>
    [NativeOffset(0xC0)]
    [NativeName("m_additiveBaseFrame")]
    [NativeMetadata("MPropertyGroupName", "\"+Additive\"")]
    [NativeMetadata("MPropertyDescription",
        "\"The frame to use when generating an additive, if you are generating relative to another animation and this is set to -1, we will extract each frame from it's corresponding frame in the base anim\"")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public CNmClipDocumentAdditiveBaseFrame AdditiveBaseFrame { get; set; }

    /// <summary>
    ///     Gets or sets AdditiveBaseFrameIdx.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nAdditiveBaseFrameIdx</c> at offset <c>0xC4</c>.
    /// </remarks>
    [NativeOffset(0xC4)]
    [NativeName("m_nAdditiveBaseFrameIdx")]
    [NativeMetadata("MPropertyGroupName", "\"+Additive\"")]
    [NativeMetadata("MPropertyDescription",
        "\"The frame to use when generating an additive, only valid for 'RelativeToFrame' and 'RelativeToAnimationFrame' \"")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public int AdditiveBaseFrameIdx { get; set; }

    /// <summary>
    ///     Gets or sets AdditiveType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_additiveType</c> at offset <c>0xB4</c>.
    /// </remarks>
    [NativeOffset(0xB4)]
    [NativeName("m_additiveType")]
    [NativeMetadata("MPropertyGroupName", "\"+Additive\"")]
    public CNmClipDocumentAdditiveType AdditiveType { get; set; }

    /// <summary>
    ///     Gets or sets AnimationSkeletonName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_animationSkeletonName</c> at offset <c>0x78</c>.
    /// </remarks>
    [NativeOffset(0x78)]
    [NativeName("m_animationSkeletonName")]
    [NativeMetadata("MPropertyAttributeEditor", "\"AssetBrowse( vnmskel, *requiredoubleclick )\"")]
    public string AnimationSkeletonName { get; set; }

    /// <summary>
    ///     Gets or sets BonesToSampleInModelSpace.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bonesToSampleInModelSpace</c> at offset <c>0xD0</c>.
    /// </remarks>
    [NativeOffset(0xD0)]
    [NativeName("m_bonesToSampleInModelSpace")]
    [NativeMetadata("MPropertyGroupName", "\"Advanced\"")]
    [NativeMetadata("MPropertyAutoExpandSelf")]
    [NativeMetadata("MPropertyDescription",
        "\"List the set of bones that need to be sampled in model space for sub-frames. Warning! This can be REALLY expensive so be careful with this!\"")]
    public string[] BonesToSampleInModelSpace { get; set; }

    /// <summary>
    ///     Gets or sets DurationOverrideSeconds.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flDurationOverrideSeconds</c> at offset <c>0xB0</c>.
    /// </remarks>
    [NativeOffset(0xB0)]
    [NativeName("m_flDurationOverrideSeconds")]
    [NativeMetadata("MPropertyGroupName", "\"+Import Options\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Override the final duration of this clip in seconds (0 or a negative value means use the authored duration)\"")]
    public float DurationOverrideSeconds { get; set; }

    /// <summary>
    ///     Gets or sets EndFrame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nEndFrame</c> at offset <c>0xAC</c>.
    /// </remarks>
    [NativeOffset(0xAC)]
    [NativeName("m_nEndFrame")]
    [NativeMetadata("MPropertyGroupName", "\"+Import Options\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Specify the import end frame (0 or a negative value means use the last frame in the authored animation)\"")]
    public int EndFrame { get; set; }

    /// <summary>
    ///     Gets or sets EventTracks.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eventTracks</c> at offset <c>0x98</c>.
    /// </remarks>
    [NativeOffset(0x98)]
    [NativeName("m_eventTracks")]
    [NativeMetadata("MPropertySuppressField")]
    public CNmClipDocEventTrack[] EventTracks { get; set; }

    /// <summary>
    ///     Gets or sets SecondaryAnimationSkeletonNames.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_secondaryAnimationSkeletonNames</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_secondaryAnimationSkeletonNames")]
    [NativeMetadata("MPropertyAttributeEditor", "\"AssetBrowse( vnmskel, *requiredoubleclick )\"")]
    [NativeMetadata("MPropertyAutoExpandSelf")]
    public string[] SecondaryAnimationSkeletonNames { get; set; }

    /// <summary>
    ///     Gets or sets SourceFilename.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sourceFilename</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_sourceFilename")]
    [NativeMetadata("MPropertyAttributeEditor",
        "\"ModelDocAssetBrowse( dmx, fbx, smd, *requiredoubleclick, *ShowRelatedFile )\"")]
    public string SourceFilename { get; set; }

    /// <summary>
    ///     Gets or sets StartFrame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nStartFrame</c> at offset <c>0xA8</c>.
    /// </remarks>
    [NativeOffset(0xA8)]
    [NativeName("m_nStartFrame")]
    [NativeMetadata("MPropertyGroupName", "\"+Import Options\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Specify the import start frame (0 or a negative value means use the first frame in the authored animation)\"")]
    public int StartFrame { get; set; }

    /// <summary>
    ///     Gets or sets UseReferencePoseForSecondaryAnimAdditives.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bUseReferencePoseForSecondaryAnimAdditives</c> at offset <c>0xC8</c>.
    /// </remarks>
    [NativeOffset(0xC8)]
    [NativeName("m_bUseReferencePoseForSecondaryAnimAdditives")]
    [NativeMetadata("MPropertyGroupName", "\"+Additive\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Should we calculate the additives for the secondary weapons from their reference pose or try to look up a pose in the specified animation\"")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public bool UseReferencePoseForSecondaryAnimAdditives { get; set; }
}
