// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmGraphDocCachedFloatNode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animlib;

#endregion

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmGraphDocCachedFloatNode
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 264 bytes, align 8.
/// </remarks>
[NativeSize(264)]
public partial class CNmGraphDocCachedFloatNode : CNmGraphDocFlowNode
{
    /// <summary>
    ///     Gets or sets Mode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_mode</c> at offset <c>0x100</c>.
    /// </remarks>
    [NativeOffset(0x100)]
    [NativeName("m_mode")]
    public NmCachedValueMode Mode { get; set; }
}
