// <auto-generated/>
// CS2OpenSchema — SounddocLib/CMixConvolution
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.SoundsystemLowlevel;

#endregion

namespace CS2OpenSchema.SounddocLib;

/// <summary>
///     Apply a vsnd as an impulse response (IR) to an audio signal via convolution.
/// </summary>
/// <remarks>
///     Native name: <c>CMixConvolution</c>. Module: <c>sounddoc_lib</c> — 64 bytes, align 8.
/// </remarks>
[NativeSize(64)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CMixConvolution\",\n\t\"m_name\": \"\",\n\t\"m_Comment\": \"\",\n\t\"m_bActive\": true,\n\t\"m_bSolo\": false,\n\t\"m_bEditProperties\": false,\n\t\"m_desc\":\n\t{\n\t\t\"m_fldbGain\": -12.000000,\n\t\t\"m_flPreDelayMS\": 0.000000,\n\t\t\"m_flWetMix\": 1.000000,\n\t\t\"m_fldbLow\": 0.000000,\n\t\t\"m_fldbMid\": 0.000000,\n\t\t\"m_fldbHigh\": 0.000000,\n\t\t\"m_flLowCutoffFreq\": 1500.000000,\n\t\t\"m_flHighCutoffFreq\": 7500.000000\n\t}\n}")]
[NativeMetadata("MPropertyDescription", "Apply a vsnd as an impulse response (IR) to an audio signal via convolution.")]
[NativeMetadata("MPropertyFriendlyName", "VMix Audio Convolution Node")]
public partial class CMixConvolution : CMixPropertyBase
{
    /// <summary>
    ///     Gets or sets Desc.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_desc</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_desc")]
    [NativeMetadata("MPropertyAutoExpandSelf", "")]
    public VMixConvolutionDesc Desc { get; set; }
}
