// <auto-generated/>
// CS2OpenSchema — Events/BombDefusedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     Fired when the C4 is successfully defused.  `userid` is the defuser; `site` is the bombsite.
/// </summary>
/// <remarks>
///     Native name: <c>bomb_defused</c>. Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("bomb_defused")]
[GameEventSource("mod.gameevents")]
public sealed partial record BombDefusedEvent
{
    /// <summary>
    ///     C4.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>c4</c> — KV1 type <c>short</c>.
    /// </remarks>
    [NativeName("c4")]
    [GameEventFieldType("short")]
    public required short C4 { get; init; }

    /// <summary>
    ///     bombsite index.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>site</c> — KV1 type <c>short</c>.
    /// </remarks>
    [NativeName("site")]
    [GameEventFieldType("short")]
    public required short Site { get; init; }

    /// <summary>
    ///     player who defused the bomb.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller_and_pawn</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller_and_pawn")]
    public required int UserId { get; init; }

    /// <summary>
    ///     Entity handle of the pawn for `userid`. Companion wire key `userid_pawn`, emitted by the engine alongside `userid` for the player_controller_and_pawn type.
    /// </summary>
    /// <remarks>
    ///     Wire key: <c>userid_pawn</c>, derived by the engine from the <c>player_controller_and_pawn</c> type rather than declared as a field.
    /// </remarks>
    [NativeName("userid_pawn")]
    [GameEventFieldType("player_controller_and_pawn")]
    public required uint UserIdPawn { get; init; }
}
