// <auto-generated/>
// CS2OpenSchema — Events/ChoppersIncomingWarningEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     choppers_incoming_warning.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("choppers_incoming_warning")]
[GameEventSource("mod.gameevents")]
public sealed partial record ChoppersIncomingWarningEvent
{
    /// <summary>
    ///     Global.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>global</c> — KV1 type <c>bool</c>.
    /// </remarks>
    [NativeName("global")]
    [GameEventFieldType("bool")]
    public required bool Global { get; init; }
}
