// <auto-generated/>
// CS2OpenSchema — Events/ClientDisconnectEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25175329 — 2026-09-07T21:44:07Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     client_disconnect.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("client_disconnect")]
[GameEventSource("mod.gameevents")]
public sealed partial record ClientDisconnectEvent
{
}
