// <auto-generated/>
// CS2OpenSchema — Events/ClientLoadoutChangedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     client_loadout_changed.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("client_loadout_changed")]
[GameEventSource("game.gameevents")]
public sealed partial record ClientLoadoutChangedEvent
{
}
