// <auto-generated/>
// CS2OpenSchema — Events/CsPreRestartEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25218825 — 2026-09-09T22:31:50Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     cs_pre_restart.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("cs_pre_restart")]
[GameEventSource("mod.gameevents")]
public sealed partial record CsPreRestartEvent
{
}
