// <auto-generated/>
// CS2OpenSchema — Events/DoorOpenEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25218825 — 2026-09-09T22:31:50Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     door_open.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("door_open")]
[GameEventSource("game.gameevents")]
public sealed partial record DoorOpenEvent
{
    /// <summary>
    ///     EntIndex.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>entindex</c> — KV1 type <c>long</c>.
    /// </remarks>
    [NativeName("entindex")]
    [GameEventFieldType("long")]
    public required int EntIndex { get; init; }

    /// <summary>
    ///     Who closed the door.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_pawn</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_pawn")]
    public required uint UserId { get; init; }
}
