// <auto-generated/>
// CS2OpenSchema — Events/DropRateModifiedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25218825 — 2026-09-09T22:31:50Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     drop_rate_modified.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
/// </remarks>
[NativeName("drop_rate_modified")]
[GameEventSource("core.gameevents")]
public sealed partial record DropRateModifiedEvent
{
}
