// <auto-generated/>
// CS2OpenSchema — Events/EndMatchCmmStartRevealItemsEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     endmatch_cmm_start_reveal_items.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("endmatch_cmm_start_reveal_items")]
[GameEventSource("game.gameevents")]
public sealed partial record EndMatchCmmStartRevealItemsEvent
{
}
