// <auto-generated/>
// CS2OpenSchema — Events/EventTicketModifiedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25175329 — 2026-09-07T21:44:07Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     event_ticket_modified.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
/// </remarks>
[NativeName("event_ticket_modified")]
[GameEventSource("core.gameevents")]
public sealed partial record EventTicketModifiedEvent
{
}
