// <auto-generated/>
// CS2OpenSchema — Events/ExitBombzoneEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     exit_bombzone.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("exit_bombzone")]
[GameEventSource("mod.gameevents")]
public sealed partial record ExitBombzoneEvent
{
    /// <summary>
    ///     Hasbomb.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>hasbomb</c> — KV1 type <c>bool</c>.
    /// </remarks>
    [NativeName("hasbomb")]
    [GameEventFieldType("bool")]
    public required bool Hasbomb { get; init; }

    /// <summary>
    ///     Isplanted.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>isplanted</c> — KV1 type <c>bool</c>.
    /// </remarks>
    [NativeName("isplanted")]
    [GameEventFieldType("bool")]
    public required bool Isplanted { get; init; }

    /// <summary>
    ///     Userid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int Userid { get; init; }
}
