// <auto-generated/>
// CS2OpenSchema — Events/HltvChatEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     hltv_chat.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
///     <para>a HLTV chat msg sent by spectators</para>
/// </remarks>
[NativeName("hltv_chat")]
[GameEventSource("core.gameevents")]
public sealed partial record HltvChatEvent
{
    /// <summary>
    ///     steam id.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>steamID</c> — KV1 type <c>uint64</c>.
    /// </remarks>
    [NativeName("steamID")]
    [GameEventFieldType("uint64")]
    public required ulong SteamID { get; init; }

    /// <summary>
    ///     Text.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>text</c> — KV1 type <c>string</c>.
    /// </remarks>
    [NativeName("text")]
    [GameEventFieldType("string")]
    public required string Text { get; init; }
}
