// <auto-generated/>
// CS2OpenSchema — Events/NavGenerateEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     nav_generate.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("nav_generate")]
[GameEventSource("mod.gameevents")]
public sealed partial record NavGenerateEvent
{
}
