// <auto-generated/>
// CS2OpenSchema — Events/PlayerGivenC4Event
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     player_given_c4.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("player_given_c4")]
[GameEventSource("mod.gameevents")]
public sealed partial record PlayerGivenC4Event
{
    /// <summary>
    ///     user ID who received the c4.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int Userid { get; init; }
}
