// <auto-generated/>
// CS2OpenSchema — Events/PlayerSpawnEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     player_spawn.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
///     <para>player spawned in game</para>
/// </remarks>
[NativeName("player_spawn")]
[GameEventSource("core.gameevents")]
public sealed partial record PlayerSpawnEvent
{
    /// <summary>
    ///     Userid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller_and_pawn</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller_and_pawn")]
    public required int Userid { get; init; }
}
