// <auto-generated/>
// CS2OpenSchema — Events/PlayerActivateEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     player_activate.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
/// </remarks>
[NativeName("player_activate")]
[GameEventSource("core.gameevents")]
public sealed partial record PlayerActivateEvent
{
    /// <summary>
    ///     user ID on server.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int UserId { get; init; }
}
