// <auto-generated/>
// CS2OpenSchema — Events/PlayerDecalEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     player_decal.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("player_decal")]
[GameEventSource("game.gameevents")]
public sealed partial record PlayerDecalEvent
{
    /// <summary>
    ///     Userid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_pawn</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_pawn")]
    public required int Userid { get; init; }
}
