// <auto-generated/>
// CS2OpenSchema — Events/PlayerFullUpdateEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     player_full_update.
/// </summary>
/// <remarks>
///     Source: <c>core.gameevents</c>.
/// </remarks>
[NativeName("player_full_update")]
[GameEventSource("core.gameevents")]
public sealed partial record PlayerFullUpdateEvent
{
    /// <summary>
    ///     Number of this full update.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>count</c> — KV1 type <c>short</c>.
    /// </remarks>
    [NativeName("count")]
    [GameEventFieldType("short")]
    public required short Count { get; init; }

    /// <summary>
    ///     user ID on server.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int UserId { get; init; }
}
