// <auto-generated/>
// CS2OpenSchema — Events/RoundFreezeEndEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     Fired when the buy/freeze period ends and live play begins. Players regain movement; this is the canonical "round live" tick for demo-parsing tooling and stat trackers.
/// </summary>
/// <remarks>
///     Native name: <c>round_freeze_end</c>. Source: <c>core.gameevents</c>.
/// </remarks>
[NativeName("round_freeze_end")]
[GameEventSource("core.gameevents")]
public sealed partial record RoundFreezeEndEvent
{
}
