// <auto-generated/>
// CS2OpenSchema — Events/SmokeBeaconParadropEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     smoke_beacon_paradrop.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("smoke_beacon_paradrop")]
[GameEventSource("mod.gameevents")]
public sealed partial record SmokeBeaconParadropEvent
{
    /// <summary>
    ///     Paradrop.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>paradrop</c> — KV1 type <c>short</c>.
    /// </remarks>
    [NativeName("paradrop")]
    [GameEventFieldType("short")]
    public required short Paradrop { get; init; }

    /// <summary>
    ///     UserId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int UserId { get; init; }
}
