// <auto-generated/>
// CS2OpenSchema — Events/StartVoteEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     start_vote.
/// </summary>
/// <remarks>
///     Source: <c>mod.gameevents</c>.
/// </remarks>
[NativeName("start_vote")]
[GameEventSource("mod.gameevents")]
public sealed partial record StartVoteEvent
{
    /// <summary>
    ///     Type.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>type</c> — KV1 type <c>byte</c>.
    /// </remarks>
    [NativeName("type")]
    [GameEventFieldType("byte")]
    public required byte Type { get; init; }

    /// <summary>
    ///     Userid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>userid</c> — KV1 type <c>player_controller</c>.
    /// </remarks>
    [NativeName("userid")]
    [GameEventFieldType("player_controller")]
    public required int Userid { get; init; }

    /// <summary>
    ///     VoteParameter.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>vote_parameter</c> — KV1 type <c>short</c>.
    /// </remarks>
    [NativeName("vote_parameter")]
    [GameEventFieldType("short")]
    public required short VoteParameter { get; init; }
}
