// <auto-generated/>
// CS2OpenSchema — Events/UgcMapInfoReceivedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     ugc_map_info_received.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("ugc_map_info_received")]
[GameEventSource("game.gameevents")]
public sealed partial record UgcMapInfoReceivedEvent
{
    /// <summary>
    ///     PublishedFileId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>published_file_id</c> — KV1 type <c>uint64</c>.
    /// </remarks>
    [NativeName("published_file_id")]
    [GameEventFieldType("uint64")]
    public required ulong PublishedFileId { get; init; }
}
