// <auto-generated/>
// CS2OpenSchema — Events/UgcMapUnsubscribedEvent
// Generated from upstream gameevents_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable

namespace CS2OpenSchema.Events;

/// <summary>
///     ugc_map_unsubscribed.
/// </summary>
/// <remarks>
///     Source: <c>game.gameevents</c>.
/// </remarks>
[NativeName("ugc_map_unsubscribed")]
[GameEventSource("game.gameevents")]
public sealed partial record UgcMapUnsubscribedEvent
{
    /// <summary>
    ///     PublishedFileId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>published_file_id</c> — KV1 type <c>uint64</c>.
    /// </remarks>
    [NativeName("published_file_id")]
    [GameEventFieldType("uint64")]
    public required ulong PublishedFileId { get; init; }
}
