// <auto-generated/>
// CS2OpenSchema — Animlib/CNmFloatRemapNodeRemapRange
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animlib;

/// <summary>
///     CNmFloatRemapNode::RemapRange_t
/// </summary>
/// <remarks>
///     Module: <c>animlib</c> — 8 bytes, align 4.
/// </remarks>
[NativeSize(8)]
[NativeName("CNmFloatRemapNode::RemapRange_t")]
public partial class CNmFloatRemapNodeRemapRange
{
    /// <summary>
    ///     Gets or sets Begin.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flBegin</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_flBegin")]
    public float Begin { get; set; }

    /// <summary>
    ///     Gets or sets End.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flEnd</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_flEnd")]
    public float End { get; set; }
}
