// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropAttributeDistributionMode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     CSmartPropAttributeDistributionMode.
/// </summary>
/// <remarks>
///     Module: <c>smartprops</c> — 64 bytes.
/// </remarks>
[NativeSize(64)]
[NativeMetadata("MPropertyCustomEditor", "SmartPropAttributeEditor(enum:SmartPropDistributionMode_t)")]
public partial class CSmartPropAttributeDistributionMode
{
}
