// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropOperationSetMateraialGroupChoice
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     Picks a material group from a set of choices and assigns that material group to a specified variable.
/// </summary>
/// <remarks>
///     Native name: <c>CSmartPropOperation_SetMateraialGroupChoice</c>. Module: <c>smartprops</c> — 240 bytes.
/// </remarks>
[NativeSize(240)]
[NativeName("CSmartPropOperation_SetMateraialGroupChoice")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CSmartPropOperation_SetMateraialGroupChoice\",\n\t\"m_bEnabled\": true,\n\t\"m_VariableName\": \"\",\n\t\"m_SelectionMode\": \"RANDOM\",\n\t\"m_ChoiceSelection\": 0,\n\t\"m_MaterialGroupChoices\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyFriendlyName", "\"Set Material Group Choice\"")]
[NativeMetadata("MPropertyDescription",
    "\"Picks a material group from a set of choices and assigns that material group to a specified variable.\"")]
[NativeMetadata("MVDataClassGroup", "\"Material\"")]
public partial class CSmartPropOperationSetMateraialGroupChoice : CSmartPropOperation
{
    /// <summary>
    ///     Specifies the index of the material group choice to pick.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ChoiceSelection</c> at offset <c>0x98</c>.
    /// </remarks>
    [NativeOffset(0x98)]
    [NativeName("m_ChoiceSelection")]
    [NativeMetadata("MPropertyFriendlyName", "\"Choice Index\"")]
    [NativeMetadata("MPropertyDescription", "\"Specifies the index of the material group choice to pick\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"( m_SelectionMode != SPECIFIC )\"")]
    public int? ChoiceSelection { get; set; }

    /// <summary>
    ///     Gets or sets MaterialGroupChoices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_MaterialGroupChoices</c> at offset <c>0xD8</c>.
    /// </remarks>
    [NativeOffset(0xD8)]
    [NativeName("m_MaterialGroupChoices")]
    [NativeMetadata("MPropertyAutoExpandSelf")]
    public MaterialGroupChoice[] MaterialGroupChoices { get; set; }

    /// <summary>
    ///     Specifies how the material group is to be selected from the authored set of choices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_SelectionMode</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_SelectionMode")]
    [NativeMetadata("MPropertyFriendlyName", "\"Selection Mode\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Specifies how the material group is to be selected from the authored set of choices\"")]
    public CSmartPropAttributeChoiceSelectionMode SelectionMode { get; set; }

    /// <summary>
    ///     Material group variable to set to the selected choice.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_VariableName</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_VariableName")]
    [NativeMetadata("MPropertyDescription", "\"Material group variable to set to the selected choice.\"")]
    [NativeMetadata("MPropertyAttributeEditor", "\"SmartPropItemNameEditor( Variable:MaterialGroup )\"")]
    [NativeMetadata("MPropertyProvidesEditContextString", "\"ToolEditContext_ID_SmartProp_Variable\"")]
    public string VariableName { get; set; }
}
