// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropOperationSetTintColor
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     Set the color tint to one color out of a pre-selected set of colors.
/// </summary>
/// <remarks>
///     Native name: <c>CSmartPropOperation_SetTintColor</c>. Module: <c>smartprops</c> — 296 bytes, align 8.
/// </remarks>
[NativeSize(296)]
[NativeName("CSmartPropOperation_SetTintColor")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CSmartPropOperation_SetTintColor\",\n\t\"m_bEnabled\": true,\n\t\"m_SelectionMode\": \"RANDOM\",\n\t\"m_ColorSelection\": 0,\n\t\"m_Mode\": \"MULTIPLY_OBJECT\",\n\t\"m_ColorChoices\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyDescription", "Set the color tint to one color out of a pre-selected set of colors.")]
[NativeMetadata("MPropertyFriendlyName", "Tint Color Choice")]
[NativeMetadata("MVDataClassGroup", "Color")]
public partial class CSmartPropOperationSetTintColor : CSmartPropOperation
{
    /// <summary>
    ///     List of possible colors which may be selected.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ColorChoices</c> at offset <c>0x110</c>.
    /// </remarks>
    [NativeOffset(0x110)]
    [NativeName("m_ColorChoices")]
    [NativeMetadata("MPropertyDescription", "List of possible colors which may be selected")]
    public CUtlVector__ColorChoice_t__ ColorChoices { get; set; }

    /// <summary>
    ///     Specifies the index of the color to pick.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ColorSelection</c> at offset <c>0x90</c>.
    /// </remarks>
    [NativeOffset(0x90)]
    [NativeName("m_ColorSelection")]
    [NativeMetadata("MPropertyDescription", "Specifies the index of the color to pick")]
    [NativeMetadata("MPropertyFriendlyName", "Color Selection")]
    [NativeMetadata("MPropertySuppressExpr", "( m_SelectionMode != SPECIFIC )")]
    public int? ColorSelection { get; set; }

    /// <summary>
    ///     Specifies how the selected color should be applied to the current color.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Mode</c> at offset <c>0xD0</c>.
    /// </remarks>
    [NativeOffset(0xD0)]
    [NativeName("m_Mode")]
    [NativeMetadata("MPropertyDescription", "Specifies how the selected color should be applied to the current color.")]
    [NativeMetadata("MPropertyFriendlyName", "Application Mode")]
    public CSmartPropAttributeApplyColorMode Mode { get; set; }

    /// <summary>
    ///     Specifies how the color is to be selected from the authored set of choices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_SelectionMode</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_SelectionMode")]
    [NativeMetadata("MPropertyDescription", "Specifies how the color is to be selected from the authored set of choices")]
    [NativeMetadata("MPropertyFriendlyName", "Selection Mode")]
    public CSmartPropAttributeChoiceSelectionMode SelectionMode { get; set; }
}
