// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CAnimUpdateNodeRef
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CAnimUpdateNodeRef.
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 16 bytes, align 8.
/// </remarks>
[NativeSize(16)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_nodeIndex\": -1\n}")]
public partial class CAnimUpdateNodeRef
{
    /// <summary>
    ///     Gets or sets NodeIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nodeIndex</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_nodeIndex")]
    public int NodeIndex { get; set; }
}
