// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CCycleControlUpdateNode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CCycleControlUpdateNode.
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 120 bytes, align 8.
/// </remarks>
[NativeSize(120)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CCycleControlUpdateNode\",\n\t\"m_nodePath\":\n\t{\n\t\t\"m_path\":\n\t\t[\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t\t}\n\t\t],\n\t\t\"m_nCount\": 0\n\t},\n\t\"m_networkMode\": \"ServerAuthoritative\",\n\t\"m_name\": \"\",\n\t\"m_pChildNode\":\n\t{\n\t\t\"m_nodeIndex\": -1\n\t},\n\t\"m_valueSource\": \"MoveHeading\",\n\t\"m_paramIndex\":\n\t{\n\t\t\"m_type\": \"ANIMPARAM_UNKNOWN\",\n\t\t\"m_index\": 255\n\t},\n\t\"m_bLockWhenWaning\": false\n}")]
public partial class CCycleControlUpdateNode : CUnaryUpdateNode
{
    /// <summary>
    ///     Gets or sets LockWhenWaning.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLockWhenWaning</c> at offset <c>0x76</c>.
    /// </remarks>
    [NativeOffset(0x76)]
    [NativeName("m_bLockWhenWaning")]
    public bool LockWhenWaning { get; set; }

    /// <summary>
    ///     Gets or sets ParamIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_paramIndex</c> at offset <c>0x74</c>.
    /// </remarks>
    [NativeOffset(0x74)]
    [NativeName("m_paramIndex")]
    public CAnimParamHandle ParamIndex { get; set; }

    /// <summary>
    ///     Gets or sets ValueSource.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_valueSource</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_valueSource")]
    public AnimValueSource ValueSource { get; set; }
}
