// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CTurnHelperInstanceData
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CTurnHelperInstanceData.
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 12 bytes, align 4.
/// </remarks>
[NativeSize(12)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_turnAmount\": 0.000000,\n\t\"m_turnStartTime\": 0.000000,\n\t\"m_duration\": 1.000000\n}")]
public partial class CTurnHelperInstanceData
{
    /// <summary>
    ///     Gets or sets Duration.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_duration</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_duration")]
    public float Duration { get; set; }

    /// <summary>
    ///     Gets or sets TurnAmount.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_turnAmount</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_turnAmount")]
    public float TurnAmount { get; set; }

    /// <summary>
    ///     Gets or sets TurnStartTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_turnStartTime</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_turnStartTime")]
    public float TurnStartTime { get; set; }
}
