// <auto-generated/>
// CS2OpenSchema — SoundsystemLowlevel/VMixPannerType
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.SoundsystemLowlevel;

/// <summary>
///     VMixPannerType_t.
/// </summary>
/// <remarks>
///     Module: <c>soundsystem_lowlevel</c> — 32-bit.
/// </remarks>
[NativeName("VMixPannerType_t")]
public enum VMixPannerType : uint
{
    /// <summary>
    ///     PannerTypeLinear.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PANNER_TYPE_LINEAR</c>.
    /// </remarks>
    [NativeName("PANNER_TYPE_LINEAR")]
    PannerTypeLinear = 0,

    /// <summary>
    ///     PannerTypeEqualPower.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PANNER_TYPE_EQUAL_POWER</c>.
    /// </remarks>
    [NativeName("PANNER_TYPE_EQUAL_POWER")]
    PannerTypeEqualPower = 1
}
