// <auto-generated/>
// CS2OpenSchema — Animationsystem/CAnimFrameBlockAnim
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animationsystem;

/// <summary>
///     CAnimFrameBlockAnim.
/// </summary>
/// <remarks>
///     Module: <c>animationsystem</c> — 32 bytes, align 8.
/// </remarks>
[NativeSize(32)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_nStartFrame\": 0,\n\t\"m_nEndFrame\": 0,\n\t\"m_segmentIndexArray\":\n\t[\n\t]\n}")]
public partial class CAnimFrameBlockAnim
{
    /// <summary>
    ///     Gets or sets EndFrame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nEndFrame</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_nEndFrame")]
    public int EndFrame { get; set; }

    /// <summary>
    ///     Gets or sets SegmentIndexArray.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_segmentIndexArray</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_segmentIndexArray")]
    public CUtlVector__int32__ SegmentIndexArray { get; set; }

    /// <summary>
    ///     Gets or sets StartFrame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nStartFrame</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_nStartFrame")]
    public int StartFrame { get; set; }
}
