// <auto-generated/>
// CS2OpenSchema — Animationsystem/CAnimSequenceParams
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animationsystem;

/// <summary>
///     CAnimSequenceParams.
/// </summary>
/// <remarks>
///     Module: <c>animationsystem</c> — 8 bytes, align 4.
/// </remarks>
[NativeSize(8)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_flFadeInTime\": 0.200000,\n\t\"m_flFadeOutTime\": 0.200000\n}")]
public partial class CAnimSequenceParams
{
    /// <summary>
    ///     Gets or sets FadeInTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFadeInTime</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_flFadeInTime")]
    public float FadeInTime { get; set; }

    /// <summary>
    ///     Gets or sets FadeOutTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFadeOutTime</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_flFadeOutTime")]
    public float FadeOutTime { get; set; }
}
