// <auto-generated/>
// CS2OpenSchema — Client/AIMotorDebugSnapshotData
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     AI_Motor_DebugSnapshotData_t
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32 bytes, align 8.
/// </remarks>
[NativeSize(32)]
[NativeName("AI_Motor_DebugSnapshotData_t")]
public partial class AIMotorDebugSnapshotData : DebugSnapshotBaseStructuredData
{
    /// <summary>
    ///     Gets or sets CurrentMovementGait.
    /// </summary>
    /// <remarks>
    ///     Native field <c>current_movement_gait</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("current_movement_gait")]
    public string CurrentMovementGait { get; set; }

    /// <summary>
    ///     Gets or sets CurrentMovementGaitSet.
    /// </summary>
    /// <remarks>
    ///     Native field <c>current_movement_gait_set</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("current_movement_gait_set")]
    public string CurrentMovementGaitSet { get; set; }

    /// <summary>
    ///     Gets or sets MovementSettingId.
    /// </summary>
    /// <remarks>
    ///     Native field <c>movement_setting_id</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("movement_setting_id")]
    public string MovementSettingId { get; set; }
}
