// <auto-generated/>
// CS2OpenSchema — Client/BodySectionAuthority
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     BodySectionAuthority_t
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32-bit.
/// </remarks>
[NativeName("BodySectionAuthority_t")]
public enum BodySectionAuthority : uint
{
    /// <summary>
    ///     None
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eNone</c>
    /// </remarks>
    [NativeName("eNone")]
    None = 0,

    /// <summary>
    ///     LowerBody
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eLowerBody</c>
    /// </remarks>
    [NativeName("eLowerBody")]
    LowerBody = 1,

    /// <summary>
    ///     UpperBody
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eUpperBody</c>
    /// </remarks>
    [NativeName("eUpperBody")]
    UpperBody = 2,

    /// <summary>
    ///     FullBody
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eFullBody</c>
    /// </remarks>
    [NativeName("eFullBody")]
    FullBody = 3
}
