// <auto-generated/>
// CS2OpenSchema — Client/C_FootstepControl
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     C_FootstepControl
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 4232 bytes, align 8.
/// </remarks>
[NativeSize(4232)]
public partial class C_FootstepControl : C_BaseTrigger
{
    /// <summary>
    ///     Gets or sets Destination.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_destination</c> at offset <c>0x1080</c>.
    /// </remarks>
    [NativeOffset(0x1080)]
    [NativeName("m_destination")]
    public string Destination { get; set; }

    /// <summary>
    ///     Gets or sets Source.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_source</c> at offset <c>0x1078</c>.
    /// </remarks>
    [NativeOffset(0x1078)]
    [NativeName("m_source")]
    public string Source { get; set; }
}
