// <auto-generated/>
// CS2OpenSchema — Client/CCash
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CCashStack
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 4016 bytes, align 8.
/// </remarks>
[NativeSize(4016)]
[NativeName("CCashStack")]
public partial class CCash : C_BaseModelEntity
{
    /// <summary>
    ///     Gets or sets CashStackValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nCashStackValue</c> at offset <c>0xFA8</c>.
    /// </remarks>
    [NativeOffset(0xFA8)]
    [NativeName("m_nCashStackValue")]
    public int CashStackValue { get; set; }
}
