// <auto-generated/>
// CS2OpenSchema — Client/CCSGOPreviewModelAliasCsgoItemPreviewmodel
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     C_CSGO_PreviewModelAlias_csgo_item_previewmodel.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 5736 bytes.
/// </remarks>
[NativeSize(5736)]
[NativeName("C_CSGO_PreviewModelAlias_csgo_item_previewmodel")]
public partial class CCSGOPreviewModelAliasCsgoItemPreviewmodel : CCSGOPreviewModel
{
}
