// <auto-generated/>
// CS2OpenSchema — Client/InteractionPassive
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     InteractionPassive_t.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32-bit.
/// </remarks>
[NativeName("InteractionPassive_t")]
public enum InteractionPassive : uint
{
    /// <summary>
    ///     InteractPassiveNone.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>INTERACT_PASSIVE_NONE</c>.
    /// </remarks>
    [NativeName("INTERACT_PASSIVE_NONE")]
    InteractPassiveNone = 0,

    /// <summary>
    ///     InteractPassiveLookat.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>INTERACT_PASSIVE_LOOKAT</c>.
    /// </remarks>
    [NativeName("INTERACT_PASSIVE_LOOKAT")]
    InteractPassiveLookat = 1,

    /// <summary>
    ///     InteractPassiveSpeak.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>INTERACT_PASSIVE_SPEAK</c>.
    /// </remarks>
    [NativeName("INTERACT_PASSIVE_SPEAK")]
    InteractPassiveSpeak = 2
}
