// <auto-generated/>
// CS2OpenSchema — Client/PreviewCharacterBannerAnimation
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     PreviewCharacterBannerAnimation.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32-bit.
/// </remarks>
public enum PreviewCharacterBannerAnimation : uint
{
    /// <summary>
    ///     Invalid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>INVALID</c>.
    /// </remarks>
    [NativeName("INVALID")]
    Invalid = 4294967295,

    /// <summary>
    ///     IdleOffscreen.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>IDLE_OFFSCREEN</c>.
    /// </remarks>
    [NativeName("IDLE_OFFSCREEN")]
    IdleOffscreen = 0,

    /// <summary>
    ///     BannerAwpAceGun.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_GUN</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_GUN")]
    BannerAwpAceGun = 1,

    /// <summary>
    ///     BannerAwpAceA.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_A</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_A")]
    BannerAwpAceA = 2,

    /// <summary>
    ///     BannerAwpAceB.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_B</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_B")]
    BannerAwpAceB = 3,

    /// <summary>
    ///     BannerAwpAceC.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_C</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_C")]
    BannerAwpAceC = 4,

    /// <summary>
    ///     BannerAwpAceD.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_D</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_D")]
    BannerAwpAceD = 5,

    /// <summary>
    ///     BannerAwpAceE.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_AWP_ACE_E</c>.
    /// </remarks>
    [NativeName("BANNER_AWP_ACE_E")]
    BannerAwpAceE = 6,

    /// <summary>
    ///     BannerPistol3shot.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_PISTOL3SHOT</c>.
    /// </remarks>
    [NativeName("BANNER_PISTOL3SHOT")]
    BannerPistol3shot = 7,

    /// <summary>
    ///     Banner3shotA.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_3SHOT_A</c>.
    /// </remarks>
    [NativeName("BANNER_3SHOT_A")]
    Banner3shotA = 8,

    /// <summary>
    ///     Banner3shotB.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_3SHOT_B</c>.
    /// </remarks>
    [NativeName("BANNER_3SHOT_B")]
    Banner3shotB = 9,

    /// <summary>
    ///     Banner3shotC.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_3SHOT_C</c>.
    /// </remarks>
    [NativeName("BANNER_3SHOT_C")]
    Banner3shotC = 10,

    /// <summary>
    ///     BannerPistol4shot.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_PISTOL4SHOT</c>.
    /// </remarks>
    [NativeName("BANNER_PISTOL4SHOT")]
    BannerPistol4shot = 11,

    /// <summary>
    ///     Banner4shotA.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_4SHOT_A</c>.
    /// </remarks>
    [NativeName("BANNER_4SHOT_A")]
    Banner4shotA = 12,

    /// <summary>
    ///     Banner4shotB.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_4SHOT_B</c>.
    /// </remarks>
    [NativeName("BANNER_4SHOT_B")]
    Banner4shotB = 13,

    /// <summary>
    ///     Banner4shotC.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_4SHOT_C</c>.
    /// </remarks>
    [NativeName("BANNER_4SHOT_C")]
    Banner4shotC = 14,

    /// <summary>
    ///     Banner4shotD.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_4SHOT_D</c>.
    /// </remarks>
    [NativeName("BANNER_4SHOT_D")]
    Banner4shotD = 15,

    /// <summary>
    ///     CelebrateStretchNoweapIdle0.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>CELEBRATE_STRETCH_NOWEAP_IDLE0</c>.
    /// </remarks>
    [NativeName("CELEBRATE_STRETCH_NOWEAP_IDLE0")]
    CelebrateStretchNoweapIdle0 = 16,

    /// <summary>
    ///     BannerBombPlant.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_PLANT</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_PLANT")]
    BannerBombPlant = 17,

    /// <summary>
    ///     BannerBombDefusalVer.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_DEFUSAL_VER</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_DEFUSAL_VER")]
    BannerBombDefusalVer = 18,

    /// <summary>
    ///     BannerFire.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_FIRE</c>.
    /// </remarks>
    [NativeName("BANNER_FIRE")]
    BannerFire = 19,

    /// <summary>
    ///     BannerBombBlastToss.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_BLAST_TOSS</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_BLAST_TOSS")]
    BannerBombBlastToss = 20,

    /// <summary>
    ///     BannerBombBlast01.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_BLAST01</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_BLAST01")]
    BannerBombBlast01 = 21,

    /// <summary>
    ///     BannerBombBlast02.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_BLAST02</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_BLAST02")]
    BannerBombBlast02 = 22,

    /// <summary>
    ///     BannerBombBlast03.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_BOMB_BLAST03</c>.
    /// </remarks>
    [NativeName("BANNER_BOMB_BLAST03")]
    BannerBombBlast03 = 23,

    /// <summary>
    ///     BannerCelebrate01.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_CELEBRATE_01</c>.
    /// </remarks>
    [NativeName("BANNER_CELEBRATE_01")]
    BannerCelebrate01 = 24,

    /// <summary>
    ///     BannerCelebrate02.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_CELEBRATE_02</c>.
    /// </remarks>
    [NativeName("BANNER_CELEBRATE_02")]
    BannerCelebrate02 = 25,

    /// <summary>
    ///     BannerCelebrate03.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_CELEBRATE_03</c>.
    /// </remarks>
    [NativeName("BANNER_CELEBRATE_03")]
    BannerCelebrate03 = 26,

    /// <summary>
    ///     BannerCelebrate04.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>BANNER_CELEBRATE_04</c>.
    /// </remarks>
    [NativeName("BANNER_CELEBRATE_04")]
    BannerCelebrate04 = 27
}
