// <auto-generated/>
// CS2OpenSchema — MathlibExtended/FuseVariableAccess
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.MathlibExtended;

/// <summary>
///     FuseVariableAccess_t.
/// </summary>
/// <remarks>
///     Module: <c>mathlib_extended</c> — 8-bit.
/// </remarks>
[NativeName("FuseVariableAccess_t")]
public enum FuseVariableAccess : byte
{
    /// <summary>
    ///     Writable.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>WRITABLE</c>.
    /// </remarks>
    [NativeName("WRITABLE")]
    Writable = 0,

    /// <summary>
    ///     ReadOnly.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>READ_ONLY</c>.
    /// </remarks>
    [NativeName("READ_ONLY")]
    ReadOnly = 1
}
