// <auto-generated/>
// CS2OpenSchema — Hammer/ImportExportOptionsEditableData
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Hammer;

/// <summary>
///     ImportExportOptionsEditableData_t
/// </summary>
/// <remarks>
///     Module: <c>hammer</c> — 16 bytes.
/// </remarks>
[NativeSize(16)]
[NativeName("ImportExportOptionsEditableData_t")]
public partial class ImportExportOptionsEditableData
{
    /// <summary>
    ///     Gets or sets ExportDefaultFormat.
    /// </summary>
    /// <remarks>
    ///     Native field <c>nExportDefaultFormat</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("nExportDefaultFormat")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export Default Format\"")]
    public ImportExportOptionsEditableDataTExportDefaultFormat ExportDefaultFormat { get; set; }

    /// <summary>
    ///     Gets or sets ExportEncoding.
    /// </summary>
    /// <remarks>
    ///     Native field <c>nExportEncoding</c> at offset <c>0xC</c>.
    /// </remarks>
    [NativeOffset(0xC)]
    [NativeName("nExportEncoding")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export Encoding\"")]
    public ImportExportOptionsEditableDataTExportEncoding ExportEncoding { get; set; }

    /// <summary>
    ///     Gets or sets ExportFbxEmbedTextures.
    /// </summary>
    /// <remarks>
    ///     Native field <c>bExportFbxEmbedTextures</c> at offset <c>0x2</c>.
    /// </remarks>
    [NativeOffset(0x2)]
    [NativeName("bExportFbxEmbedTextures")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export FBX Embed Textures From Content If Available\"")]
    [NativeMetadata("MPropertySuppressField")]
    public bool ExportFbxEmbedTextures { get; set; }

    /// <summary>
    ///     Gets or sets ExportFbxUnit.
    /// </summary>
    /// <remarks>
    ///     Native field <c>nExportFbxUnit</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("nExportFbxUnit")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export Hammer Units To FBX Units\"")]
    public ImportExportOptionsEditableDataTExportFbxUnit ExportFbxUnit { get; set; }

    /// <summary>
    ///     Gets or sets ExportHidden.
    /// </summary>
    /// <remarks>
    ///     Native field <c>bExportHidden</c> at offset <c>0x1</c>.
    /// </remarks>
    [NativeOffset(0x1)]
    [NativeName("bExportHidden")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export Hidden Objects\"")]
    public bool ExportHidden { get; set; }

    /// <summary>
    ///     Gets or sets ExportProps.
    /// </summary>
    /// <remarks>
    ///     Native field <c>bExportProps</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("bExportProps")]
    [NativeMetadata("MPropertyFriendlyName", "\"Export Props\"")]
    public bool ExportProps { get; set; }
}
