// <auto-generated/>
// CS2OpenSchema — Physicslib/FeTri
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Physicslib;

/// <summary>
///     FeTri_t.
/// </summary>
/// <remarks>
///     Module: <c>physicslib</c> — 28 bytes, align 4.
/// </remarks>
[NativeSize(28)]
[NativeName("FeTri_t")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"nNode\":\n\t[\n\t\t0,\n\t\t0,\n\t\t0\n\t],\n\t\"w1\": 0.000000,\n\t\"w2\": 0.000000,\n\t\"v1x\": 0.000000,\n\t\"v2\":\n\t[\n\t\t0.000000,\n\t\t0.000000\n\t]\n}")]
public partial class FeTri
{
    /// <summary>
    ///     Gets or sets Node.
    /// </summary>
    /// <remarks>
    ///     Native field <c>nNode</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("nNode")]
    public ushort[] Node { get; set; }

    /// <summary>
    ///     Gets or sets V1x.
    /// </summary>
    /// <remarks>
    ///     Native field <c>v1x</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("v1x")]
    public float V1x { get; set; }

    /// <summary>
    ///     Gets or sets V2.
    /// </summary>
    /// <remarks>
    ///     Native field <c>v2</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("v2")]
    public Vector2D V2 { get; set; }

    /// <summary>
    ///     Gets or sets W1.
    /// </summary>
    /// <remarks>
    ///     Native field <c>w1</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("w1")]
    public float W1 { get; set; }

    /// <summary>
    ///     Gets or sets W2.
    /// </summary>
    /// <remarks>
    ///     Native field <c>w2</c> at offset <c>0xC</c>.
    /// </remarks>
    [NativeOffset(0xC)]
    [NativeName("w2")]
    public float W2 { get; set; }
}
