// <auto-generated/>
// CS2OpenSchema — Toolscene/CLightRigSky
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Resourcesystem;

#endregion

namespace CS2OpenSchema.Toolscene;

/// <summary>
///     CLightRigSky.
/// </summary>
/// <remarks>
///     Module: <c>toolscene</c> — 8 bytes, align 8.
/// </remarks>
[NativeSize(8)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_hSkyMaterial\": \"\"\n}")]
public partial class CLightRigSky
{
    /// <summary>
    ///     Gets or sets SkyMaterial.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hSkyMaterial</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_hSkyMaterial")]
    public CStrongHandle<InfoForResourceTypeIMaterial2> SkyMaterial { get; set; }
}
