// <auto-generated/>
// CS2OpenSchema — Animlib/CNmEntityAttributeIntEvent
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animlib;

/// <summary>
///     CNmEntityAttributeIntEvent.
/// </summary>
/// <remarks>
///     Module: <c>animlib</c> — 64 bytes, align 8.
/// </remarks>
[NativeSize(64)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CNmEntityAttributeIntEvent\",\n\t\"m_flStartTime\":\n\t{\n\t\t\"m_flValue\": 0.000000\n\t},\n\t\"m_flDuration\":\n\t{\n\t\t\"m_flValue\": 0.000000\n\t},\n\t\"m_syncID\": \"\",\n\t\"m_target\": \"Self\",\n\t\"m_attributeName\": \"\",\n\t\"m_nIntValue\": 0\n}")]
public partial class CNmEntityAttributeIntEvent : CNmEntityAttributeEventBase
{
    /// <summary>
    ///     Gets or sets IntValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nIntValue</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_nIntValue")]
    public int IntValue { get; set; }
}
