// <auto-generated/>
// CS2OpenSchema — Animlib/CNmIdEventPercentageThroughNodeCDefinition
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animlib;

/// <summary>
///     CNmIDEventPercentageThroughNode::CDefinition.
/// </summary>
/// <remarks>
///     Module: <c>animlib</c> — 32 bytes, align 8.
/// </remarks>
[NativeSize(32)]
[NativeName("CNmIDEventPercentageThroughNode::CDefinition")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CNmIDEventPercentageThroughNode::CDefinition\",\n\t\"m_nNodeIdx\": -1,\n\t\"m_nSourceStateNodeIdx\": -1,\n\t\"m_eventConditionRules\":\n\t{\n\t\t\"m_flags\": 0\n\t},\n\t\"m_eventID\": \"\"\n}")]
public partial class CNmIdEventPercentageThroughNodeCDefinition : CNmBoolValueNodeCDefinition
{
    /// <summary>
    ///     Gets or sets EventConditionRules.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eventConditionRules</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_eventConditionRules")]
    public CNmBitFlags EventConditionRules { get; set; }

    /// <summary>
    ///     Gets or sets EventId.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eventID</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_eventID")]
    public string EventId { get; set; }

    /// <summary>
    ///     Gets or sets SourceStateNodeIdx.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nSourceStateNodeIdx</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_nSourceStateNodeIdx")]
    public short SourceStateNodeIdx { get; set; }
}
