// <auto-generated/>
// CS2OpenSchema — Animlib/CNmSyncTrack
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animlib;

/// <summary>
///     CNmSyncTrack.
/// </summary>
/// <remarks>
///     Module: <c>animlib</c> — 176 bytes.
/// </remarks>
[NativeSize(176)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_syncEvents\":\n\t[\n\t\t{\n\t\t\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\t\t\"m_startTime\":\n\t\t\t{\n\t\t\t\t\"m_flValue\": 0.000000\n\t\t\t},\n\t\t\t\"m_duration\":\n\t\t\t{\n\t\t\t\t\"m_flValue\": 1.000000\n\t\t\t}\n\t\t}\n\t],\n\t\"m_nStartEventOffset\": 0\n}")]
public partial class CNmSyncTrack
{
    /// <summary>
    ///     Gets or sets StartEventOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nStartEventOffset</c> at offset <c>0xA8</c>.
    /// </remarks>
    [NativeOffset(0xA8)]
    [NativeName("m_nStartEventOffset")]
    public int StartEventOffset { get; set; }

    /// <summary>
    ///     Gets or sets SyncEvents.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_syncEvents</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_syncEvents")]
    public CNmSyncTrackEvent[] SyncEvents { get; set; }
}
