// <auto-generated/>
// CS2OpenSchema — PulseSystem/CPulseCellOutflowTestExplicitYesNo
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.PulseRuntimeLib;

#endregion

namespace CS2OpenSchema.PulseSystem;

/// <summary>
///     Test node that picks between two outflows as specified in the test domain.
/// </summary>
/// <remarks>
///     Native name: <c>CPulseCell_Outflow_TestExplicitYesNo</c>. Module: <c>pulse_system</c> — 216 bytes, align 8.
/// </remarks>
[NativeSize(216)]
[NativeName("CPulseCell_Outflow_TestExplicitYesNo")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CPulseCell_Outflow_TestExplicitYesNo\",\n\t\"m_nEditorNodeID\": -1,\n\t\"m_Yes\":\n\t{\n\t\t\"m_SourceOutflowName\": \"\",\n\t\t\"m_nDestChunk\": -1,\n\t\t\"m_nInstruction\": -1\n\t},\n\t\"m_No\":\n\t{\n\t\t\"m_SourceOutflowName\": \"\",\n\t\t\"m_nDestChunk\": -1,\n\t\t\"m_nInstruction\": -1\n\t}\n}")]
[NativeMetadata("MPropertyDescription", "Test node that picks between two outflows as specified in the test domain.")]
[NativeMetadata("MPropertyFriendlyName", "[Test] Explicit Yes/No Outflow")]
public partial class CPulseCellOutflowTestExplicitYesNo : CPulseCellBaseFlow
{
    /// <summary>
    ///     No.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_No</c> at offset <c>0x90</c>.
    /// </remarks>
    [NativeOffset(0x90)]
    [NativeName("m_No")]
    [NativeMetadata("MPropertyFriendlyName", "No")]
    public CPulseOutflowConnection No { get; set; }

    /// <summary>
    ///     Yes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Yes</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_Yes")]
    [NativeMetadata("MPropertyFriendlyName", "Yes")]
    public CPulseOutflowConnection Yes { get; set; }
}
