// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocGroupInputNode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     Group Input.
/// </summary>
/// <remarks>
///     Native name: <c>CAnimGraphDoc_GroupInputNode</c>. Module: <c>animgraphdoclib</c> — 104 bytes.
/// </remarks>
[NativeSize(104)]
[NativeName("CAnimGraphDoc_GroupInputNode")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CAnimGraphDoc_GroupInputNode\",\n\t\"m_sName\": \"Unnamed\",\n\t\"m_vecPosition\":\n\t[\n\t\t0.000000,\n\t\t0.000000\n\t],\n\t\"m_nNodeID\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_bDebugThisNode\": false,\n\t\"m_networkMode\": \"ServerAuthoritative\",\n\t\"m_proxyItems\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyFriendlyName", "\"Group Input\"")]
public partial class CAnimGraphDocGroupInputNode : CAnimGraphDocProxyNodeBase
{
}
