// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocTagSpan
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Modellib;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     CAnimGraphDoc_TagSpan.
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 48 bytes, align 8.
/// </remarks>
[NativeSize(48)]
[NativeName("CAnimGraphDoc_TagSpan")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CAnimGraphDoc_TagSpan\",\n\t\"m_id\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_fStartCycle\": 0.000000,\n\t\"m_fDuration\": 0.100000\n}")]
public partial class CAnimGraphDocTagSpan
{
    /// <summary>
    ///     Gets or sets Duration.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fDuration</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_fDuration")]
    public float Duration { get; set; }

    /// <summary>
    ///     Gets or sets Id.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_id</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_id")]
    public AnimTagId Id { get; set; }

    /// <summary>
    ///     Gets or sets StartCycle.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fStartCycle</c> at offset <c>0x24</c>.
    /// </remarks>
    [NativeOffset(0x24)]
    [NativeName("m_fStartCycle")]
    public float StartCycle { get; set; }
}
