// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocSingleFrameNode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.GlobalTypes;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     Single Frame.
/// </summary>
/// <remarks>
///     Native name: <c>CAnimGraphDoc_SingleFrameNode</c>. Module: <c>animgraphdoclib</c> — 120 bytes, align 8.
/// </remarks>
[NativeSize(120)]
[NativeName("CAnimGraphDoc_SingleFrameNode")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CAnimGraphDoc_SingleFrameNode\",\n\t\"m_sName\": \"Unnamed\",\n\t\"m_vecPosition\":\n\t[\n\t\t0.000000,\n\t\t0.000000\n\t],\n\t\"m_nNodeID\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_bDebugThisNode\": false,\n\t\"m_networkMode\": \"ServerAuthoritative\",\n\t\"m_sequenceName\": \"\",\n\t\"m_eFrameSelection\": \"SpecificFrame\",\n\t\"m_nFrameIndex\": 0,\n\t\"m_actions\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyFriendlyName", "Single Frame")]
public partial class CAnimGraphDocSingleFrameNode : CAnimGraphDocNode
{
    /// <summary>
    ///     Gets or sets Actions.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_actions</c> at offset <c>0x60</c>.
    /// </remarks>
    [NativeOffset(0x60)]
    [NativeName("m_actions")]
    public CUtlVector__CSmartPtr__CAnimGraphDoc_Action____ Actions { get; set; }

    /// <summary>
    ///     Frame Index.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nFrameIndex</c> at offset <c>0x5C</c>.
    /// </remarks>
    [NativeOffset(0x5C)]
    [NativeName("m_nFrameIndex")]
    [NativeMetadata("MPropertyAttrStateCallback", "")]
    [NativeMetadata("MPropertyFriendlyName", "Frame Index")]
    public int FrameIndex { get; set; }

    /// <summary>
    ///     Frame Selection.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eFrameSelection</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_eFrameSelection")]
    [NativeMetadata("MPropertyAutoRebuildOnChange", "")]
    [NativeMetadata("MPropertyFriendlyName", "Frame Selection")]
    public SingleFrameSelection FrameSelection { get; set; }

    /// <summary>
    ///     Sequence.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sequenceName</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_sequenceName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Sequence")]
    [NativeMetadata("MPropertyFriendlyName", "Sequence")]
    public string SequenceName { get; set; }
}
