// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocAimCameraNode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Modellib;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     Aim Camera.
/// </summary>
/// <remarks>
///     Native name: <c>CAnimGraphDoc_AimCameraNode</c>. Module: <c>animgraphdoclib</c> — 176 bytes, align 8.
/// </remarks>
[NativeSize(176)]
[NativeName("CAnimGraphDoc_AimCameraNode")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CAnimGraphDoc_AimCameraNode\",\n\t\"m_sName\": \"Unnamed\",\n\t\"m_vecPosition\":\n\t[\n\t\t0.000000,\n\t\t0.000000\n\t],\n\t\"m_nNodeID\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_bDebugThisNode\": false,\n\t\"m_networkMode\": \"ServerAuthoritative\",\n\t\"m_inputConnection\":\n\t{\n\t\t\"m_nodeID\":\n\t\t{\n\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t},\n\t\t\"m_outputID\":\n\t\t{\n\t\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t\t}\n\t},\n\t\"m_ikChain\": \"\",\n\t\"m_cameraJointName\": \"\",\n\t\"m_pelvisJointName\": \"\",\n\t\"m_clavicleLeftJointName\": \"\",\n\t\"m_clavicleRightJointName\": \"\",\n\t\"m_parameterNamePosition\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterNameOrientation\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterNamePelvisOffset\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterCameraOnly\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterCameraClearanceDistance\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterWeaponDepenetrationDistance\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_parameterWeaponDepenetrationDelta\":\n\t{\n\t\t\"m_id\": <HIDDEN FOR DIFF>,\n\t},\n\t\"m_depenetrationJointName\": \"\",\n\t\"m_propJoints\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyFriendlyName", "Aim Camera")]
public partial class CAnimGraphDocAimCameraNode : CAnimGraphDocNode
{
    /// <summary>
    ///     Camera Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_cameraJointName</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_cameraJointName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Bone")]
    [NativeMetadata("MPropertyFriendlyName", "Camera Joint")]
    public string CameraJointName { get; set; }

    /// <summary>
    ///     Clavicle Left Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_clavicleLeftJointName</c> at offset <c>0x60</c>.
    /// </remarks>
    [NativeOffset(0x60)]
    [NativeName("m_clavicleLeftJointName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Bone")]
    [NativeMetadata("MPropertyFriendlyName", "Clavicle Left Joint")]
    public string ClavicleLeftJointName { get; set; }

    /// <summary>
    ///     Clavicle Right Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_clavicleRightJointName</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_clavicleRightJointName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Bone")]
    [NativeMetadata("MPropertyFriendlyName", "Clavicle Right Joint")]
    public string ClavicleRightJointName { get; set; }

    /// <summary>
    ///     Depenetration Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_depenetrationJointName</c> at offset <c>0x90</c>.
    /// </remarks>
    [NativeOffset(0x90)]
    [NativeName("m_depenetrationJointName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Bone")]
    [NativeMetadata("MPropertyFriendlyName", "Depenetration Joint")]
    public string DepenetrationJointName { get; set; }

    /// <summary>
    ///     Spine IK Chain.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ikChain</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_ikChain")]
    [NativeMetadata("MPropertyAttributeChoiceName", "IKChain")]
    [NativeMetadata("MPropertyFriendlyName", "Spine IK Chain")]
    public string IkChain { get; set; }

    /// <summary>
    ///     Gets or sets InputConnection.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_inputConnection</c> at offset <c>0x40</c>.
    /// </remarks>
    [NativeOffset(0x40)]
    [NativeName("m_inputConnection")]
    [NativeMetadata("MPropertySuppressField", "")]
    public CAnimGraphDocNodeConnection InputConnection { get; set; }

    /// <summary>
    ///     Clearance Distance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterCameraClearanceDistance</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_parameterCameraClearanceDistance")]
    [NativeMetadata("MPropertyAttributeChoiceName", "FloatParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Clearance Distance")]
    public AnimParamID ParameterCameraClearanceDistance { get; set; }

    /// <summary>
    ///     Camera Only Parameter.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterCameraOnly</c> at offset <c>0x7C</c>.
    /// </remarks>
    [NativeOffset(0x7C)]
    [NativeName("m_parameterCameraOnly")]
    [NativeMetadata("MPropertyAttributeChoiceName", "BoolParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Camera Only Parameter")]
    public AnimParamID ParameterCameraOnly { get; set; }

    /// <summary>
    ///     Orientation Parameter.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterNameOrientation</c> at offset <c>0x74</c>.
    /// </remarks>
    [NativeOffset(0x74)]
    [NativeName("m_parameterNameOrientation")]
    [NativeMetadata("MPropertyAttributeChoiceName", "QuaternionParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Orientation Parameter")]
    public AnimParamID ParameterNameOrientation { get; set; }

    /// <summary>
    ///     Pelvis Offset Parameter.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterNamePelvisOffset</c> at offset <c>0x78</c>.
    /// </remarks>
    [NativeOffset(0x78)]
    [NativeName("m_parameterNamePelvisOffset")]
    [NativeMetadata("MPropertyAttributeChoiceName", "FloatParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Pelvis Offset Parameter")]
    public AnimParamID ParameterNamePelvisOffset { get; set; }

    /// <summary>
    ///     Animgraph Position Parameter.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterNamePosition</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_parameterNamePosition")]
    [NativeMetadata("MPropertyAttributeChoiceName", "VectorParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Animgraph Position Parameter")]
    public AnimParamID ParameterNamePosition { get; set; }

    /// <summary>
    ///     Weapon De-Penetration Delta.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterWeaponDepenetrationDelta</c> at offset <c>0x88</c>.
    /// </remarks>
    [NativeOffset(0x88)]
    [NativeName("m_parameterWeaponDepenetrationDelta")]
    [NativeMetadata("MPropertyAttributeChoiceName", "VectorParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Weapon De-Penetration Delta")]
    public AnimParamID ParameterWeaponDepenetrationDelta { get; set; }

    /// <summary>
    ///     Weapon De-Penetration Distance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_parameterWeaponDepenetrationDistance</c> at offset <c>0x84</c>.
    /// </remarks>
    [NativeOffset(0x84)]
    [NativeName("m_parameterWeaponDepenetrationDistance")]
    [NativeMetadata("MPropertyAttributeChoiceName", "FloatParameter")]
    [NativeMetadata("MPropertyFriendlyName", "Weapon De-Penetration Distance")]
    public AnimParamID ParameterWeaponDepenetrationDistance { get; set; }

    /// <summary>
    ///     Pelvis Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pelvisJointName</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_pelvisJointName")]
    [NativeMetadata("MPropertyAttributeChoiceName", "Bone")]
    [NativeMetadata("MPropertyFriendlyName", "Pelvis Joint")]
    public string PelvisJointName { get; set; }

    /// <summary>
    ///     These joints will maintain their offset relative to the camera joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_propJoints</c> at offset <c>0x98</c>.
    /// </remarks>
    [NativeOffset(0x98)]
    [NativeName("m_propJoints")]
    [NativeMetadata("MPropertyDescription", "These joints will maintain their offset relative to the camera joint.")]
    [NativeMetadata("MPropertyFriendlyName", "Prop Joints")]
    public CUtlVector__CAnimGraphDoc_AimCameraNode_PropJoint__ PropJoints { get; set; }
}
