// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/FinishedConditionOption
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     FinishedConditionOption.
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 32-bit.
/// </remarks>
public enum FinishedConditionOption : uint
{
    /// <summary>
    ///     On Finished.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FinishedConditionOption_OnFinished</c>.
    /// </remarks>
    [NativeName("FinishedConditionOption_OnFinished")]
    [NativeMetadata("MPropertyFriendlyName", "On Finished")]
    OnFinished = 0,

    /// <summary>
    ///     On Almost Finished.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FinishedConditionOption_OnAlmostFinished</c>.
    /// </remarks>
    [NativeName("FinishedConditionOption_OnAlmostFinished")]
    [NativeMetadata("MPropertyFriendlyName", "On Almost Finished")]
    OnAlmostFinished = 1
}
