// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropChoice
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     Choice.
/// </summary>
/// <remarks>
///     Native name: <c>CSmartPropChoice</c>. Module: <c>smartprops</c> — 56 bytes.
/// </remarks>
[NativeSize(56)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CSmartPropChoice\",\n\t\"m_nElementID\": -1,\n\t\"m_Name\": \"\",\n\t\"m_DefaultOption\": \"\",\n\t\"m_Options\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyFriendlyName", "\"Choice\"")]
[NativeMetadata("MVDataAnonymousNode")]
[NativeMetadata("MVDataOutlinerNameExpr", "\"m_Name\"")]
public partial class CSmartPropChoice : CSmartPropParameter
{
    /// <summary>
    ///     Gets or sets DefaultOption.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_DefaultOption</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_DefaultOption")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"smartprop_choice_options\"")]
    public string DefaultOption { get; set; }

    /// <summary>
    ///     Choice Name.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Name</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_Name")]
    [NativeMetadata("MPropertyFriendlyName", "\"Choice Name\"")]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or sets Options.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Options</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_Options")]
    [NativeMetadata("MPropertyAutoExpandSelf")]
    public CSmartPropChoiceOption[] Options { get; set; }
}
