// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropFilterProbability
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     CSmartPropFilter_Probability
/// </summary>
/// <remarks>
///     Module: <c>smartprops</c> — 144 bytes, align 8.
/// </remarks>
[NativeSize(144)]
[NativeName("CSmartPropFilter_Probability")]
public partial class CSmartPropFilterProbability : CSmartPropFilter
{
    /// <summary>
    ///     Gets or sets Probability.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flProbability</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_flProbability")]
    [NativeMetadata("MPropertyDescription",
        "\"0.0 to 1.0 value indicating the probability of this element being evaluated. Where a value of 0 means the element will never be evaluated and 1.0 means it will always be evaluated\"")]
    public CSmartPropAttributeFloat Probability { get; set; }
}
