// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropOperationSaveState
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     CSmartPropOperation_SaveState
/// </summary>
/// <remarks>
///     Module: <c>smartprops</c> — 88 bytes, align 8.
/// </remarks>
[NativeSize(88)]
[NativeName("CSmartPropOperation_SaveState")]
public partial class CSmartPropOperationSaveState : CSmartPropOperation
{
    /// <summary>
    ///     Gets or sets StateName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_StateName</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_StateName")]
    [NativeMetadata("MPropertyAttributeEditor", "\"SmartPropItemNameEditor( SavedState )\"")]
    [NativeMetadata("MPropertyDescription",
        "\"Name to assign to the saved state, the save state can be restored later using this name.\"")]
    public string StateName { get; set; }
}
