// <auto-generated/>
// CS2OpenSchema — Smartprops/CSmartPropFilterSurfaceProperties
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     CSmartPropFilter_SurfaceProperties
/// </summary>
/// <remarks>
///     Module: <c>smartprops</c> — 128 bytes, align 8.
/// </remarks>
[NativeSize(128)]
[NativeName("CSmartPropFilter_SurfaceProperties")]
public partial class CSmartPropFilterSurfaceProperties : CSmartPropFilter
{
    /// <summary>
    ///     Gets or sets AllowedSurfaceProperties.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_AllowedSurfaceProperties</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_AllowedSurfaceProperties")]
    [NativeMetadata("MPropertyDescription",
        "\"List of surface properties on which this element is valid. If empty element is not restricted to any specific surfaces.\"")]
    public string[] AllowedSurfaceProperties { get; set; }

    /// <summary>
    ///     Gets or sets DisallowedSurfaceProperties.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_DisallowedSurfaceProperties</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_DisallowedSurfaceProperties")]
    [NativeMetadata("MPropertyDescription",
        "\"List of surface properties on which this element is not valid. If empty element is not restricted to any specific surfaces.\"")]
    public string[] DisallowedSurfaceProperties { get; set; }
}
