// <auto-generated/>
// CS2OpenSchema — Smartprops/SmartPropGridOriginBasis
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Smartprops;

/// <summary>
///     SmartPropGridOriginBasis_t
/// </summary>
/// <remarks>
///     Module: <c>smartprops</c> — 32-bit — flags.
/// </remarks>
[Flags]
[NativeName("SmartPropGridOriginBasis_t")]
public enum SmartPropGridOriginBasis : uint
{
    /// <summary>
    ///     Center
    /// </summary>
    /// <remarks>
    ///     Native name: <c>CENTER</c>
    /// </remarks>
    [NativeName("CENTER")]
    [NativeMetadata("MPropertyFriendlyName", "\"Center\"")]
    [NativeMetadata("MPropertyDescription", "\"Lay out child elements with their origin at the center of each grid cell.\"")]
    Center = 0,

    /// <summary>
    ///     Corner
    /// </summary>
    /// <remarks>
    ///     Native name: <c>CORNER</c>
    /// </remarks>
    [NativeName("CORNER")]
    [NativeMetadata("MPropertyFriendlyName", "\"Corner\"")]
    [NativeMetadata("MPropertyDescription", "\"Lay out child elements with their origin at the corner of each grid cell.\"")]
    Corner = 1
}
