// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocStateTransition
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Modellib;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     CAnimGraphDoc_StateTransition
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 112 bytes, align 8.
/// </remarks>
[NativeSize(112)]
[NativeName("CAnimGraphDoc_StateTransition")]
public partial class CAnimGraphDocStateTransition
{
    /// <summary>
    ///     Gets or sets ConditionList.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_conditionList</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_conditionList")]
    [NativeMetadata("MPropertySuppressField")]
    public CAnimGraphDocConditionContainer ConditionList { get; set; }

    /// <summary>
    ///     Gets or sets DestState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_destState</c> at offset <c>0x5C</c>.
    /// </remarks>
    [NativeOffset(0x5C)]
    [NativeName("m_destState")]
    [NativeMetadata("MPropertySuppressField")]
    public AnimStateID DestState { get; set; }

    /// <summary>
    ///     Gets or sets Disabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bDisabled</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_bDisabled")]
    [NativeMetadata("MPropertyFriendlyName", "\"Disable\"")]
    public bool Disabled { get; set; }

    /// <summary>
    ///     Gets or sets SComment.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sComment</c> at offset <c>0x60</c>.
    /// </remarks>
    [NativeOffset(0x60)]
    [NativeName("m_sComment")]
    [NativeMetadata("MPropertyFriendlyName", "\"Comment\"")]
    [NativeMetadata("MPropertyAttributeEditor", "\"TextBlock()\"")]
    [NativeMetadata("MPropertySortPriority", "-100")]
    public string SComment { get; set; }

    /// <summary>
    ///     Gets or sets SrcState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_srcState</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_srcState")]
    [NativeMetadata("MPropertySuppressField")]
    public AnimStateID SrcState { get; set; }
}
