// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocBlendNode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animgraphlib;
using CS2OpenSchema.Modellib;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     CAnimGraphDoc_BlendNode
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 168 bytes, align 8.
/// </remarks>
[NativeSize(168)]
[NativeName("CAnimGraphDoc_BlendNode")]
public partial class CAnimGraphDocBlendNode : CAnimGraphDocNode
{
    /// <summary>
    ///     Gets or sets BlendKeyType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_blendKeyType</c> at offset <c>0x7C</c>.
    /// </remarks>
    [NativeOffset(0x7C)]
    [NativeName("m_blendKeyType")]
    [NativeMetadata("MPropertyFriendlyName", "\"Blend Key Values\"")]
    public BlendKeyType BlendKeyType { get; set; }

    /// <summary>
    ///     Gets or sets BlendValueSource.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_blendValueSource</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_blendValueSource")]
    [NativeMetadata("MPropertyFriendlyName", "\"Blend Source\"")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public AnimValueSource BlendValueSource { get; set; }

    /// <summary>
    ///     Gets or sets Children.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_children</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_children")]
    [NativeMetadata("MPropertyFriendlyName", "\"Blend Items\"")]
    [NativeMetadata("MPropertyAutoExpandSelf")]
    public CBlendNodeChild[] Children { get; set; }

    /// <summary>
    ///     Gets or sets Damping.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_damping</c> at offset <c>0x88</c>.
    /// </remarks>
    [NativeOffset(0x88)]
    [NativeName("m_damping")]
    [NativeMetadata("MPropertyFriendlyName", "\"Damping\"")]
    public CAnimInputDamping Damping { get; set; }

    /// <summary>
    ///     Gets or sets IsAngle.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsAngle</c> at offset <c>0x84</c>.
    /// </remarks>
    [NativeOffset(0x84)]
    [NativeName("m_bIsAngle")]
    [NativeMetadata("MPropertyFriendlyName", "\"Is Angle\"")]
    public bool IsAngle { get; set; }

    /// <summary>
    ///     Gets or sets LinearRootMotionBlendMode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eLinearRootMotionBlendMode</c> at offset <c>0xA0</c>.
    /// </remarks>
    [NativeOffset(0xA0)]
    [NativeName("m_eLinearRootMotionBlendMode")]
    [NativeMetadata("MPropertyFriendlyName", "\"Linear Root Motion Blend Mode\"")]
    public LinearRootMotionBlendMode LinearRootMotionBlendMode { get; set; }

    /// <summary>
    ///     Gets or sets LockBlendOnReset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLockBlendOnReset</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_bLockBlendOnReset")]
    [NativeMetadata("MPropertyFriendlyName", "\"Lock Blend on Reset\"")]
    public bool LockBlendOnReset { get; set; }

    /// <summary>
    ///     Gets or sets LockWhenWaning.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLockWhenWaning</c> at offset <c>0x83</c>.
    /// </remarks>
    [NativeOffset(0x83)]
    [NativeName("m_bLockWhenWaning")]
    [NativeMetadata("MPropertyFriendlyName", "\"Lock Blend When Waning\"")]
    public bool LockWhenWaning { get; set; }

    /// <summary>
    ///     Gets or sets Loop.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLoop</c> at offset <c>0x82</c>.
    /// </remarks>
    [NativeOffset(0x82)]
    [NativeName("m_bLoop")]
    [NativeMetadata("MPropertyFriendlyName", "\"Loop\"")]
    public bool Loop { get; set; }

    /// <summary>
    ///     Gets or sets Param.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_param</c> at offset <c>0x78</c>.
    /// </remarks>
    [NativeOffset(0x78)]
    [NativeName("m_param")]
    [NativeMetadata("MPropertyFriendlyName", "\"Parameter\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"FloatParameter\"")]
    public AnimParamID Param { get; set; }

    /// <summary>
    ///     Gets or sets ParamName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_paramName</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_paramName")]
    [NativeMetadata("MPropertySuppressField")]
    public string ParamName { get; set; }

    /// <summary>
    ///     Gets or sets SyncCycles.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bSyncCycles</c> at offset <c>0x81</c>.
    /// </remarks>
    [NativeOffset(0x81)]
    [NativeName("m_bSyncCycles")]
    [NativeMetadata("MPropertyFriendlyName", "\"Sync Cycles\"")]
    public bool SyncCycles { get; set; }
}
