// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocDirectPlaybackNode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     CAnimGraphDoc_DirectPlaybackNode
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 80 bytes, align 8.
/// </remarks>
[NativeSize(80)]
[NativeName("CAnimGraphDoc_DirectPlaybackNode")]
public partial class CAnimGraphDocDirectPlaybackNode : CAnimGraphDocNode
{
    /// <summary>
    ///     Gets or sets FinishEarly.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bFinishEarly</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_bFinishEarly")]
    [NativeMetadata("MPropertyFriendlyName", "\"Finish Early\"")]
    public bool FinishEarly { get; set; }

    /// <summary>
    ///     Gets or sets InputConnection.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_inputConnection</c> at offset <c>0x40</c>.
    /// </remarks>
    [NativeOffset(0x40)]
    [NativeName("m_inputConnection")]
    [NativeMetadata("MPropertySuppressField")]
    public CAnimGraphDocNodeConnection InputConnection { get; set; }

    /// <summary>
    ///     Gets or sets ResetOnFinish.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bResetOnFinish</c> at offset <c>0x49</c>.
    /// </remarks>
    [NativeOffset(0x49)]
    [NativeName("m_bResetOnFinish")]
    [NativeMetadata("MPropertyFriendlyName", "\"Reset Child On Finish\"")]
    public bool ResetOnFinish { get; set; }
}
