// <auto-generated/>
// CS2OpenSchema — Animgraphdoclib/CAnimGraphDocSelectorNode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animgraphlib;
using CS2OpenSchema.Modellib;

#endregion

namespace CS2OpenSchema.Animgraphdoclib;

/// <summary>
///     CAnimGraphDoc_SelectorNode
/// </summary>
/// <remarks>
///     Module: <c>animgraphdoclib</c> — 208 bytes, align 8.
/// </remarks>
[NativeSize(208)]
[NativeName("CAnimGraphDoc_SelectorNode")]
public partial class CAnimGraphDocSelectorNode : CAnimGraphDocNode
{
    /// <summary>
    ///     Gets or sets BlendCurve.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_blendCurve</c> at offset <c>0xC8</c>.
    /// </remarks>
    [NativeOffset(0xC8)]
    [NativeName("m_blendCurve")]
    [NativeMetadata("MPropertySuppressField")]
    public CBlendCurve BlendCurve { get; set; }

    /// <summary>
    ///     Gets or sets BlendDuration.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_blendDuration</c> at offset <c>0xA0</c>.
    /// </remarks>
    [NativeOffset(0xA0)]
    [NativeName("m_blendDuration")]
    [NativeMetadata("MPropertyFriendlyName", "\"Blend Duration\"")]
    public CFloatAnimValue BlendDuration { get; set; }

    /// <summary>
    ///     Gets or sets BoolParamID.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_boolParamID</c> at offset <c>0x88</c>.
    /// </remarks>
    [NativeOffset(0x88)]
    [NativeName("m_boolParamID")]
    [NativeMetadata("MPropertyFriendlyName", "\"Bool Parameter\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"BoolParameter\"")]
    [NativeMetadata("MPropertyAutoRebuildOnChange")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public AnimParamID BoolParamID { get; set; }

    /// <summary>
    ///     Gets or sets BoolParamName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_boolParamName</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_boolParamName")]
    [NativeMetadata("MPropertySuppressField")]
    public string BoolParamName { get; set; }

    /// <summary>
    ///     Gets or sets Children.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_children</c> at offset <c>0x40</c>.
    /// </remarks>
    [NativeOffset(0x40)]
    [NativeName("m_children")]
    [NativeMetadata("MPropertySuppressField")]
    public CAnimGraphDocNodeConnection[] Children { get; set; }

    /// <summary>
    ///     Gets or sets EnumParamID.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_enumParamID</c> at offset <c>0x98</c>.
    /// </remarks>
    [NativeOffset(0x98)]
    [NativeName("m_enumParamID")]
    [NativeMetadata("MPropertyFriendlyName", "\"Enum Parameter\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"EnumParameter\"")]
    [NativeMetadata("MPropertyAutoRebuildOnChange")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public AnimParamID EnumParamID { get; set; }

    /// <summary>
    ///     Gets or sets EnumParamName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_enumParamName</c> at offset <c>0x90</c>.
    /// </remarks>
    [NativeOffset(0x90)]
    [NativeName("m_enumParamName")]
    [NativeMetadata("MPropertySuppressField")]
    public string EnumParamName { get; set; }

    /// <summary>
    ///     Gets or sets FallbackChild.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fallbackChild</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_fallbackChild")]
    [NativeMetadata("MPropertySuppressField")]
    public CAnimGraphDocNodeConnection FallbackChild { get; set; }

    /// <summary>
    ///     Gets or sets LockWhenWaning.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLockWhenWaning</c> at offset <c>0xC6</c>.
    /// </remarks>
    [NativeOffset(0xC6)]
    [NativeName("m_bLockWhenWaning")]
    [NativeMetadata("MPropertyFriendlyName", "\"Lock Selection When Waning\"")]
    public bool LockWhenWaning { get; set; }

    /// <summary>
    ///     Gets or sets ResetOnChange.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bResetOnChange</c> at offset <c>0xC4</c>.
    /// </remarks>
    [NativeOffset(0xC4)]
    [NativeName("m_bResetOnChange")]
    [NativeMetadata("MPropertyFriendlyName", "\"Reset On Change\"")]
    public bool ResetOnChange { get; set; }

    /// <summary>
    ///     Gets or sets SelectionSource.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_selectionSource</c> at offset <c>0x78</c>.
    /// </remarks>
    [NativeOffset(0x78)]
    [NativeName("m_selectionSource")]
    [NativeMetadata("MPropertyFriendlyName", "\"Selection Source\"")]
    [NativeMetadata("MPropertyAutoRebuildOnChange")]
    public SelectionSource SelectionSource { get; set; }

    /// <summary>
    ///     Gets or sets SyncCyclesOnChange.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bSyncCyclesOnChange</c> at offset <c>0xC5</c>.
    /// </remarks>
    [NativeOffset(0xC5)]
    [NativeName("m_bSyncCyclesOnChange")]
    [NativeMetadata("MPropertyFriendlyName", "\"Start new option at same cycle\"")]
    public bool SyncCyclesOnChange { get; set; }

    /// <summary>
    ///     Gets or sets TagBehavior.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_tagBehavior</c> at offset <c>0xC0</c>.
    /// </remarks>
    [NativeOffset(0xC0)]
    [NativeName("m_tagBehavior")]
    [NativeMetadata("MPropertyFriendlyName", "\"Tag Behavior\"")]
    public SelectorTagBehavior TagBehavior { get; set; }

    /// <summary>
    ///     Gets or sets TagID.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_tagID</c> at offset <c>0x9C</c>.
    /// </remarks>
    [NativeOffset(0x9C)]
    [NativeName("m_tagID")]
    [NativeMetadata("MPropertyFriendlyName", "\"Tag Parameter\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"Tag\"")]
    [NativeMetadata("MPropertyAutoRebuildOnChange")]
    [NativeMetadata("MPropertyAttrStateCallback")]
    public AnimTagID TagID { get; set; }

    /// <summary>
    ///     Gets or sets Tags.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_tags</c> at offset <c>0x60</c>.
    /// </remarks>
    [NativeOffset(0x60)]
    [NativeName("m_tags")]
    [NativeMetadata("MPropertySuppressField")]
    public AnimTagID[] Tags { get; set; }
}
