// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CCachedPose
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animationsystem;

#endregion

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CCachedPose
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 64 bytes, align 8.
/// </remarks>
[NativeSize(64)]
public partial class CCachedPose
{
    /// <summary>
    ///     Gets or sets Cycle.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flCycle</c> at offset <c>0x3C</c>.
    /// </remarks>
    [NativeOffset(0x3C)]
    [NativeName("m_flCycle")]
    public float Cycle { get; set; }

    /// <summary>
    ///     Gets or sets MorphWeights.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_morphWeights</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_morphWeights")]
    public float[] MorphWeights { get; set; }

    /// <summary>
    ///     Gets or sets Sequence.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hSequence</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_hSequence")]
    public HSequence Sequence { get; set; }

    /// <summary>
    ///     Gets or sets Transforms.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_transforms</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_transforms")]
    public CTransform[] Transforms { get; set; }
}
