// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CFutureVelocityMetricEvaluator
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CFutureVelocityMetricEvaluator
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 96 bytes, align 8.
/// </remarks>
[NativeSize(96)]
public partial class CFutureVelocityMetricEvaluator : CMotionMetricEvaluator
{
    /// <summary>
    ///     Gets or sets Distance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flDistance</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_flDistance")]
    public float Distance { get; set; }

    /// <summary>
    ///     Gets or sets Mode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_eMode</c> at offset <c>0x5C</c>.
    /// </remarks>
    [NativeOffset(0x5C)]
    [NativeName("m_eMode")]
    public VelocityMetricMode Mode { get; set; }

    /// <summary>
    ///     Gets or sets StoppingDistance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flStoppingDistance</c> at offset <c>0x54</c>.
    /// </remarks>
    [NativeOffset(0x54)]
    [NativeName("m_flStoppingDistance")]
    public float StoppingDistance { get; set; }

    /// <summary>
    ///     Gets or sets TargetSpeed.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flTargetSpeed</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_flTargetSpeed")]
    public float TargetSpeed { get; set; }
}
