// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CFutureFacingMetricEvaluator
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CFutureFacingMetricEvaluator
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 88 bytes, align 8.
/// </remarks>
[NativeSize(88)]
public partial class CFutureFacingMetricEvaluator : CMotionMetricEvaluator
{
    /// <summary>
    ///     Gets or sets Distance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flDistance</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_flDistance")]
    public float Distance { get; set; }

    /// <summary>
    ///     Gets or sets Time.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flTime</c> at offset <c>0x54</c>.
    /// </remarks>
    [NativeOffset(0x54)]
    [NativeName("m_flTime")]
    public float Time { get; set; }
}
