// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CLODComponentUpdater
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CLODComponentUpdater
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 56 bytes, align 8.
/// </remarks>
[NativeSize(56)]
public partial class CLODComponentUpdater : CAnimComponentUpdater
{
    /// <summary>
    ///     Gets or sets ServerLOD.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nServerLOD</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_nServerLOD")]
    public int ServerLOD { get; set; }
}
