// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CMotionSearchDB
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CMotionSearchDB
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 184 bytes, align 8.
/// </remarks>
[NativeSize(184)]
public partial class CMotionSearchDB
{
    /// <summary>
    ///     Gets or sets CodeIndices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_codeIndices</c> at offset <c>0xA0</c>.
    /// </remarks>
    [NativeOffset(0xA0)]
    [NativeName("m_codeIndices")]
    public MotionDBIndex[] CodeIndices { get; set; }

    /// <summary>
    ///     Gets or sets ResidualQuantizer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_residualQuantizer</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_residualQuantizer")]
    public CProductQuantizer ResidualQuantizer { get; set; }

    /// <summary>
    ///     Gets or sets RootNode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_rootNode</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_rootNode")]
    public CMotionSearchNode RootNode { get; set; }
}
