// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CMotionSearchNode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CMotionSearchNode
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 128 bytes, align 8.
/// </remarks>
[NativeSize(128)]
public partial class CMotionSearchNode
{
    /// <summary>
    ///     Gets or sets Children.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_children</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_children")]
    public CMotionSearchNode?[] Children { get; set; }

    /// <summary>
    ///     Gets or sets Quantizer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_quantizer</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_quantizer")]
    public CVectorQuantizer Quantizer { get; set; }

    /// <summary>
    ///     Gets or sets SampleCodes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sampleCodes</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_sampleCodes")]
    public SampleCode[][] SampleCodes { get; set; }

    /// <summary>
    ///     Gets or sets SampleIndices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sampleIndices</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_sampleIndices")]
    public int[][] SampleIndices { get; set; }

    /// <summary>
    ///     Gets or sets SelectableSamples.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_selectableSamples</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_selectableSamples")]
    public int[] SelectableSamples { get; set; }
}
