// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CPathAnimMotorUpdaterBase
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CPathAnimMotorUpdaterBase.
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 40 bytes.
/// </remarks>
[NativeSize(40)]
[NativeMetadata("MGetKV3ClassDefaults", "Could not parse KV3 Defaults")]
public partial class CPathAnimMotorUpdaterBase : CAnimMotorUpdaterBase
{
    /// <summary>
    ///     Gets or sets LockToPath.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLockToPath</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_bLockToPath")]
    public bool LockToPath { get; set; }
}
