// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CTimeRemainingMetricEvaluator
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CTimeRemainingMetricEvaluator.
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 96 bytes.
/// </remarks>
[NativeSize(96)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CTimeRemainingMetricEvaluator\",\n\t\"m_means\":\n\t[\n\t],\n\t\"m_standardDeviations\":\n\t[\n\t],\n\t\"m_flWeight\": 0.000000,\n\t\"m_nDimensionStartIndex\": -1,\n\t\"m_bMatchByTimeRemaining\": false,\n\t\"m_flMaxTimeRemaining\": 0.000000,\n\t\"m_bFilterByTimeRemaining\": false,\n\t\"m_flMinTimeRemaining\": 0.000000\n}")]
public partial class CTimeRemainingMetricEvaluator : CMotionMetricEvaluator
{
    /// <summary>
    ///     Gets or sets FilterByTimeRemaining.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bFilterByTimeRemaining</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_bFilterByTimeRemaining")]
    public bool FilterByTimeRemaining { get; set; }

    /// <summary>
    ///     Gets or sets MatchByTimeRemaining.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bMatchByTimeRemaining</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_bMatchByTimeRemaining")]
    public bool MatchByTimeRemaining { get; set; }

    /// <summary>
    ///     Gets or sets MaxTimeRemaining.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flMaxTimeRemaining</c> at offset <c>0x54</c>.
    /// </remarks>
    [NativeOffset(0x54)]
    [NativeName("m_flMaxTimeRemaining")]
    public float MaxTimeRemaining { get; set; }

    /// <summary>
    ///     Gets or sets MinTimeRemaining.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flMinTimeRemaining</c> at offset <c>0x5C</c>.
    /// </remarks>
    [NativeOffset(0x5C)]
    [NativeName("m_flMinTimeRemaining")]
    public float MinTimeRemaining { get; set; }
}
