// <auto-generated/>
// CS2OpenSchema — Animgraphlib/CVectorQuantizer
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     CVectorQuantizer
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 32 bytes, align 8.
/// </remarks>
[NativeSize(32)]
public partial class CVectorQuantizer
{
    /// <summary>
    ///     Gets or sets CentroidVectors.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_centroidVectors</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_centroidVectors")]
    public float[] CentroidVectors { get; set; }

    /// <summary>
    ///     Gets or sets Centroids.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nCentroids</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_nCentroids")]
    public int Centroids { get; set; }

    /// <summary>
    ///     Gets or sets Dimensions.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nDimensions</c> at offset <c>0x1C</c>.
    /// </remarks>
    [NativeOffset(0x1C)]
    [NativeName("m_nDimensions")]
    public int Dimensions { get; set; }
}
