// <auto-generated/>
// CS2OpenSchema — Animgraphlib/DampedPathMotorInstanceData
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     DampedPathMotorInstanceData_t
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 40 bytes, align 4.
/// </remarks>
[NativeSize(40)]
[NativeName("DampedPathMotorInstanceData_t")]
public partial class DampedPathMotorInstanceData
{
    /// <summary>
    ///     Gets or sets Acceleration.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vAcceleration</c> at offset <c>0xC</c>.
    /// </remarks>
    [NativeOffset(0xC)]
    [NativeName("m_vAcceleration")]
    public Vector Acceleration { get; set; }

    /// <summary>
    ///     Gets or sets Stopping.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bStopping</c> at offset <c>0x24</c>.
    /// </remarks>
    [NativeOffset(0x24)]
    [NativeName("m_bStopping")]
    public bool Stopping { get; set; }

    /// <summary>
    ///     Gets or sets Velocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vVelocity</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_vVelocity")]
    public Vector Velocity { get; set; }
}
