// <auto-generated/>
// CS2OpenSchema — Animgraphlib/FootPinningTimingSource
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     FootPinningTimingSource
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 32-bit — flags.
/// </remarks>
[Flags]
public enum FootPinningTimingSource : uint
{
    /// <summary>
    ///     FootMotion
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FootMotion</c>
    /// </remarks>
    [NativeName("FootMotion")]
    FootMotion = 0,

    /// <summary>
    ///     Tag
    /// </summary>
    /// <remarks>
    ///     Native name: <c>Tag</c>
    /// </remarks>
    [NativeName("Tag")]
    Tag = 1,

    /// <summary>
    ///     Parameter
    /// </summary>
    /// <remarks>
    ///     Native name: <c>Parameter</c>
    /// </remarks>
    [NativeName("Parameter")]
    Parameter = 2
}
