// <auto-generated/>
// CS2OpenSchema — Animgraphlib/IKTargetSource
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animgraphlib;

/// <summary>
///     IKTargetSource
/// </summary>
/// <remarks>
///     Module: <c>animgraphlib</c> — 32-bit — flags.
/// </remarks>
[Flags]
public enum IKTargetSource : uint
{
    /// <summary>
    ///     Bone
    /// </summary>
    /// <remarks>
    ///     Native name: <c>IKTARGETSOURCE_Bone</c>
    /// </remarks>
    [NativeName("IKTARGETSOURCE_Bone")]
    [NativeMetadata("MPropertyFriendlyName", "\"Bone\"")]
    Bone = 0,

    /// <summary>
    ///     AnimgraphParameter
    /// </summary>
    /// <remarks>
    ///     Native name: <c>IKTARGETSOURCE_AnimgraphParameter</c>
    /// </remarks>
    [NativeName("IKTARGETSOURCE_AnimgraphParameter")]
    [NativeMetadata("MPropertyFriendlyName", "\"Animgraph Parameter\"")]
    AnimgraphParameter = 1,

    /// <summary>
    ///     Count
    /// </summary>
    /// <remarks>
    ///     Native name: <c>IKTARGETSOURCE_COUNT</c>
    /// </remarks>
    [NativeName("IKTARGETSOURCE_COUNT")]
    [NativeMetadata("MPropertySuppressEnumerator")]
    Count = 2
}
