// <auto-generated/>
// CS2OpenSchema — Particleslib/ParticleNamedValueConfiguration
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animationsystem;

#endregion

namespace CS2OpenSchema.Particleslib;

/// <summary>
///     ParticleNamedValueConfiguration_t
/// </summary>
/// <remarks>
///     Module: <c>particleslib</c> — 56 bytes, align 8.
/// </remarks>
[NativeSize(56)]
[NativeName("ParticleNamedValueConfiguration_t")]
public partial class ParticleNamedValueConfiguration
{
    /// <summary>
    ///     Gets or sets AttachType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iAttachType</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_iAttachType")]
    public ParticleAttachment AttachType { get; set; }

    /// <summary>
    ///     Gets or sets AttachmentName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_strAttachmentName</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_strAttachmentName")]
    public string AttachmentName { get; set; }

    /// <summary>
    ///     Gets or sets BoundValuePath.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_BoundValuePath</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_BoundValuePath")]
    public string BoundValuePath { get; set; }

    /// <summary>
    ///     Gets or sets ConfigName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ConfigName</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_ConfigName")]
    public string ConfigName { get; set; }

    /// <summary>
    ///     Gets or sets ConfigValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ConfigValue</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_ConfigValue")]
    public KeyValues3 ConfigValue { get; set; }

    /// <summary>
    ///     Gets or sets EntityScope.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_strEntityScope</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_strEntityScope")]
    public string EntityScope { get; set; }
}
