// <auto-generated/>
// CS2OpenSchema — SoundsystemLowlevel/CVMixBaseProcessorDesc
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.SoundsystemLowlevel;

/// <summary>
///     CVMixBaseProcessorDesc
/// </summary>
/// <remarks>
///     Module: <c>soundsystem_lowlevel</c> — 32 bytes — abstract.
/// </remarks>
[NativeSize(32)]
public abstract partial class CVMixBaseProcessorDesc
{
    /// <summary>
    ///     Gets or sets Channels.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nChannels</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_nChannels")]
    public int Channels { get; set; }

    /// <summary>
    ///     Gets or sets Flxfade.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flxfade</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_flxfade")]
    public float Flxfade { get; set; }

    /// <summary>
    ///     Gets or sets Name.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_name</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_name")]
    public string Name { get; set; }
}
