// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmClipDocEventFrameSnap
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animlib;

#endregion

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmClipDocEvent_FrameSnap.
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 24 bytes, align 8.
/// </remarks>
[NativeSize(24)]
[NativeName("CNmClipDocEvent_FrameSnap")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CNmClipDocEvent_FrameSnap\",\n\t\"m_flStartTime\": 0.000000,\n\t\"m_flDuration\": 0.000000,\n\t\"m_frameSnapMode\": \"Round\"\n}")]
public partial class CNmClipDocEventFrameSnap : CNmClipDocEvent
{
    /// <summary>
    ///     Gets or sets FrameSnapMode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_frameSnapMode</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_frameSnapMode")]
    public NmFrameSnapEventMode FrameSnapMode { get; set; }
}
