// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmClipDocumentAdditiveBaseFrame
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmClipDocument::AdditiveBaseFrame_t.
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 8-bit.
/// </remarks>
[NativeName("CNmClipDocument::AdditiveBaseFrame_t")]
public enum CNmClipDocumentAdditiveBaseFrame : byte
{
    /// <summary>
    ///     FirstFrame.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FirstFrame</c>.
    /// </remarks>
    [NativeName("FirstFrame")]
    FirstFrame = 0,

    /// <summary>
    ///     LastFrame.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>LastFrame</c>.
    /// </remarks>
    [NativeName("LastFrame")]
    LastFrame = 1,

    /// <summary>
    ///     UserSpecifiedFrame.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>UserSpecifiedFrame</c>.
    /// </remarks>
    [NativeName("UserSpecifiedFrame")]
    UserSpecifiedFrame = 2
}
