// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmGraphDocDataDictionaryIDSet
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmGraphDocDataDictionary::IDSet_t.
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 48 bytes, align 8.
/// </remarks>
[NativeSize(48)]
[NativeName("CNmGraphDocDataDictionary::IDSet_t")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\"m_name\": \"\",\n\t\"m_graphIDs\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyAutoExpandSelf", "")]
public partial class CNmGraphDocDataDictionaryIDSet
{
    /// <summary>
    ///     Graph IDs.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_graphIDs</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_graphIDs")]
    [NativeMetadata("MPropertyAutoExpandSelf", "")]
    [NativeMetadata("MPropertyFriendlyName", "Graph IDs")]
    public CUtlVector__CGlobalSymbol__ GraphIDs { get; set; }

    /// <summary>
    ///     Gets or sets ID.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ID</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_ID")]
    [NativeMetadata("MPropertySuppressField", "")]
    public Guid ID { get; set; }

    /// <summary>
    ///     Gets or sets Name.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_name</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_name")]
    [NativeMetadata("MPropertyFlattenIntoParentRow", "")]
    public string Name { get; set; }
}
