// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmGraphDocStateNodeStateEvent
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmGraphDocStateNode::StateEvent_t.
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 16 bytes.
/// </remarks>
[NativeSize(16)]
[NativeName("CNmGraphDocStateNode::StateEvent_t")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\"m_bIsEntry\": true,\n\t\"m_bIsFullyInState\": true,\n\t\"m_bIsExit\": true\n}")]
[NativeMetadata("MPropertyAutoExpandSelf")]
public partial class CNmGraphDocStateNodeStateEvent
{
    /// <summary>
    ///     Gets or sets ID.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ID</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_ID")]
    [NativeMetadata("MPropertyAttributeEditor", "\"AnimGraphID()\"")]
    public string ID { get; set; }

    /// <summary>
    ///     Gets or sets IsEntry.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsEntry</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_bIsEntry")]
    public bool IsEntry { get; set; }

    /// <summary>
    ///     Gets or sets IsExit.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsExit</c> at offset <c>0xA</c>.
    /// </remarks>
    [NativeOffset(0xA)]
    [NativeName("m_bIsExit")]
    public bool IsExit { get; set; }

    /// <summary>
    ///     Gets or sets IsFullyInState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsFullyInState</c> at offset <c>0x9</c>.
    /// </remarks>
    [NativeOffset(0x9)]
    [NativeName("m_bIsFullyInState")]
    public bool IsFullyInState { get; set; }
}
