// <auto-generated/>
// CS2OpenSchema — Animdoclib/CNmGraphDocOrientationWarpNode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Animlib;

#endregion

namespace CS2OpenSchema.Animdoclib;

/// <summary>
///     CNmGraphDocOrientationWarpNode.
/// </summary>
/// <remarks>
///     Module: <c>animdoclib</c> — 264 bytes, align 8.
/// </remarks>
[NativeSize(264)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CNmGraphDocOrientationWarpNode\",\n\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\"m_name\": \"\",\n\t\"m_floatingComment\": \"\",\n\t\"m_position\":\n\t[\n\t\t0.000000,\n\t\t0.000000\n\t],\n\t\"m_pChildGraph\": null,\n\t\"m_pSecondaryGraph\": null,\n\t\"m_inputPins\":\n\t[\n\t\t{\n\t\t\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\t\t\"m_name\": \"Input\",\n\t\t\t\"m_type\": \"Pose\",\n\t\t\t\"m_bIsDynamicPin\": false,\n\t\t\t\"m_bAllowMultipleOutConnections\": false\n\t\t},\n\t\t{\n\t\t\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\t\t\"m_name\": \"Direction (Character)\",\n\t\t\t\"m_type\": \"Vector\",\n\t\t\t\"m_bIsDynamicPin\": false,\n\t\t\t\"m_bAllowMultipleOutConnections\": false\n\t\t},\n\t\t{\n\t\t\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\t\t\"m_name\": \"Angle Offset (Deg)\",\n\t\t\t\"m_type\": \"Float\",\n\t\t\t\"m_bIsDynamicPin\": false,\n\t\t\t\"m_bAllowMultipleOutConnections\": false\n\t\t}\n\t],\n\t\"m_outputPins\":\n\t[\n\t\t{\n\t\t\t\"m_ID\": <HIDDEN FOR DIFF>,\n\t\t\t\"m_name\": \"Result\",\n\t\t\t\"m_type\": \"Pose\",\n\t\t\t\"m_bIsDynamicPin\": false,\n\t\t\t\"m_bAllowMultipleOutConnections\": false\n\t\t}\n\t],\n\t\"m_offsetType\": \"RelativeToCharacter\",\n\t\"m_samplingMode\": \"WorldSpace\",\n\t\"m_bWarpTranslation\": false\n}")]
public partial class CNmGraphDocOrientationWarpNode : CNmGraphDocFlowNode
{
    /// <summary>
    ///     Gets or sets OffsetType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_offsetType</c> at offset <c>0x100</c>.
    /// </remarks>
    [NativeOffset(0x100)]
    [NativeName("m_offsetType")]
    public CNmGraphDocOrientationWarpNodeOffsetType OffsetType { get; set; }

    /// <summary>
    ///     Gets or sets SamplingMode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_samplingMode</c> at offset <c>0x104</c>.
    /// </remarks>
    [NativeOffset(0x104)]
    [NativeName("m_samplingMode")]
    public CNmRootMotionDataSamplingMode SamplingMode { get; set; }

    /// <summary>
    ///     Should the translation curve change as the orientation is being warped?
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bWarpTranslation</c> at offset <c>0x105</c>.
    /// </remarks>
    [NativeOffset(0x105)]
    [NativeName("m_bWarpTranslation")]
    [NativeMetadata("MPropertyDescription", "Should the translation curve change as the orientation is being warped?")]
    [NativeMetadata("MPropertyGroupName", "Experimental")]
    public bool WarpTranslation { get; set; }
}
