// <auto-generated/>
// CS2OpenSchema — Common/CCSGOTeamPreviewCharacterPositionAPI
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Common;

/// <summary>
///     CCSGO_TeamPreviewCharacterPosition_API.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 8 bytes.
/// </remarks>
[NativeSize(8)]
[NativeName("CCSGO_TeamPreviewCharacterPosition_API")]
public partial class CCSGOTeamPreviewCharacterPositionAPI
{
}
