// <auto-generated/>
// CS2OpenSchema — SoundsystemVoicecontainers/CVoiceContainerEnvelopeAnalyzer
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.SoundsystemVoicecontainers;

/// <summary>
///     Generates an Envelope Curve on compile.
/// </summary>
/// <remarks>
///     Native name: <c>CVoiceContainerEnvelopeAnalyzer</c>. Module: <c>soundsystem_voicecontainers</c> — 88 bytes, align 8.
/// </remarks>
[NativeSize(88)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CVoiceContainerEnvelopeAnalyzer\",\n\t\"m_curve\":\n\t{\n\t\t\"m_spline\":\n\t\t[\n\t\t],\n\t\t\"m_tangents\":\n\t\t[\n\t\t],\n\t\t\"m_vDomainMins\":\n\t\t[\n\t\t\t0.000000,\n\t\t\t0.000000\n\t\t],\n\t\t\"m_vDomainMaxs\":\n\t\t[\n\t\t\t0.000000,\n\t\t\t0.000000\n\t\t]\n\t},\n\t\"m_mode\": \"Peak\",\n\t\"m_fAnalysisWindowMs\": 200.000000,\n\t\"m_flThreshold\": 0.000000\n}")]
[NativeMetadata("MPropertyDescription", "Generates an Envelope Curve on compile")]
[NativeMetadata("MPropertyFriendlyName", "Envelope Analyzer")]
public partial class CVoiceContainerEnvelopeAnalyzer : CVoiceContainerAnalysisBase
{
    /// <summary>
    ///     Analysis Window.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fAnalysisWindowMs</c> at offset <c>0x4C</c>.
    /// </remarks>
    [NativeOffset(0x4C)]
    [NativeName("m_fAnalysisWindowMs")]
    [NativeMetadata("MPropertyFriendlyName", "Analysis Window")]
    public float AnalysisWindowMs { get; set; }

    /// <summary>
    ///     Envelope Mode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_mode</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_mode")]
    [NativeMetadata("MPropertyFriendlyName", "Envelope Mode")]
    public EMode Mode { get; set; }

    /// <summary>
    ///     Threshold.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flThreshold</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_flThreshold")]
    [NativeMetadata("MPropertyFriendlyName", "Threshold")]
    public float Threshold { get; set; }
}
