// <auto-generated/>
// CS2OpenSchema — PulseSystem/CPulseCellStepTestDomainTracepoint
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Common;

#endregion

namespace CS2OpenSchema.PulseSystem;

/// <summary>
///     CPulseCell_Step_TestDomainTracepoint
/// </summary>
/// <remarks>
///     Module: <c>pulse_system</c> — 72 bytes, align 8.
/// </remarks>
[NativeSize(72)]
[NativeName("CPulseCell_Step_TestDomainTracepoint")]
public partial class CPulseCellStepTestDomainTracepoint : CPulseCellBaseFlow
{
}
