// <auto-generated/>
// CS2OpenSchema — Server/CBreakable
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Client;
using CS2OpenSchema.Common;
using CS2OpenSchema.Entity2;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     CBreakable.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 2112 bytes.
/// </remarks>
[NativeSize(2112)]
public partial class CBreakable : CBaseModelEntity
{
    /// <summary>
    ///     Gets or sets Breaker.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hBreaker</c> at offset <c>0x7B4</c>.
    /// </remarks>
    [NativeOffset(0x7B4)]
    [NativeName("m_hBreaker")]
    public CHandle<CBaseEntity> Breaker { get; set; }

    /// <summary>
    ///     Gets or sets CPropDataComponent.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_CPropDataComponent</c> at offset <c>0x770</c>.
    /// </remarks>
    [NativeOffset(0x770)]
    [NativeName("m_CPropDataComponent")]
    public CPropDataComponent CPropDataComponent { get; set; }

    /// <summary>
    ///     Gets or sets Explosion.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Explosion</c> at offset <c>0x7B8</c>.
    /// </remarks>
    [NativeOffset(0x7B8)]
    [NativeName("m_Explosion")]
    public Explosions Explosion { get; set; }

    /// <summary>
    ///     Gets or sets ImpactEnergyScale.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_impactEnergyScale</c> at offset <c>0x7D8</c>.
    /// </remarks>
    [NativeOffset(0x7D8)]
    [NativeName("m_impactEnergyScale")]
    public float ImpactEnergyScale { get; set; }

    /// <summary>
    ///     Gets or sets LastPhysicsInfluenceTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flLastPhysicsInfluenceTime</c> at offset <c>0x838</c>.
    /// </remarks>
    [NativeOffset(0x838)]
    [NativeName("m_flLastPhysicsInfluenceTime")]
    public GameTime LastPhysicsInfluenceTime { get; set; }

    /// <summary>
    ///     Gets or sets Material.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Material</c> at offset <c>0x7B0</c>.
    /// </remarks>
    [NativeOffset(0x7B0)]
    [NativeName("m_Material")]
    public Materials Material { get; set; }

    /// <summary>
    ///     Gets or sets MinHealthDmg.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iMinHealthDmg</c> at offset <c>0x7CC</c>.
    /// </remarks>
    [NativeOffset(0x7CC)]
    [NativeName("m_iMinHealthDmg")]
    public int MinHealthDmg { get; set; }

    /// <summary>
    ///     Gets or sets OnBreak.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnBreak</c> at offset <c>0x7F8</c>.
    /// </remarks>
    [NativeOffset(0x7F8)]
    [NativeName("m_OnBreak")]
    public CEntityIOOutput OnBreak { get; set; }

    /// <summary>
    ///     Gets or sets OnHealthChanged.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnHealthChanged</c> at offset <c>0x810</c>.
    /// </remarks>
    [NativeOffset(0x810)]
    [NativeName("m_OnHealthChanged")]
    public float? OnHealthChanged { get; set; }

    /// <summary>
    ///     Gets or sets OnStartDeath.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnStartDeath</c> at offset <c>0x7E0</c>.
    /// </remarks>
    [NativeOffset(0x7E0)]
    [NativeName("m_OnStartDeath")]
    public CEntityIOOutput OnStartDeath { get; set; }

    /// <summary>
    ///     Gets or sets OverrideBlockLOS.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nOverrideBlockLOS</c> at offset <c>0x7DC</c>.
    /// </remarks>
    [NativeOffset(0x7DC)]
    [NativeName("m_nOverrideBlockLOS")]
    public EOverrideBlockLOS OverrideBlockLOS { get; set; }

    /// <summary>
    ///     Gets or sets PerformanceMode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_PerformanceMode</c> at offset <c>0x830</c>.
    /// </remarks>
    [NativeOffset(0x830)]
    [NativeName("m_PerformanceMode")]
    public PerformanceMode PerformanceMode { get; set; }

    /// <summary>
    ///     Gets or sets PhysicsAttacker.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hPhysicsAttacker</c> at offset <c>0x834</c>.
    /// </remarks>
    [NativeOffset(0x834)]
    [NativeName("m_hPhysicsAttacker")]
    public CHandle<CBasePlayerPawn> PhysicsAttacker { get; set; }

    /// <summary>
    ///     Gets or sets PressureDelay.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flPressureDelay</c> at offset <c>0x7C8</c>.
    /// </remarks>
    [NativeOffset(0x7C8)]
    [NativeName("m_flPressureDelay")]
    public float PressureDelay { get; set; }

    /// <summary>
    ///     Gets or sets PropData.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iszPropData</c> at offset <c>0x7D0</c>.
    /// </remarks>
    [NativeOffset(0x7D0)]
    [NativeName("m_iszPropData")]
    public string PropData { get; set; }

    /// <summary>
    ///     Gets or sets SpawnObject.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iszSpawnObject</c> at offset <c>0x7C0</c>.
    /// </remarks>
    [NativeOffset(0x7C0)]
    [NativeName("m_iszSpawnObject")]
    public string SpawnObject { get; set; }
}
