// <auto-generated/>
// CS2OpenSchema — Server/CDynamicPropAliasDynamicProp
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CDynamicPropAlias_dynamic_prop.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 2976 bytes, align 16.
/// </remarks>
[NativeSize(2976)]
[NativeName("CDynamicPropAlias_dynamic_prop")]
public partial class CDynamicPropAliasDynamicProp : CDynamicProp
{
}
