// <auto-generated/>
// CS2OpenSchema — Server/CEconItemView
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CEconItemView.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 680 bytes.
/// </remarks>
[NativeSize(680)]
public partial class CEconItemView : IEconItemInterface
{
    /// <summary>
    ///     Gets or sets AccountId.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iAccountID</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_iAccountID")]
    public uint AccountId { get; set; }

    /// <summary>
    ///     Gets or sets AttributeList.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_AttributeList</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_AttributeList")]
    public CAttributeList AttributeList { get; set; }

    /// <summary>
    ///     Gets or sets CustomName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_szCustomName</c> at offset <c>0x160</c>.
    /// </remarks>
    [NativeOffset(0x160)]
    [NativeName("m_szCustomName")]
    public string CustomName { get; set; }

    /// <summary>
    ///     Gets or sets CustomNameOverride.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_szCustomNameOverride</c> at offset <c>0x201</c>.
    /// </remarks>
    [NativeOffset(0x201)]
    [NativeName("m_szCustomNameOverride")]
    public string CustomNameOverride { get; set; }

    /// <summary>
    ///     Gets or sets EntityLevel.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iEntityLevel</c> at offset <c>0x40</c>.
    /// </remarks>
    [NativeOffset(0x40)]
    [NativeName("m_iEntityLevel")]
    public uint EntityLevel { get; set; }

    /// <summary>
    ///     Gets or sets EntityQuality.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iEntityQuality</c> at offset <c>0x3C</c>.
    /// </remarks>
    [NativeOffset(0x3C)]
    [NativeName("m_iEntityQuality")]
    public int EntityQuality { get; set; }

    /// <summary>
    ///     Gets or sets Initialized.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInitialized</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_bInitialized")]
    public bool Initialized { get; set; }

    /// <summary>
    ///     Gets or sets InventoryPosition.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iInventoryPosition</c> at offset <c>0x5C</c>.
    /// </remarks>
    [NativeOffset(0x5C)]
    [NativeName("m_iInventoryPosition")]
    public uint InventoryPosition { get; set; }

    /// <summary>
    ///     Gets or sets ItemDefinitionIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iItemDefinitionIndex</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_iItemDefinitionIndex")]
    public ushort ItemDefinitionIndex { get; set; }

    /// <summary>
    ///     Gets or sets ItemId.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iItemID</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_iItemID")]
    public ulong ItemId { get; set; }

    /// <summary>
    ///     Gets or sets ItemIdHigh.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iItemIDHigh</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_iItemIDHigh")]
    public uint ItemIdHigh { get; set; }

    /// <summary>
    ///     Gets or sets ItemIdLow.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iItemIDLow</c> at offset <c>0x54</c>.
    /// </remarks>
    [NativeOffset(0x54)]
    [NativeName("m_iItemIDLow")]
    public uint ItemIdLow { get; set; }

    /// <summary>
    ///     Gets or sets NetworkedDynamicAttributes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_NetworkedDynamicAttributes</c> at offset <c>0xE8</c>.
    /// </remarks>
    [NativeOffset(0xE8)]
    [NativeName("m_NetworkedDynamicAttributes")]
    public CAttributeList NetworkedDynamicAttributes { get; set; }
}
