// <auto-generated/>
// CS2OpenSchema — Server/CEnvSky
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Resourcesystem;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     CEnvSky.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1992 bytes.
/// </remarks>
[NativeSize(1992)]
[NativeMetadata("MEntityAllowsPortraitWorldSpawn")]
public partial class CEnvSky : CBaseModelEntity
{
    /// <summary>
    ///     Gets or sets BrightnessScale.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flBrightnessScale</c> at offset <c>0x784</c>.
    /// </remarks>
    [NativeOffset(0x784)]
    [NativeName("m_flBrightnessScale")]
    public float BrightnessScale { get; set; }

    /// <summary>
    ///     Gets or sets Enabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bEnabled</c> at offset <c>0x79C</c>.
    /// </remarks>
    [NativeOffset(0x79C)]
    [NativeName("m_bEnabled")]
    public bool Enabled { get; set; }

    /// <summary>
    ///     Gets or sets FogMaxEnd.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFogMaxEnd</c> at offset <c>0x798</c>.
    /// </remarks>
    [NativeOffset(0x798)]
    [NativeName("m_flFogMaxEnd")]
    public float FogMaxEnd { get; set; }

    /// <summary>
    ///     Gets or sets FogMaxStart.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFogMaxStart</c> at offset <c>0x794</c>.
    /// </remarks>
    [NativeOffset(0x794)]
    [NativeName("m_flFogMaxStart")]
    public float FogMaxStart { get; set; }

    /// <summary>
    ///     Gets or sets FogMinEnd.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFogMinEnd</c> at offset <c>0x790</c>.
    /// </remarks>
    [NativeOffset(0x790)]
    [NativeName("m_flFogMinEnd")]
    public float FogMinEnd { get; set; }

    /// <summary>
    ///     Gets or sets FogMinStart.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFogMinStart</c> at offset <c>0x78C</c>.
    /// </remarks>
    [NativeOffset(0x78C)]
    [NativeName("m_flFogMinStart")]
    public float FogMinStart { get; set; }

    /// <summary>
    ///     Gets or sets FogType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nFogType</c> at offset <c>0x788</c>.
    /// </remarks>
    [NativeOffset(0x788)]
    [NativeName("m_nFogType")]
    public int FogType { get; set; }

    /// <summary>
    ///     Gets or sets SkyMaterial.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hSkyMaterial</c> at offset <c>0x768</c>.
    /// </remarks>
    [NativeOffset(0x768)]
    [NativeName("m_hSkyMaterial")]
    public CStrongHandle<InfoForResourceTypeIMaterial2> SkyMaterial { get; set; }

    /// <summary>
    ///     Gets or sets SkyMaterialLightingOnly.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hSkyMaterialLightingOnly</c> at offset <c>0x770</c>.
    /// </remarks>
    [NativeOffset(0x770)]
    [NativeName("m_hSkyMaterialLightingOnly")]
    public CStrongHandle<InfoForResourceTypeIMaterial2> SkyMaterialLightingOnly { get; set; }

    /// <summary>
    ///     Gets or sets StartDisabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bStartDisabled</c> at offset <c>0x778</c>.
    /// </remarks>
    [NativeOffset(0x778)]
    [NativeName("m_bStartDisabled")]
    public bool StartDisabled { get; set; }

    /// <summary>
    ///     Gets or sets TintColor.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vTintColor</c> at offset <c>0x779</c>.
    /// </remarks>
    [NativeOffset(0x779)]
    [NativeName("m_vTintColor")]
    public Color TintColor { get; set; }

    /// <summary>
    ///     Gets or sets TintColorLightingOnly.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vTintColorLightingOnly</c> at offset <c>0x77D</c>.
    /// </remarks>
    [NativeOffset(0x77D)]
    [NativeName("m_vTintColorLightingOnly")]
    public Color TintColorLightingOnly { get; set; }
}
