// <auto-generated/>
// CS2OpenSchema — Server/CInfoVisibilityBox
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CInfoVisibilityBox.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1216 bytes.
/// </remarks>
[NativeSize(1216)]
public partial class CInfoVisibilityBox : CBaseEntity
{
    /// <summary>
    ///     Gets or sets BoxSize.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vBoxSize</c> at offset <c>0x4B0</c>.
    /// </remarks>
    [NativeOffset(0x4B0)]
    [NativeName("m_vBoxSize")]
    public Vector BoxSize { get; set; }

    /// <summary>
    ///     Gets or sets Enabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bEnabled</c> at offset <c>0x4BC</c>.
    /// </remarks>
    [NativeOffset(0x4BC)]
    [NativeName("m_bEnabled")]
    public bool Enabled { get; set; }

    /// <summary>
    ///     Gets or sets Mode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nMode</c> at offset <c>0x4AC</c>.
    /// </remarks>
    [NativeOffset(0x4AC)]
    [NativeName("m_nMode")]
    public int Mode { get; set; }
}
