// <auto-generated/>
// CS2OpenSchema — Server/CLogicAuto
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Entity2;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     CLogicAuto.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1440 bytes, align 8.
/// </remarks>
[NativeSize(1440)]
public partial class CLogicAuto : CBaseEntity
{
    /// <summary>
    ///     Gets or sets GlobalState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_globalstate</c> at offset <c>0x598</c>.
    /// </remarks>
    [NativeOffset(0x598)]
    [NativeName("m_globalstate")]
    public string GlobalState { get; set; }

    /// <summary>
    ///     Gets or sets OnBackgroundMap.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnBackgroundMap</c> at offset <c>0x520</c>.
    /// </remarks>
    [NativeOffset(0x520)]
    [NativeName("m_OnBackgroundMap")]
    public CEntityIOOutput OnBackgroundMap { get; set; }

    /// <summary>
    ///     Gets or sets OnDemoMapSpawn.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnDemoMapSpawn</c> at offset <c>0x4C0</c>.
    /// </remarks>
    [NativeOffset(0x4C0)]
    [NativeName("m_OnDemoMapSpawn")]
    public CEntityIOOutput OnDemoMapSpawn { get; set; }

    /// <summary>
    ///     Gets or sets OnLoadGame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnLoadGame</c> at offset <c>0x4F0</c>.
    /// </remarks>
    [NativeOffset(0x4F0)]
    [NativeName("m_OnLoadGame")]
    public CEntityIOOutput OnLoadGame { get; set; }

    /// <summary>
    ///     Gets or sets OnMapSpawn.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnMapSpawn</c> at offset <c>0x4A8</c>.
    /// </remarks>
    [NativeOffset(0x4A8)]
    [NativeName("m_OnMapSpawn")]
    public CEntityIOOutput OnMapSpawn { get; set; }

    /// <summary>
    ///     Gets or sets OnMapTransition.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnMapTransition</c> at offset <c>0x508</c>.
    /// </remarks>
    [NativeOffset(0x508)]
    [NativeName("m_OnMapTransition")]
    public CEntityIOOutput OnMapTransition { get; set; }

    /// <summary>
    ///     Gets or sets OnMultiNewMap.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnMultiNewMap</c> at offset <c>0x538</c>.
    /// </remarks>
    [NativeOffset(0x538)]
    [NativeName("m_OnMultiNewMap")]
    public CEntityIOOutput OnMultiNewMap { get; set; }

    /// <summary>
    ///     Gets or sets OnMultiNewRound.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnMultiNewRound</c> at offset <c>0x550</c>.
    /// </remarks>
    [NativeOffset(0x550)]
    [NativeName("m_OnMultiNewRound")]
    public CEntityIOOutput OnMultiNewRound { get; set; }

    /// <summary>
    ///     Gets or sets OnNewGame.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnNewGame</c> at offset <c>0x4D8</c>.
    /// </remarks>
    [NativeOffset(0x4D8)]
    [NativeName("m_OnNewGame")]
    public CEntityIOOutput OnNewGame { get; set; }

    /// <summary>
    ///     Gets or sets OnVREnabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnVREnabled</c> at offset <c>0x568</c>.
    /// </remarks>
    [NativeOffset(0x568)]
    [NativeName("m_OnVREnabled")]
    public CEntityIOOutput OnVREnabled { get; set; }

    /// <summary>
    ///     Gets or sets OnVRNotEnabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnVRNotEnabled</c> at offset <c>0x580</c>.
    /// </remarks>
    [NativeOffset(0x580)]
    [NativeName("m_OnVRNotEnabled")]
    public CEntityIOOutput OnVRNotEnabled { get; set; }
}
