// <auto-generated/>
// CS2OpenSchema — Server/CMolotovProjectile
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Common;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     The thrown molotov / incendiary-grenade projectile that spawns a CInferno fire on impact.
/// </summary>
/// <remarks>
///     Native name: <c>CMolotovProjectile</c>. Module: <c>server</c> — 2912 bytes, align 16.
/// </remarks>
[NativeSize(2912)]
public partial class CMolotovProjectile : CBaseCSGrenadeProjectile
{
    /// <summary>
    ///     Whether the projectile has already ignited.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bDetonated</c> at offset <c>0xA78</c>.
    /// </remarks>
    [NativeOffset(0xA78)]
    [NativeName("m_bDetonated")]
    public bool Detonated { get; set; }

    /// <summary>
    ///     True for the CT incendiary grenade, false for the T molotov.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsIncGrenade</c> at offset <c>0xA60</c>.
    /// </remarks>
    [NativeOffset(0xA60)]
    [NativeName("m_bIsIncGrenade")]
    public bool IsIncGrenade { get; set; }

    /// <summary>
    ///     Gets or sets StillTimer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_stillTimer</c> at offset <c>0xA80</c>.
    /// </remarks>
    [NativeOffset(0xA80)]
    [NativeName("m_stillTimer")]
    public IntervalTimer StillTimer { get; set; }
}
