// <auto-generated/>
// CS2OpenSchema — Server/CPhysConstraint
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Entity2;
using CS2OpenSchema.Vphysics2;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     CPhysConstraint.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1288 bytes — abstract.
/// </remarks>
[NativeSize(1288)]
public abstract partial class CPhysConstraint : CLogicalEntity
{
    /// <summary>
    ///     Gets or sets Attach1.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hAttach1</c> at offset <c>0x4C0</c>.
    /// </remarks>
    [NativeOffset(0x4C0)]
    [NativeName("m_hAttach1")]
    public CHandle__CBaseEntity__ Attach1 { get; set; }

    /// <summary>
    ///     Gets or sets Attach2.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hAttach2</c> at offset <c>0x4C4</c>.
    /// </remarks>
    [NativeOffset(0x4C4)]
    [NativeName("m_hAttach2")]
    public CHandle__CBaseEntity__ Attach2 { get; set; }

    /// <summary>
    ///     Gets or sets BreakSound.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_breakSound</c> at offset <c>0x4D8</c>.
    /// </remarks>
    [NativeOffset(0x4D8)]
    [NativeName("m_breakSound")]
    public CGameSoundEventName BreakSound { get; set; }

    /// <summary>
    ///     Gets or sets ForceLimit.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_forceLimit</c> at offset <c>0x4E0</c>.
    /// </remarks>
    [NativeOffset(0x4E0)]
    [NativeName("m_forceLimit")]
    public float ForceLimit { get; set; }

    /// <summary>
    ///     Gets or sets Joint.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hJoint</c> at offset <c>0x4A8</c>.
    /// </remarks>
    [NativeOffset(0x4A8)]
    [NativeName("m_hJoint")]
    [NativeMetadata("MPhysPtr", "")]
    public IPhysicsJoint? Joint { get; set; }

    /// <summary>
    ///     Gets or sets MinTeleportDistance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_minTeleportDistance</c> at offset <c>0x4E8</c>.
    /// </remarks>
    [NativeOffset(0x4E8)]
    [NativeName("m_minTeleportDistance")]
    public float MinTeleportDistance { get; set; }

    /// <summary>
    ///     Gets or sets NameAttach1.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nameAttach1</c> at offset <c>0x4B0</c>.
    /// </remarks>
    [NativeOffset(0x4B0)]
    [NativeName("m_nameAttach1")]
    public string NameAttach1 { get; set; }

    /// <summary>
    ///     Gets or sets NameAttach2.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nameAttach2</c> at offset <c>0x4B8</c>.
    /// </remarks>
    [NativeOffset(0x4B8)]
    [NativeName("m_nameAttach2")]
    public string NameAttach2 { get; set; }

    /// <summary>
    ///     Gets or sets NameAttachment1.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nameAttachment1</c> at offset <c>0x4C8</c>.
    /// </remarks>
    [NativeOffset(0x4C8)]
    [NativeName("m_nameAttachment1")]
    public string NameAttachment1 { get; set; }

    /// <summary>
    ///     Gets or sets NameAttachment2.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nameAttachment2</c> at offset <c>0x4D0</c>.
    /// </remarks>
    [NativeOffset(0x4D0)]
    [NativeName("m_nameAttachment2")]
    public string NameAttachment2 { get; set; }

    /// <summary>
    ///     Gets or sets OnBreak.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnBreak</c> at offset <c>0x4F0</c>.
    /// </remarks>
    [NativeOffset(0x4F0)]
    [NativeName("m_OnBreak")]
    public CEntityIOOutput OnBreak { get; set; }

    /// <summary>
    ///     Gets or sets SnapObjectPositions.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bSnapObjectPositions</c> at offset <c>0x4EC</c>.
    /// </remarks>
    [NativeOffset(0x4EC)]
    [NativeName("m_bSnapObjectPositions")]
    public bool SnapObjectPositions { get; set; }

    /// <summary>
    ///     Gets or sets TorqueLimit.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_torqueLimit</c> at offset <c>0x4E4</c>.
    /// </remarks>
    [NativeOffset(0x4E4)]
    [NativeName("m_torqueLimit")]
    public float TorqueLimit { get; set; }

    /// <summary>
    ///     Gets or sets TreatEntity1AsInfiniteMass.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bTreatEntity1AsInfiniteMass</c> at offset <c>0x4ED</c>.
    /// </remarks>
    [NativeOffset(0x4ED)]
    [NativeName("m_bTreatEntity1AsInfiniteMass")]
    public bool TreatEntity1AsInfiniteMass { get; set; }
}
