// <auto-generated/>
// CS2OpenSchema — Server/CPointVelocitySensor
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CPointVelocitySensor.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1256 bytes, align 8.
/// </remarks>
[NativeSize(1256)]
public partial class CPointVelocitySensor : CPointEntity
{
    /// <summary>
    ///     Gets or sets AvgInterval.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flAvgInterval</c> at offset <c>0x4C0</c>.
    /// </remarks>
    [NativeOffset(0x4C0)]
    [NativeName("m_flAvgInterval")]
    public float AvgInterval { get; set; }

    /// <summary>
    ///     Gets or sets Axis.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecAxis</c> at offset <c>0x4AC</c>.
    /// </remarks>
    [NativeOffset(0x4AC)]
    [NativeName("m_vecAxis")]
    public Vector Axis { get; set; }

    /// <summary>
    ///     Gets or sets Enabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bEnabled</c> at offset <c>0x4B8</c>.
    /// </remarks>
    [NativeOffset(0x4B8)]
    [NativeName("m_bEnabled")]
    public bool Enabled { get; set; }

    /// <summary>
    ///     Gets or sets PrevVelocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fPrevVelocity</c> at offset <c>0x4BC</c>.
    /// </remarks>
    [NativeOffset(0x4BC)]
    [NativeName("m_fPrevVelocity")]
    public float PrevVelocity { get; set; }

    /// <summary>
    ///     Gets or sets TargetEntity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hTargetEntity</c> at offset <c>0x4A8</c>.
    /// </remarks>
    [NativeOffset(0x4A8)]
    [NativeName("m_hTargetEntity")]
    public CHandle__CBaseEntity__ TargetEntity { get; set; }

    /// <summary>
    ///     Gets or sets Velocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Velocity</c> at offset <c>0x4C8</c>.
    /// </remarks>
    [NativeOffset(0x4C8)]
    [NativeName("m_Velocity")]
    public CEntityOutputTemplate__float32__ Velocity { get; set; }
}
