// <auto-generated/>
// CS2OpenSchema — Server/CSWeaponMode
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     Weapon fire mode: primary vs secondary (right-click) fire.
/// </summary>
/// <remarks>
///     Native name: <c>CSWeaponMode</c>. Module: <c>server</c> — 32-bit.
/// </remarks>
public enum CSWeaponMode : uint
{
    /// <summary>
    ///     Primary fire.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>Primary_Mode</c>.
    /// </remarks>
    [NativeName("Primary_Mode")]
    Primary_Mode = 0,

    /// <summary>
    ///     Secondary fire (e.g. scope, burst, silencer toggle).
    /// </summary>
    /// <remarks>
    ///     Native name: <c>Secondary_Mode</c>.
    /// </remarks>
    [NativeName("Secondary_Mode")]
    Secondary_Mode = 1,

    /// <summary>
    ///     WeaponMode_MAX.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>WeaponMode_MAX</c>.
    /// </remarks>
    [NativeName("WeaponMode_MAX")]
    WeaponMode_MAX = 2
}
