// <auto-generated/>
// CS2OpenSchema — Server/DecalFlags
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     DecalFlags_t.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32-bit.
/// </remarks>
[NativeName("DecalFlags_t")]
public enum DecalFlags : uint
{
    /// <summary>
    ///     None.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eNone</c>.
    /// </remarks>
    [NativeName("eNone")]
    [NativeMetadata("MEnumeratorIsNotAFlag", "")]
    None = 0,

    /// <summary>
    ///     CanNotClear.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eCannotClear</c>.
    /// </remarks>
    [NativeName("eCannotClear")]
    CanNotClear = 1,

    /// <summary>
    ///     DecalProjectToBackFaces.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eDecalProjectToBackfaces</c>.
    /// </remarks>
    [NativeName("eDecalProjectToBackfaces")]
    DecalProjectToBackFaces = 2,

    /// <summary>
    ///     AllButCanNotClear.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eAllButCannotClear</c>.
    /// </remarks>
    [NativeName("eAllButCannotClear")]
    [NativeMetadata("MEnumeratorIsNotAFlag", "")]
    AllButCanNotClear = 4294967294,

    /// <summary>
    ///     All.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eAll</c>.
    /// </remarks>
    [NativeName("eAll")]
    [NativeMetadata("MEnumeratorIsNotAFlag", "")]
    All = 4294967295
}
