// <auto-generated/>
// CS2OpenSchema — Server/EGCBaseProtoObjectTypes
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     EGCBaseProtoObjectTypes.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32-bit.
/// </remarks>
public enum EGCBaseProtoObjectTypes : uint
{
    /// <summary>
    ///     EProtoObjectPartyInvite.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_EProtoObjectPartyInvite</c>.
    /// </remarks>
    [NativeName("k_EProtoObjectPartyInvite")]
    EProtoObjectPartyInvite = 1001,

    /// <summary>
    ///     EProtoObjectLobbyInvite.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_EProtoObjectLobbyInvite</c>.
    /// </remarks>
    [NativeName("k_EProtoObjectLobbyInvite")]
    EProtoObjectLobbyInvite = 1002
}
