// <auto-generated/>
// CS2OpenSchema — Server/ETEProtobufIds
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     ETEProtobufIds.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32-bit.
/// </remarks>
public enum ETEProtobufIds : uint
{
    /// <summary>
    ///     TE_EffectDispatchId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_EffectDispatchId</c>.
    /// </remarks>
    [NativeName("TE_EffectDispatchId")]
    TE_EffectDispatchId = 400,

    /// <summary>
    ///     TE_ArmorRicochetId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_ArmorRicochetId</c>.
    /// </remarks>
    [NativeName("TE_ArmorRicochetId")]
    TE_ArmorRicochetId = 401,

    /// <summary>
    ///     TE_BeamEntPointId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BeamEntPointId</c>.
    /// </remarks>
    [NativeName("TE_BeamEntPointId")]
    TE_BeamEntPointId = 402,

    /// <summary>
    ///     TE_BeamEntsId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BeamEntsId</c>.
    /// </remarks>
    [NativeName("TE_BeamEntsId")]
    TE_BeamEntsId = 403,

    /// <summary>
    ///     TE_BeamPointsId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BeamPointsId</c>.
    /// </remarks>
    [NativeName("TE_BeamPointsId")]
    TE_BeamPointsId = 404,

    /// <summary>
    ///     TE_BeamRingId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BeamRingId</c>.
    /// </remarks>
    [NativeName("TE_BeamRingId")]
    TE_BeamRingId = 405,

    /// <summary>
    ///     TE_BubblesId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BubblesId</c>.
    /// </remarks>
    [NativeName("TE_BubblesId")]
    TE_BubblesId = 408,

    /// <summary>
    ///     TE_BubbleTrailId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BubbleTrailId</c>.
    /// </remarks>
    [NativeName("TE_BubbleTrailId")]
    TE_BubbleTrailId = 409,

    /// <summary>
    ///     TE_DecalId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_DecalId</c>.
    /// </remarks>
    [NativeName("TE_DecalId")]
    TE_DecalId = 410,

    /// <summary>
    ///     TE_WorldDecalId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_WorldDecalId</c>.
    /// </remarks>
    [NativeName("TE_WorldDecalId")]
    TE_WorldDecalId = 411,

    /// <summary>
    ///     TE_EnergySplashId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_EnergySplashId</c>.
    /// </remarks>
    [NativeName("TE_EnergySplashId")]
    TE_EnergySplashId = 412,

    /// <summary>
    ///     TE_FizzId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_FizzId</c>.
    /// </remarks>
    [NativeName("TE_FizzId")]
    TE_FizzId = 413,

    /// <summary>
    ///     TE_ShatterSurfaceId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_ShatterSurfaceId</c>.
    /// </remarks>
    [NativeName("TE_ShatterSurfaceId")]
    TE_ShatterSurfaceId = 414,

    /// <summary>
    ///     TE_GlowSpriteId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_GlowSpriteId</c>.
    /// </remarks>
    [NativeName("TE_GlowSpriteId")]
    TE_GlowSpriteId = 415,

    /// <summary>
    ///     TE_ImpactId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_ImpactId</c>.
    /// </remarks>
    [NativeName("TE_ImpactId")]
    TE_ImpactId = 416,

    /// <summary>
    ///     TE_MuzzleFlashId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_MuzzleFlashId</c>.
    /// </remarks>
    [NativeName("TE_MuzzleFlashId")]
    TE_MuzzleFlashId = 417,

    /// <summary>
    ///     TE_BloodStreamId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_BloodStreamId</c>.
    /// </remarks>
    [NativeName("TE_BloodStreamId")]
    TE_BloodStreamId = 418,

    /// <summary>
    ///     TE_ExplosionId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_ExplosionId</c>.
    /// </remarks>
    [NativeName("TE_ExplosionId")]
    TE_ExplosionId = 419,

    /// <summary>
    ///     TE_DustId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_DustId</c>.
    /// </remarks>
    [NativeName("TE_DustId")]
    TE_DustId = 420,

    /// <summary>
    ///     TE_LargeFunnelId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_LargeFunnelId</c>.
    /// </remarks>
    [NativeName("TE_LargeFunnelId")]
    TE_LargeFunnelId = 421,

    /// <summary>
    ///     TE_SparksId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_SparksId</c>.
    /// </remarks>
    [NativeName("TE_SparksId")]
    TE_SparksId = 422,

    /// <summary>
    ///     TE_PhysicsPropId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_PhysicsPropId</c>.
    /// </remarks>
    [NativeName("TE_PhysicsPropId")]
    TE_PhysicsPropId = 423,

    /// <summary>
    ///     TE_SmokeId.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>TE_SmokeId</c>.
    /// </remarks>
    [NativeName("TE_SmokeId")]
    TE_SmokeId = 426
}
