// <auto-generated/>
// CS2OpenSchema — Server/Filter
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     filter_t.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32-bit.
/// </remarks>
[NativeName("filter_t")]
public enum Filter : uint
{
    /// <summary>
    ///     And.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FILTER_AND</c>.
    /// </remarks>
    [NativeName("FILTER_AND")]
    And = 0,

    /// <summary>
    ///     Or.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FILTER_OR</c>.
    /// </remarks>
    [NativeName("FILTER_OR")]
    Or = 1
}
