// <auto-generated/>
// CS2OpenSchema — Server/NavScope
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     NavScope_t.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 8-bit.
/// </remarks>
[NativeName("NavScope_t")]
public enum NavScope : byte
{
    /// <summary>
    ///     First.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eFirst</c>.
    /// </remarks>
    [NativeName("eFirst")]
    [NativeMetadata("MPropertySuppressEnumerator", "")]
    First = 0,

    /// <summary>
    ///     Ground.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eGround</c>.
    /// </remarks>
    [Obsolete("Alias for First.")]
    [NativeName("eGround")]
    Ground = 0,

    /// <summary>
    ///     Air.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eAir</c>.
    /// </remarks>
    [NativeName("eAir")]
    Air = 1,

    /// <summary>
    ///     Count.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eCount</c>.
    /// </remarks>
    [NativeName("eCount")]
    [NativeMetadata("MPropertySuppressEnumerator", "")]
    Count = 2,

    /// <summary>
    ///     Invalid.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>eInvalid</c>.
    /// </remarks>
    [NativeName("eInvalid")]
    [NativeMetadata("MPropertySuppressEnumerator", "")]
    Invalid = 255
}
