// <auto-generated/>
// CS2OpenSchema — Server/RotatorQueueEntry
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     RotatorQueueEntry_t.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32 bytes, align 16.
/// </remarks>
[NativeSize(32)]
[NativeName("RotatorQueueEntry_t")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"qTarget\":\n\t[\n\t\t0.000000,\n\t\t0.000000,\n\t\t0.000000,\n\t\t0.000000\n\t],\n\t\"eSpace\": \"ROTATOR_TARGET_WORLDSPACE\"\n}")]
public partial class RotatorQueueEntry
{
    /// <summary>
    ///     Gets or sets Space.
    /// </summary>
    /// <remarks>
    ///     Native field <c>eSpace</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("eSpace")]
    public RotatorTargetSpace Space { get; set; }

    /// <summary>
    ///     Gets or sets Target.
    /// </summary>
    /// <remarks>
    ///     Native field <c>qTarget</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("qTarget")]
    public Quaternion Target { get; set; }
}
