// <auto-generated/>
// CS2OpenSchema — Server/SpawnPoint
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     SpawnPoint.
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1208 bytes, align 8.
/// </remarks>
[NativeSize(1208)]
public partial class SpawnPoint : CServerOnlyPointEntity
{
    /// <summary>
    ///     Gets or sets Enabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bEnabled</c> at offset <c>0x4AC</c>.
    /// </remarks>
    [NativeOffset(0x4AC)]
    [NativeName("m_bEnabled")]
    public bool Enabled { get; set; }

    /// <summary>
    ///     Gets or sets Priority.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iPriority</c> at offset <c>0x4A8</c>.
    /// </remarks>
    [NativeOffset(0x4A8)]
    [NativeName("m_iPriority")]
    public int Priority { get; set; }

    /// <summary>
    ///     Gets or sets Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nType</c> at offset <c>0x4B0</c>.
    /// </remarks>
    [NativeOffset(0x4B0)]
    [NativeName("m_nType")]
    public int Type { get; set; }
}
