// <auto-generated/>
// CS2OpenSchema — Worldrenderer/EntityKeyValueData
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Worldrenderer;

/// <summary>
///     EntityKeyValueData_t.
/// </summary>
/// <remarks>
///     Module: <c>worldrenderer</c> — 56 bytes.
/// </remarks>
[NativeSize(56)]
[NativeName("EntityKeyValueData_t")]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_connections\":\n\t[\n\t],\n\t\"m_keyValuesData\": \"[BINARY BLOB]\"\n}")]
public partial class EntityKeyValueData
{
    /// <summary>
    ///     Gets or sets Connections.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_connections</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_connections")]
    public EntityIOConnectionData[] Connections { get; set; }

    /// <summary>
    ///     Gets or sets KeyValuesData.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_keyValuesData</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_keyValuesData")]
    public byte[] KeyValuesData { get; set; }
}
