// <auto-generated/>
// CS2OpenSchema — Client/C_CSPlayerPawn
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Common;
using CS2OpenSchema.Entity2;
using CS2OpenSchema.Server;

#endregion

namespace CS2OpenSchema.Client;

/// <summary>
///     C_CSPlayerPawn.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 13424 bytes, align 16.
/// </remarks>
[NativeSize(13424)]
public partial class C_CSPlayerPawn : C_CSPlayerPawnBase
{
    /// <summary>
    ///     Gets or sets ActionTrackingServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pActionTrackingServices</c> at offset <c>0x14B0</c>.
    /// </remarks>
    [NativeOffset(0x14B0)]
    [NativeName("m_pActionTrackingServices")]
    public CCSPlayerActionTrackingServices? ActionTrackingServices { get; set; }

    /// <summary>
    ///     Gets or sets AimPunchServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pAimPunchServices</c> at offset <c>0x14B8</c>.
    /// </remarks>
    [NativeOffset(0x14B8)]
    [NativeName("m_pAimPunchServices")]
    public CCSPlayerAimPunchServices? AimPunchServices { get; set; }

    /// <summary>
    ///     Gets or sets ArmorValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ArmorValue</c> at offset <c>0x1CA4</c>.
    /// </remarks>
    [NativeOffset(0x1CA4)]
    [NativeName("m_ArmorValue")]
    public int ArmorValue { get; set; }

    /// <summary>
    ///     Gets or sets ArrOldEyeAngles.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_arrOldEyeAngles</c> at offset <c>0x33F0</c>.
    /// </remarks>
    [NativeOffset(0x33F0)]
    [NativeName("m_arrOldEyeAngles")]
    public QAngle[] ArrOldEyeAngles { get; set; }

    /// <summary>
    ///     Gets or sets ArrOldEyeAnglesTimes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_arrOldEyeAnglesTimes</c> at offset <c>0x33E0</c>.
    /// </remarks>
    [NativeOffset(0x33E0)]
    [NativeName("m_arrOldEyeAnglesTimes")]
    public GameTime[] ArrOldEyeAnglesTimes { get; set; }

    /// <summary>
    ///     Gets or sets BlockingUseActionInProgress.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iBlockingUseActionInProgress</c> at offset <c>0x1C7C</c>.
    /// </remarks>
    [NativeOffset(0x1C7C)]
    [NativeName("m_iBlockingUseActionInProgress")]
    public CSPlayerBlockingUseAction BlockingUseActionInProgress { get; set; }

    /// <summary>
    ///     Gets or sets BulletHitModels.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecBulletHitModels</c> at offset <c>0x1C40</c>.
    /// </remarks>
    [NativeOffset(0x1C40)]
    [NativeName("m_vecBulletHitModels")]
    public CUtlVector__C_BulletHitModel___ BulletHitModels { get; set; }

    /// <summary>
    ///     Gets or sets BulletServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pBulletServices</c> at offset <c>0x1490</c>.
    /// </remarks>
    [NativeOffset(0x1490)]
    [NativeName("m_pBulletServices")]
    public CCSPlayerBulletServices? BulletServices { get; set; }

    /// <summary>
    ///     Gets or sets BuyServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pBuyServices</c> at offset <c>0x14A0</c>.
    /// </remarks>
    [NativeOffset(0x14A0)]
    [NativeName("m_pBuyServices")]
    public CCSPlayerBuyServices? BuyServices { get; set; }

    /// <summary>
    ///     Gets or sets CurrentEquipmentValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_unCurrentEquipmentValue</c> at offset <c>0x1CA8</c>.
    /// </remarks>
    [NativeOffset(0x1CA8)]
    [NativeName("m_unCurrentEquipmentValue")]
    public ushort CurrentEquipmentValue { get; set; }

    /// <summary>
    ///     Gets or sets DamageReactServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pDamageReactServices</c> at offset <c>0x14C0</c>.
    /// </remarks>
    [NativeOffset(0x14C0)]
    [NativeName("m_pDamageReactServices")]
    public CCSPlayerDamageReactServices? DamageReactServices { get; set; }

    /// <summary>
    ///     Gets or sets DeathEyeAngles.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_qDeathEyeAngles</c> at offset <c>0x1B88</c>.
    /// </remarks>
    [NativeOffset(0x1B88)]
    [NativeName("m_qDeathEyeAngles")]
    public QAngle DeathEyeAngles { get; set; }

    /// <summary>
    ///     Gets or sets DeathInfoOrigin.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecDeathInfoOrigin</c> at offset <c>0x1CBC</c>.
    /// </remarks>
    [NativeOffset(0x1CBC)]
    [NativeName("m_vecDeathInfoOrigin")]
    public VectorWS DeathInfoOrigin { get; set; }

    /// <summary>
    ///     Gets or sets DeathInfoTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flDeathInfoTime</c> at offset <c>0x1CB8</c>.
    /// </remarks>
    [NativeOffset(0x1CB8)]
    [NativeName("m_flDeathInfoTime")]
    public float DeathInfoTime { get; set; }

    /// <summary>
    ///     Gets or sets DelayTargetIDTimer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_delayTargetIDTimer</c> at offset <c>0x3430</c>.
    /// </remarks>
    [NativeOffset(0x3430)]
    [NativeName("m_delayTargetIDTimer")]
    public CountdownTimer DelayTargetIDTimer { get; set; }

    /// <summary>
    ///     Gets or sets EconGloves.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_EconGloves</c> at offset <c>0x1690</c>.
    /// </remarks>
    [NativeOffset(0x1690)]
    [NativeName("m_EconGloves")]
    public C_EconItemView EconGloves { get; set; }

    /// <summary>
    ///     Gets or sets EconGlovesChanged.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nEconGlovesChanged</c> at offset <c>0x1B00</c>.
    /// </remarks>
    [NativeOffset(0x1B00)]
    [NativeName("m_nEconGlovesChanged")]
    public byte EconGlovesChanged { get; set; }

    /// <summary>
    ///     Gets or sets EmitSoundTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flEmitSoundTime</c> at offset <c>0x1C80</c>.
    /// </remarks>
    [NativeOffset(0x1C80)]
    [NativeName("m_flEmitSoundTime")]
    public GameTime EmitSoundTime { get; set; }

    /// <summary>
    ///     Gets or sets EntitySpottedState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_entitySpottedState</c> at offset <c>0x1C60</c>.
    /// </remarks>
    [NativeOffset(0x1C60)]
    [NativeName("m_entitySpottedState")]
    public EntitySpottedState EntitySpottedState { get; set; }

    /// <summary>
    ///     Gets or sets EyeAngles.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_angEyeAngles</c> at offset <c>0x3350</c>.
    /// </remarks>
    [NativeOffset(0x3350)]
    [NativeName("m_angEyeAngles")]
    public QAngle EyeAngles { get; set; }

    /// <summary>
    ///     Gets or sets EyeAnglesVelocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_angEyeAnglesVelocity</c> at offset <c>0x3420</c>.
    /// </remarks>
    [NativeOffset(0x3420)]
    [NativeName("m_angEyeAnglesVelocity")]
    public QAngle EyeAnglesVelocity { get; set; }

    /// <summary>
    ///     Gets or sets FlinchStack.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFlinchStack</c> at offset <c>0x1C90</c>.
    /// </remarks>
    [NativeOffset(0x1C90)]
    [NativeName("m_flFlinchStack")]
    public float FlinchStack { get; set; }

    /// <summary>
    ///     Gets or sets FreezetimeEndEquipmentValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_unFreezetimeEndEquipmentValue</c> at offset <c>0x1CAC</c>.
    /// </remarks>
    [NativeOffset(0x1CAC)]
    [NativeName("m_unFreezetimeEndEquipmentValue")]
    public ushort FreezetimeEndEquipmentValue { get; set; }

    /// <summary>
    ///     Gets or sets GlowServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pGlowServices</c> at offset <c>0x14A8</c>.
    /// </remarks>
    [NativeOffset(0x14A8)]
    [NativeName("m_pGlowServices")]
    public CCSPlayerGlowServices? GlowServices { get; set; }

    /// <summary>
    ///     Gets or sets GrenadeParameterStashTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_grenadeParameterStashTime</c> at offset <c>0x1CF8</c>.
    /// </remarks>
    [NativeOffset(0x1CF8)]
    [NativeName("m_grenadeParameterStashTime")]
    public GameTime GrenadeParameterStashTime { get; set; }

    /// <summary>
    ///     Gets or sets GrenadeParametersStashed.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bGrenadeParametersStashed</c> at offset <c>0x1CFC</c>.
    /// </remarks>
    [NativeOffset(0x1CFC)]
    [NativeName("m_bGrenadeParametersStashed")]
    public bool GrenadeParametersStashed { get; set; }

    /// <summary>
    ///     Gets or sets GunGameImmunity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bGunGameImmunity</c> at offset <c>0x3268</c>.
    /// </remarks>
    [NativeOffset(0x3268)]
    [NativeName("m_bGunGameImmunity")]
    public bool GunGameImmunity { get; set; }

    /// <summary>
    ///     Gets or sets GunGameImmunityColor.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_GunGameImmunityColor</c> at offset <c>0x1BF0</c>.
    /// </remarks>
    [NativeOffset(0x1BF0)]
    [NativeName("m_GunGameImmunityColor")]
    public Color GunGameImmunityColor { get; set; }

    /// <summary>
    ///     Gets or sets HasDeathInfo.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bHasDeathInfo</c> at offset <c>0x1CB5</c>.
    /// </remarks>
    [NativeOffset(0x1CB5)]
    [NativeName("m_bHasDeathInfo")]
    public bool HasDeathInfo { get; set; }

    /// <summary>
    ///     Gets or sets HasFemaleVoice.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bHasFemaleVoice</c> at offset <c>0x14D0</c>.
    /// </remarks>
    [NativeOffset(0x14D0)]
    [NativeName("m_bHasFemaleVoice")]
    public bool HasFemaleVoice { get; set; }

    /// <summary>
    ///     Gets or sets HealthShotBoostExpirationTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flHealthShotBoostExpirationTime</c> at offset <c>0x14C8</c>.
    /// </remarks>
    [NativeOffset(0x14C8)]
    [NativeName("m_flHealthShotBoostExpirationTime")]
    public GameTime HealthShotBoostExpirationTime { get; set; }

    /// <summary>
    ///     Gets or sets HoldTargetIDTimer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_holdTargetIDTimer</c> at offset <c>0x3450</c>.
    /// </remarks>
    [NativeOffset(0x3450)]
    [NativeName("m_holdTargetIDTimer")]
    public CountdownTimer HoldTargetIDTimer { get; set; }

    /// <summary>
    ///     Gets or sets HostageServices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pHostageServices</c> at offset <c>0x1498</c>.
    /// </remarks>
    [NativeOffset(0x1498)]
    [NativeName("m_pHostageServices")]
    public CCSPlayerHostageServices? HostageServices { get; set; }

    /// <summary>
    ///     Gets or sets HudModelArms.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hHudModelArms</c> at offset <c>0x1B84</c>.
    /// </remarks>
    [NativeOffset(0x1B84)]
    [NativeName("m_hHudModelArms")]
    public CHandle__C_CS2HudModelArms__ HudModelArms { get; set; }

    /// <summary>
    ///     Gets or sets IDEntIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iIDEntIndex</c> at offset <c>0x342C</c>.
    /// </remarks>
    [NativeOffset(0x342C)]
    [NativeName("m_iIDEntIndex")]
    public int IDEntIndex { get; set; }

    /// <summary>
    ///     Gets or sets IgnoreLadderJumpTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ignoreLadderJumpTime</c> at offset <c>0x1C9C</c>.
    /// </remarks>
    [NativeOffset(0x1C9C)]
    [NativeName("m_ignoreLadderJumpTime")]
    public float IgnoreLadderJumpTime { get; set; }

    /// <summary>
    ///     Gets or sets ImmuneToGunGameDamageTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fImmuneToGunGameDamageTime</c> at offset <c>0x3264</c>.
    /// </remarks>
    [NativeOffset(0x3264)]
    [NativeName("m_fImmuneToGunGameDamageTime")]
    public GameTime ImmuneToGunGameDamageTime { get; set; }

    /// <summary>
    ///     Gets or sets ImmuneToGunGameDamageTimeLast.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fImmuneToGunGameDamageTimeLast</c> at offset <c>0x326C</c>.
    /// </remarks>
    [NativeOffset(0x326C)]
    [NativeName("m_fImmuneToGunGameDamageTimeLast")]
    public GameTime ImmuneToGunGameDamageTimeLast { get; set; }

    /// <summary>
    ///     Gets or sets InBombZone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInBombZone</c> at offset <c>0x1509</c>.
    /// </remarks>
    [NativeOffset(0x1509)]
    [NativeName("m_bInBombZone")]
    public bool InBombZone { get; set; }

    /// <summary>
    ///     Gets or sets InBuyZone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInBuyZone</c> at offset <c>0x1500</c>.
    /// </remarks>
    [NativeOffset(0x1500)]
    [NativeName("m_bInBuyZone")]
    public bool InBuyZone { get; set; }

    /// <summary>
    ///     Gets or sets InHostageRescueZone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInHostageRescueZone</c> at offset <c>0x1508</c>.
    /// </remarks>
    [NativeOffset(0x1508)]
    [NativeName("m_bInHostageRescueZone")]
    public bool InHostageRescueZone { get; set; }

    /// <summary>
    ///     Gets or sets InLanding.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInLanding</c> at offset <c>0x1502</c>.
    /// </remarks>
    [NativeOffset(0x1502)]
    [NativeName("m_bInLanding")]
    public bool InLanding { get; set; }

    /// <summary>
    ///     Gets or sets InNoDefuseArea.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bInNoDefuseArea</c> at offset <c>0x1C84</c>.
    /// </remarks>
    [NativeOffset(0x1C84)]
    [NativeName("m_bInNoDefuseArea")]
    public bool InNoDefuseArea { get; set; }

    /// <summary>
    ///     Gets or sets IsBuyMenuOpen.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsBuyMenuOpen</c> at offset <c>0x150A</c>.
    /// </remarks>
    [NativeOffset(0x150A)]
    [NativeName("m_bIsBuyMenuOpen")]
    public bool IsBuyMenuOpen { get; set; }

    /// <summary>
    ///     Gets or sets IsDefusing.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsDefusing</c> at offset <c>0x1C7A</c>.
    /// </remarks>
    [NativeOffset(0x1C7A)]
    [NativeName("m_bIsDefusing")]
    public bool IsDefusing { get; set; }

    /// <summary>
    ///     Gets or sets IsGrabbingHostage.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsGrabbingHostage</c> at offset <c>0x1C7B</c>.
    /// </remarks>
    [NativeOffset(0x1C7B)]
    [NativeName("m_bIsGrabbingHostage")]
    public bool IsGrabbingHostage { get; set; }

    /// <summary>
    ///     Gets or sets IsScoped.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsScoped</c> at offset <c>0x1C78</c>.
    /// </remarks>
    [NativeOffset(0x1C78)]
    [NativeName("m_bIsScoped")]
    public bool IsScoped { get; set; }

    /// <summary>
    ///     Gets or sets IsWalking.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bIsWalking</c> at offset <c>0x1C58</c>.
    /// </remarks>
    [NativeOffset(0x1C58)]
    [NativeName("m_bIsWalking")]
    public bool IsWalking { get; set; }

    /// <summary>
    ///     Gets or sets KilledByHeadshot.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bKilledByHeadshot</c> at offset <c>0x1CA1</c>.
    /// </remarks>
    [NativeOffset(0x1CA1)]
    [NativeName("m_bKilledByHeadshot")]
    public bool KilledByHeadshot { get; set; }

    /// <summary>
    ///     Gets or sets LandingStartTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flLandingStartTime</c> at offset <c>0x1504</c>.
    /// </remarks>
    [NativeOffset(0x1504)]
    [NativeName("m_flLandingStartTime")]
    public float LandingStartTime { get; set; }

    /// <summary>
    ///     Gets or sets LandingTimeSeconds.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flLandingTimeSeconds</c> at offset <c>0x14D4</c>.
    /// </remarks>
    [NativeOffset(0x14D4)]
    [NativeName("m_flLandingTimeSeconds")]
    public float LandingTimeSeconds { get; set; }

    /// <summary>
    ///     Gets or sets LastFiredWeaponTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flLastFiredWeaponTime</c> at offset <c>0x14CC</c>.
    /// </remarks>
    [NativeOffset(0x14CC)]
    [NativeName("m_flLastFiredWeaponTime")]
    public GameTime LastFiredWeaponTime { get; set; }

    /// <summary>
    ///     Gets or sets LastKillerIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nLastKillerIndex</c> at offset <c>0x1CB0</c>.
    /// </remarks>
    [NativeOffset(0x1CB0)]
    [NativeName("m_nLastKillerIndex")]
    public int LastKillerIndex { get; set; }

    /// <summary>
    ///     Gets or sets LastLandTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_lastLandTime</c> at offset <c>0x1B64</c>.
    /// </remarks>
    [NativeOffset(0x1B64)]
    [NativeName("m_lastLandTime")]
    public GameTime LastLandTime { get; set; }

    /// <summary>
    ///     Gets or sets LastPlaceName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_szLastPlaceName</c> at offset <c>0x14DC</c>.
    /// </remarks>
    [NativeOffset(0x14DC)]
    [NativeName("m_szLastPlaceName")]
    public string LastPlaceName { get; set; }

    /// <summary>
    ///     Gets or sets LeftHanded.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLeftHanded</c> at offset <c>0x1B94</c>.
    /// </remarks>
    [NativeOffset(0x1B94)]
    [NativeName("m_bLeftHanded")]
    public bool LeftHanded { get; set; }

    /// <summary>
    ///     Gets or sets MolotovDamageTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fMolotovDamageTime</c> at offset <c>0x3270</c>.
    /// </remarks>
    [NativeOffset(0x3270)]
    [NativeName("m_fMolotovDamageTime")]
    public float MolotovDamageTime { get; set; }

    /// <summary>
    ///     Gets or sets MustSyncRagdollState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bMustSyncRagdollState</c> at offset <c>0x1B01</c>.
    /// </remarks>
    [NativeOffset(0x1B01)]
    [NativeName("m_bMustSyncRagdollState")]
    public bool MustSyncRagdollState { get; set; }

    /// <summary>
    ///     Gets or sets NeedToReApplyGloves.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bNeedToReApplyGloves</c> at offset <c>0x168D</c>.
    /// </remarks>
    [NativeOffset(0x168D)]
    [NativeName("m_bNeedToReApplyGloves")]
    public bool NeedToReApplyGloves { get; set; }

    /// <summary>
    ///     Gets or sets NextSprayDecalTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flNextSprayDecalTime</c> at offset <c>0x1510</c>.
    /// </remarks>
    [NativeOffset(0x1510)]
    [NativeName("m_flNextSprayDecalTime")]
    public GameTime NextSprayDecalTime { get; set; }

    /// <summary>
    ///     Gets or sets OldFallVelocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flOldFallVelocity</c> at offset <c>0x14D8</c>.
    /// </remarks>
    [NativeOffset(0x14D8)]
    [NativeName("m_flOldFallVelocity")]
    public float OldFallVelocity { get; set; }

    /// <summary>
    ///     Gets or sets OldIDEntIndex.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iOldIDEntIndex</c> at offset <c>0x344C</c>.
    /// </remarks>
    [NativeOffset(0x344C)]
    [NativeName("m_iOldIDEntIndex")]
    public int OldIDEntIndex { get; set; }

    /// <summary>
    ///     Gets or sets OldIsScoped.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bOldIsScoped</c> at offset <c>0x1CB4</c>.
    /// </remarks>
    [NativeOffset(0x1CB4)]
    [NativeName("m_bOldIsScoped")]
    public bool OldIsScoped { get; set; }

    /// <summary>
    ///     Gets or sets OnGroundLastTick.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bOnGroundLastTick</c> at offset <c>0x1B68</c>.
    /// </remarks>
    [NativeOffset(0x1B68)]
    [NativeName("m_bOnGroundLastTick")]
    public bool OnGroundLastTick { get; set; }

    /// <summary>
    ///     Gets or sets PlayerInfernoBodyFx.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nPlayerInfernoBodyFx</c> at offset <c>0x32DC</c>.
    /// </remarks>
    [NativeOffset(0x32DC)]
    [NativeName("m_nPlayerInfernoBodyFx")]
    public ParticleIndex PlayerInfernoBodyFx { get; set; }

    /// <summary>
    ///     Gets or sets PlayerPatchEconIndices.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecPlayerPatchEconIndices</c> at offset <c>0x1BAC</c>.
    /// </remarks>
    [NativeOffset(0x1BAC)]
    [NativeName("m_vecPlayerPatchEconIndices")]
    public uint[] PlayerPatchEconIndices { get; set; }

    /// <summary>
    ///     Gets or sets PrevArmorVal.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nPrevArmorVal</c> at offset <c>0x14F0</c>.
    /// </remarks>
    [NativeOffset(0x14F0)]
    [NativeName("m_nPrevArmorVal")]
    public int PrevArmorVal { get; set; }

    /// <summary>
    ///     Gets or sets PrevDefuser.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bPrevDefuser</c> at offset <c>0x14EE</c>.
    /// </remarks>
    [NativeOffset(0x14EE)]
    [NativeName("m_bPrevDefuser")]
    public bool PrevDefuser { get; set; }

    /// <summary>
    ///     Gets or sets PrevGrenadeAmmoCount.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nPrevGrenadeAmmoCount</c> at offset <c>0x14F4</c>.
    /// </remarks>
    [NativeOffset(0x14F4)]
    [NativeName("m_nPrevGrenadeAmmoCount")]
    public int PrevGrenadeAmmoCount { get; set; }

    /// <summary>
    ///     Gets or sets PrevHelmet.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bPrevHelmet</c> at offset <c>0x14EF</c>.
    /// </remarks>
    [NativeOffset(0x14EF)]
    [NativeName("m_bPrevHelmet")]
    public bool PrevHelmet { get; set; }

    /// <summary>
    ///     Gets or sets PreviousWeaponHash.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_unPreviousWeaponHash</c> at offset <c>0x14F8</c>.
    /// </remarks>
    [NativeOffset(0x14F8)]
    [NativeName("m_unPreviousWeaponHash")]
    public uint PreviousWeaponHash { get; set; }

    /// <summary>
    ///     Gets or sets PreviouslyInBuyZone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bPreviouslyInBuyZone</c> at offset <c>0x1501</c>.
    /// </remarks>
    [NativeOffset(0x1501)]
    [NativeName("m_bPreviouslyInBuyZone")]
    public bool PreviouslyInBuyZone { get; set; }

    /// <summary>
    ///     Gets or sets RagdollDamageBone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nRagdollDamageBone</c> at offset <c>0x1B04</c>.
    /// </remarks>
    [NativeOffset(0x1B04)]
    [NativeName("m_nRagdollDamageBone")]
    public int RagdollDamageBone { get; set; }

    /// <summary>
    ///     Gets or sets RagdollDamageForce.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vRagdollDamageForce</c> at offset <c>0x1B08</c>.
    /// </remarks>
    [NativeOffset(0x1B08)]
    [NativeName("m_vRagdollDamageForce")]
    public Vector RagdollDamageForce { get; set; }

    /// <summary>
    ///     Gets or sets RagdollDamageHeadshot.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bRagdollDamageHeadshot</c> at offset <c>0x1B54</c>.
    /// </remarks>
    [NativeOffset(0x1B54)]
    [NativeName("m_bRagdollDamageHeadshot")]
    public bool RagdollDamageHeadshot { get; set; }

    /// <summary>
    ///     Gets or sets RagdollDamageWeaponName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_szRagdollDamageWeaponName</c> at offset <c>0x1B14</c>.
    /// </remarks>
    [NativeOffset(0x1B14)]
    [NativeName("m_szRagdollDamageWeaponName")]
    public string RagdollDamageWeaponName { get; set; }

    /// <summary>
    ///     Gets or sets RagdollServerOrigin.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vRagdollServerOrigin</c> at offset <c>0x1B58</c>.
    /// </remarks>
    [NativeOffset(0x1B58)]
    [NativeName("m_vRagdollServerOrigin")]
    public VectorWS RagdollServerOrigin { get; set; }

    /// <summary>
    ///     Gets or sets ResumeZoom.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bResumeZoom</c> at offset <c>0x1C79</c>.
    /// </remarks>
    [NativeOffset(0x1C79)]
    [NativeName("m_bResumeZoom")]
    public bool ResumeZoom { get; set; }

    /// <summary>
    ///     Gets or sets RetakesHasDefuseKit.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bRetakesHasDefuseKit</c> at offset <c>0x1680</c>.
    /// </remarks>
    [NativeOffset(0x1680)]
    [NativeName("m_bRetakesHasDefuseKit")]
    public bool RetakesHasDefuseKit { get; set; }

    /// <summary>
    ///     Gets or sets RetakesMVPBoostExtraUtility.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_RetakesMVPBoostExtraUtility</c> at offset <c>0x1688</c>.
    /// </remarks>
    [NativeOffset(0x1688)]
    [NativeName("m_RetakesMVPBoostExtraUtility")]
    public LoadoutSlot RetakesMVPBoostExtraUtility { get; set; }

    /// <summary>
    ///     Gets or sets RetakesMVPBoostItem.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iRetakesMVPBoostItem</c> at offset <c>0x1684</c>.
    /// </remarks>
    [NativeOffset(0x1684)]
    [NativeName("m_iRetakesMVPBoostItem")]
    public int RetakesMVPBoostItem { get; set; }

    /// <summary>
    ///     Gets or sets RetakesMVPLastRound.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bRetakesMVPLastRound</c> at offset <c>0x1681</c>.
    /// </remarks>
    [NativeOffset(0x1681)]
    [NativeName("m_bRetakesMVPLastRound")]
    public bool RetakesMVPLastRound { get; set; }

    /// <summary>
    ///     Gets or sets RetakesOffering.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iRetakesOffering</c> at offset <c>0x1678</c>.
    /// </remarks>
    [NativeOffset(0x1678)]
    [NativeName("m_iRetakesOffering")]
    public int RetakesOffering { get; set; }

    /// <summary>
    ///     Gets or sets RetakesOfferingCard.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iRetakesOfferingCard</c> at offset <c>0x167C</c>.
    /// </remarks>
    [NativeOffset(0x167C)]
    [NativeName("m_iRetakesOfferingCard")]
    public int RetakesOfferingCard { get; set; }

    /// <summary>
    ///     Gets or sets RoundStartEquipmentValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_unRoundStartEquipmentValue</c> at offset <c>0x1CAA</c>.
    /// </remarks>
    [NativeOffset(0x1CAA)]
    [NativeName("m_unRoundStartEquipmentValue")]
    public ushort RoundStartEquipmentValue { get; set; }

    /// <summary>
    ///     Gets or sets ShotsFired.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iShotsFired</c> at offset <c>0x1C8C</c>.
    /// </remarks>
    [NativeOffset(0x1C8C)]
    [NativeName("m_iShotsFired")]
    public int ShotsFired { get; set; }

    /// <summary>
    ///     Gets or sets ShouldAutobuyDMWeapons.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bShouldAutobuyDMWeapons</c> at offset <c>0x3260</c>.
    /// </remarks>
    [NativeOffset(0x3260)]
    [NativeName("m_bShouldAutobuyDMWeapons")]
    public bool ShouldAutobuyDMWeapons { get; set; }

    /// <summary>
    ///     Gets or sets StashedGrenadeThrowPawnCenter.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecStashedGrenadeThrowPawnCenter</c> at offset <c>0x1D18</c>.
    /// </remarks>
    [NativeOffset(0x1D18)]
    [NativeName("m_vecStashedGrenadeThrowPawnCenter")]
    public VectorWS StashedGrenadeThrowPawnCenter { get; set; }

    /// <summary>
    ///     Gets or sets StashedGrenadeThrowPosition.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecStashedGrenadeThrowPosition</c> at offset <c>0x1D0C</c>.
    /// </remarks>
    [NativeOffset(0x1D0C)]
    [NativeName("m_vecStashedGrenadeThrowPosition")]
    public VectorWS StashedGrenadeThrowPosition { get; set; }

    /// <summary>
    ///     Gets or sets StashedShootAngles.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_angStashedShootAngles</c> at offset <c>0x1D00</c>.
    /// </remarks>
    [NativeOffset(0x1D00)]
    [NativeName("m_angStashedShootAngles")]
    public QAngle StashedShootAngles { get; set; }

    /// <summary>
    ///     Gets or sets StashedVelocity.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecStashedVelocity</c> at offset <c>0x1D24</c>.
    /// </remarks>
    [NativeOffset(0x1D24)]
    [NativeName("m_vecStashedVelocity")]
    public Vector StashedVelocity { get; set; }

    /// <summary>
    ///     Gets or sets SwitchedHandednessTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_fSwitchedHandednessTime</c> at offset <c>0x1B98</c>.
    /// </remarks>
    [NativeOffset(0x1B98)]
    [NativeName("m_fSwitchedHandednessTime")]
    public GameTime SwitchedHandednessTime { get; set; }

    /// <summary>
    ///     Gets or sets TargetItemEntIdx.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iTargetItemEntIdx</c> at offset <c>0x3448</c>.
    /// </remarks>
    [NativeOffset(0x3448)]
    [NativeName("m_iTargetItemEntIdx")]
    public int TargetItemEntIdx { get; set; }

    /// <summary>
    ///     Gets or sets TimeOfLastInjury.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flTimeOfLastInjury</c> at offset <c>0x150C</c>.
    /// </remarks>
    [NativeOffset(0x150C)]
    [NativeName("m_flTimeOfLastInjury")]
    public GameTime TimeOfLastInjury { get; set; }

    /// <summary>
    ///     Gets or sets VelocityModifier.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flVelocityModifier</c> at offset <c>0x1C94</c>.
    /// </remarks>
    [NativeOffset(0x1C94)]
    [NativeName("m_flVelocityModifier")]
    public float VelocityModifier { get; set; }

    /// <summary>
    ///     Gets or sets ViewmodelFOV.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flViewmodelFOV</c> at offset <c>0x1BA8</c>.
    /// </remarks>
    [NativeOffset(0x1BA8)]
    [NativeName("m_flViewmodelFOV")]
    public float ViewmodelFOV { get; set; }

    /// <summary>
    ///     Gets or sets ViewmodelOffsetX.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flViewmodelOffsetX</c> at offset <c>0x1B9C</c>.
    /// </remarks>
    [NativeOffset(0x1B9C)]
    [NativeName("m_flViewmodelOffsetX")]
    public float ViewmodelOffsetX { get; set; }

    /// <summary>
    ///     Gets or sets ViewmodelOffsetY.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flViewmodelOffsetY</c> at offset <c>0x1BA0</c>.
    /// </remarks>
    [NativeOffset(0x1BA0)]
    [NativeName("m_flViewmodelOffsetY")]
    public float ViewmodelOffsetY { get; set; }

    /// <summary>
    ///     Gets or sets ViewmodelOffsetZ.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flViewmodelOffsetZ</c> at offset <c>0x1BA4</c>.
    /// </remarks>
    [NativeOffset(0x1BA4)]
    [NativeName("m_flViewmodelOffsetZ")]
    public float ViewmodelOffsetZ { get; set; }

    /// <summary>
    ///     Gets or sets WaitForNoAttack.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bWaitForNoAttack</c> at offset <c>0x1C98</c>.
    /// </remarks>
    [NativeOffset(0x1C98)]
    [NativeName("m_bWaitForNoAttack")]
    public bool WaitForNoAttack { get; set; }

    /// <summary>
    ///     Gets or sets WeaponHash.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_unWeaponHash</c> at offset <c>0x14FC</c>.
    /// </remarks>
    [NativeOffset(0x14FC)]
    [NativeName("m_unWeaponHash")]
    public uint WeaponHash { get; set; }

    /// <summary>
    ///     Gets or sets WhichBombZone.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nWhichBombZone</c> at offset <c>0x1C88</c>.
    /// </remarks>
    [NativeOffset(0x1C88)]
    [NativeName("m_nWhichBombZone")]
    public int WhichBombZone { get; set; }
}
