// <auto-generated/>
// CS2OpenSchema — Client/C_EnvDetailController
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     C_EnvDetailController.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 1544 bytes, align 8.
/// </remarks>
[NativeSize(1544)]
public partial class C_EnvDetailController : C_BaseEntity
{
    /// <summary>
    ///     Gets or sets FadeEndDist.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFadeEndDist</c> at offset <c>0x604</c>.
    /// </remarks>
    [NativeOffset(0x604)]
    [NativeName("m_flFadeEndDist")]
    public float FadeEndDist { get; set; }

    /// <summary>
    ///     Gets or sets FadeStartDist.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flFadeStartDist</c> at offset <c>0x600</c>.
    /// </remarks>
    [NativeOffset(0x600)]
    [NativeName("m_flFadeStartDist")]
    public float FadeStartDist { get; set; }
}
