// <auto-generated/>
// CS2OpenSchema — Client/C_PointClientUIDialog
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     C_PointClientUIDialog.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 4064 bytes.
/// </remarks>
[NativeSize(4064)]
public partial class C_PointClientUIDialog : C_BaseClientUIEntity
{
    /// <summary>
    ///     Gets or sets Activator.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hActivator</c> at offset <c>0xFD8</c>.
    /// </remarks>
    [NativeOffset(0xFD8)]
    [NativeName("m_hActivator")]
    public CHandle<C_BaseEntity> Activator { get; set; }

    /// <summary>
    ///     Gets or sets StartEnabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bStartEnabled</c> at offset <c>0xFDC</c>.
    /// </remarks>
    [NativeOffset(0xFDC)]
    [NativeName("m_bStartEnabled")]
    public bool StartEnabled { get; set; }
}
