// <auto-generated/>
// CS2OpenSchema — Client/C_ShatterGlassShardPhysics
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Common;

#endregion

namespace CS2OpenSchema.Client;

/// <summary>
///     C_ShatterGlassShardPhysics.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 4152 bytes, align 8.
/// </remarks>
[NativeSize(4152)]
public partial class C_ShatterGlassShardPhysics : C_BaseModelEntity
{
    /// <summary>
    ///     Gets or sets ShardDesc.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ShardDesc</c> at offset <c>0xFB8</c>.
    /// </remarks>
    [NativeOffset(0xFB8)]
    [NativeName("m_ShardDesc")]
    [NativeMetadata("MNotSaved", "")]
    public ShardModelDesc ShardDesc { get; set; }
}
