// <auto-generated/>
// CS2OpenSchema — Client/CBodyComponentSkeletonInstance
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CBodyComponentSkeletonInstance.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 1248 bytes.
/// </remarks>
[NativeSize(1248)]
public partial class CBodyComponentSkeletonInstance : CBodyComponent
{
    /// <summary>
    ///     Gets or sets SkeletonInstance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_skeletonInstance</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_skeletonInstance")]
    public CSkeletonInstance SkeletonInstance { get; set; }
}
