// <auto-generated/>
// CS2OpenSchema — Client/CBodyComponentPoint
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 25000182 — 2026-08-28T20:16:08Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CBodyComponentPoint.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 432 bytes.
/// </remarks>
[NativeSize(432)]
[NativeMetadata("MGetKV3ClassDefaults", "")]
public partial class CBodyComponentPoint : CBodyComponent
{
    /// <summary>
    ///     Gets or sets SceneNode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sceneNode</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_sceneNode")]
    public CGameSceneNode SceneNode { get; set; }
}
