// <auto-generated/>
// CS2OpenSchema — Client/CInfoDynamicShadowHint
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CInfoDynamicShadowHint.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 1560 bytes, align 8.
/// </remarks>
[NativeSize(1560)]
public partial class CInfoDynamicShadowHint : C_PointEntity
{
    /// <summary>
    ///     Gets or sets Disabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bDisabled</c> at offset <c>0x600</c>.
    /// </remarks>
    [NativeOffset(0x600)]
    [NativeName("m_bDisabled")]
    public bool Disabled { get; set; }

    /// <summary>
    ///     Gets or sets Importance.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nImportance</c> at offset <c>0x608</c>.
    /// </remarks>
    [NativeOffset(0x608)]
    [NativeName("m_nImportance")]
    public int Importance { get; set; }

    /// <summary>
    ///     Gets or sets Light.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hLight</c> at offset <c>0x610</c>.
    /// </remarks>
    [NativeOffset(0x610)]
    [NativeName("m_hLight")]
    public CHandle__C_BaseEntity__ Light { get; set; }

    /// <summary>
    ///     Gets or sets LightChoice.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nLightChoice</c> at offset <c>0x60C</c>.
    /// </remarks>
    [NativeOffset(0x60C)]
    [NativeName("m_nLightChoice")]
    public int LightChoice { get; set; }

    /// <summary>
    ///     Gets or sets Range.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flRange</c> at offset <c>0x604</c>.
    /// </remarks>
    [NativeOffset(0x604)]
    [NativeName("m_flRange")]
    public float Range { get; set; }
}
