// <auto-generated/>
// CS2OpenSchema — Client/CPlayerItemServices
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Server;

#endregion

namespace CS2OpenSchema.Client;

/// <summary>
///     CPlayer_ItemServices.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 72 bytes.
/// </remarks>
[NativeSize(72)]
[NativeName("CPlayer_ItemServices")]
public partial class CPlayerItemServices : CPlayerPawnComponent
{
}
