// <auto-generated/>
// CS2OpenSchema — Client/CPointOffScreenIndicatorUi
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CPointOffScreenIndicatorUi.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 4624 bytes.
/// </remarks>
[NativeSize(4624)]
public partial class CPointOffScreenIndicatorUi : C_PointClientUIWorldPanel
{
    /// <summary>
    ///     Gets or sets BeenEnabled.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bBeenEnabled</c> at offset <c>0x1200</c>.
    /// </remarks>
    [NativeOffset(0x1200)]
    [NativeName("m_bBeenEnabled")]
    [NativeMetadata("MNotSaved")]
    public bool BeenEnabled { get; set; }

    /// <summary>
    ///     Gets or sets Hide.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bHide</c> at offset <c>0x1201</c>.
    /// </remarks>
    [NativeOffset(0x1201)]
    [NativeName("m_bHide")]
    [NativeMetadata("MNotSaved")]
    public bool Hide { get; set; }

    /// <summary>
    ///     Gets or sets SeenTargetTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flSeenTargetTime</c> at offset <c>0x1204</c>.
    /// </remarks>
    [NativeOffset(0x1204)]
    [NativeName("m_flSeenTargetTime")]
    [NativeMetadata("MNotSaved")]
    public float SeenTargetTime { get; set; }

    /// <summary>
    ///     Gets or sets TargetPanel.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pTargetPanel</c> at offset <c>0x1208</c>.
    /// </remarks>
    [NativeOffset(0x1208)]
    [NativeName("m_pTargetPanel")]
    [NativeMetadata("MNotSaved")]
    public C_PointClientUIWorldPanel? TargetPanel { get; set; }
}
