// <auto-generated/>
// CS2OpenSchema — Client/CSWeaponSilencerType
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     CSWeaponSilencerType.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32-bit.
/// </remarks>
public enum CSWeaponSilencerType : uint
{
    /// <summary>
    ///     WeaponsilencerNone.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>WEAPONSILENCER_NONE</c>.
    /// </remarks>
    [NativeName("WEAPONSILENCER_NONE")]
    WeaponsilencerNone = 0,

    /// <summary>
    ///     WeaponsilencerDetachable.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>WEAPONSILENCER_DETACHABLE</c>.
    /// </remarks>
    [NativeName("WEAPONSILENCER_DETACHABLE")]
    WeaponsilencerDetachable = 1,

    /// <summary>
    ///     WeaponsilencerIntegrated.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>WEAPONSILENCER_INTEGRATED</c>.
    /// </remarks>
    [NativeName("WEAPONSILENCER_INTEGRATED")]
    WeaponsilencerIntegrated = 2
}
