// <auto-generated/>
// CS2OpenSchema — Client/EventClientOutput
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     EventClientOutput_t.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 56 bytes.
/// </remarks>
[NativeSize(56)]
[NativeName("EventClientOutput_t")]
public partial class EventClientOutput
{
    /// <summary>
    ///     Gets or sets LoopState.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_LoopState</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_LoopState")]
    public EngineLoopState LoopState { get; set; }

    /// <summary>
    ///     Gets or sets RealTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flRealTime</c> at offset <c>0x2C</c>.
    /// </remarks>
    [NativeOffset(0x2C)]
    [NativeName("m_flRealTime")]
    public float RealTime { get; set; }

    /// <summary>
    ///     Gets or sets RenderFrameTimeUnbounded.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flRenderFrameTimeUnbounded</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_flRenderFrameTimeUnbounded")]
    public float RenderFrameTimeUnbounded { get; set; }

    /// <summary>
    ///     Gets or sets RenderOnly.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bRenderOnly</c> at offset <c>0x34</c>.
    /// </remarks>
    [NativeOffset(0x34)]
    [NativeName("m_bRenderOnly")]
    public bool RenderOnly { get; set; }

    /// <summary>
    ///     Gets or sets RenderTime.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flRenderTime</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_flRenderTime")]
    public float RenderTime { get; set; }
}
