// <auto-generated/>
// CS2OpenSchema — Client/VoteCreateFailed
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10673343 — May 20 2026 15:25:57

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Client;

/// <summary>
///     vote_create_failed_t.
/// </summary>
/// <remarks>
///     Module: <c>client</c> — 32-bit.
/// </remarks>
[NativeName("vote_create_failed_t")]
public enum VoteCreateFailed : uint
{
    /// <summary>
    ///     VoteFailedGeneric.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_GENERIC</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_GENERIC")]
    VoteFailedGeneric = 0,

    /// <summary>
    ///     VoteFailedTransitioningPlayers.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TRANSITIONING_PLAYERS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TRANSITIONING_PLAYERS")]
    VoteFailedTransitioningPlayers = 1,

    /// <summary>
    ///     VoteFailedRateExceeded.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_RATE_EXCEEDED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_RATE_EXCEEDED")]
    VoteFailedRateExceeded = 2,

    /// <summary>
    ///     VoteFailedYesMustExceedNo.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_YES_MUST_EXCEED_NO</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_YES_MUST_EXCEED_NO")]
    VoteFailedYesMustExceedNo = 3,

    /// <summary>
    ///     VoteFailedQuorumFailure.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_QUORUM_FAILURE</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_QUORUM_FAILURE")]
    VoteFailedQuorumFailure = 4,

    /// <summary>
    ///     VoteFailedIssueDisabled.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_ISSUE_DISABLED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_ISSUE_DISABLED")]
    VoteFailedIssueDisabled = 5,

    /// <summary>
    ///     VoteFailedMapNotFound.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_MAP_NOT_FOUND</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_MAP_NOT_FOUND")]
    VoteFailedMapNotFound = 6,

    /// <summary>
    ///     VoteFailedMapNameRequired.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_MAP_NAME_REQUIRED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_MAP_NAME_REQUIRED")]
    VoteFailedMapNameRequired = 7,

    /// <summary>
    ///     VoteFailedFailedRecently.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENTLY</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENTLY")]
    VoteFailedFailedRecently = 8,

    /// <summary>
    ///     VoteFailedTeamCantCall.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TEAM_CANT_CALL</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TEAM_CANT_CALL")]
    VoteFailedTeamCantCall = 9,

    /// <summary>
    ///     VoteFailedWaitingforplayers.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_WAITINGFORPLAYERS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_WAITINGFORPLAYERS")]
    VoteFailedWaitingforplayers = 10,

    /// <summary>
    ///     VoteFailedPlayernotfound.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_PLAYERNOTFOUND</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_PLAYERNOTFOUND")]
    VoteFailedPlayernotfound = 11,

    /// <summary>
    ///     VoteFailedCannotKickAdmin.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_CANNOT_KICK_ADMIN</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_CANNOT_KICK_ADMIN")]
    VoteFailedCannotKickAdmin = 12,

    /// <summary>
    ///     VoteFailedScrambleInProgress.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_SCRAMBLE_IN_PROGRESS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_SCRAMBLE_IN_PROGRESS")]
    VoteFailedScrambleInProgress = 13,

    /// <summary>
    ///     VoteFailedSpectator.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_SPECTATOR</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_SPECTATOR")]
    VoteFailedSpectator = 14,

    /// <summary>
    ///     VoteFailedFailedRecentKick.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENT_KICK</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENT_KICK")]
    VoteFailedFailedRecentKick = 15,

    /// <summary>
    ///     VoteFailedFailedRecentChangemap.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENT_CHANGEMAP</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENT_CHANGEMAP")]
    VoteFailedFailedRecentChangemap = 16,

    /// <summary>
    ///     VoteFailedFailedRecentSwapteams.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENT_SWAPTEAMS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENT_SWAPTEAMS")]
    VoteFailedFailedRecentSwapteams = 17,

    /// <summary>
    ///     VoteFailedFailedRecentScrambleteams.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENT_SCRAMBLETEAMS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENT_SCRAMBLETEAMS")]
    VoteFailedFailedRecentScrambleteams = 18,

    /// <summary>
    ///     VoteFailedFailedRecentRestart.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_FAILED_RECENT_RESTART</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_FAILED_RECENT_RESTART")]
    VoteFailedFailedRecentRestart = 19,

    /// <summary>
    ///     VoteFailedSwapInProgress.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_SWAP_IN_PROGRESS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_SWAP_IN_PROGRESS")]
    VoteFailedSwapInProgress = 20,

    /// <summary>
    ///     VoteFailedDisabled.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_DISABLED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_DISABLED")]
    VoteFailedDisabled = 21,

    /// <summary>
    ///     VoteFailedNextlevelSet.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_NEXTLEVEL_SET</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_NEXTLEVEL_SET")]
    VoteFailedNextlevelSet = 22,

    /// <summary>
    ///     VoteFailedTooEarlySurrender.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TOO_EARLY_SURRENDER</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TOO_EARLY_SURRENDER")]
    VoteFailedTooEarlySurrender = 23,

    /// <summary>
    ///     VoteFailedMatchPaused.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_MATCH_PAUSED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_MATCH_PAUSED")]
    VoteFailedMatchPaused = 24,

    /// <summary>
    ///     VoteFailedMatchNotPaused.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_MATCH_NOT_PAUSED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_MATCH_NOT_PAUSED")]
    VoteFailedMatchNotPaused = 25,

    /// <summary>
    ///     VoteFailedNotInWarmup.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_NOT_IN_WARMUP</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_NOT_IN_WARMUP")]
    VoteFailedNotInWarmup = 26,

    /// <summary>
    ///     VoteFailedNot10Players.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_NOT_10_PLAYERS</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_NOT_10_PLAYERS")]
    VoteFailedNot10Players = 27,

    /// <summary>
    ///     VoteFailedTimeoutActive.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TIMEOUT_ACTIVE</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TIMEOUT_ACTIVE")]
    VoteFailedTimeoutActive = 28,

    /// <summary>
    ///     VoteFailedTimeoutInactive.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TIMEOUT_INACTIVE</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TIMEOUT_INACTIVE")]
    VoteFailedTimeoutInactive = 29,

    /// <summary>
    ///     VoteFailedTimeoutExhausted.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_TIMEOUT_EXHAUSTED</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_TIMEOUT_EXHAUSTED")]
    VoteFailedTimeoutExhausted = 30,

    /// <summary>
    ///     VoteFailedCantRoundEnd.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_CANT_ROUND_END</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_CANT_ROUND_END")]
    VoteFailedCantRoundEnd = 31,

    /// <summary>
    ///     VoteFailedRematch.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_REMATCH</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_REMATCH")]
    VoteFailedRematch = 32,

    /// <summary>
    ///     VoteFailedContinue.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_CONTINUE</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_CONTINUE")]
    VoteFailedContinue = 33,

    /// <summary>
    ///     VoteFailedMax.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>VOTE_FAILED_MAX</c>.
    /// </remarks>
    [NativeName("VOTE_FAILED_MAX")]
    VoteFailedMax = 34
}
