// <auto-generated/>
// CS2OpenSchema — Soundsystem/CSndBeatPattern
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Soundsystem;

/// <summary>
///     CSndBeatPattern.
/// </summary>
/// <remarks>
///     Module: <c>soundsystem</c> — 152 bytes, align 8.
/// </remarks>
[NativeSize(152)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_name\": \"\",\n\t\"m_launchSyncType\": \"eSndBeatLaunchSyncTypeReset\",\n\t\"m_flSyncPriority\": 0.000000,\n\t\"m_timeSignature\":\n\t{\n\t\t\"nNumerator\": 4,\n\t\t\"nDenominator\": 4\n\t},\n\t\"m_flLength\": 4.000000,\n\t\"m_bLooping\": false,\n\t\"m_launchSyncEventType\": \"eSndBeatEventTypeBeat\",\n\t\"m_flSyncBeatMult\": 1.000000,\n\t\"m_playEventType\": \"eSndBeatEventTypeBeat\",\n\t\"m_flPlayBeatMult\": 1.000000,\n\t\"m_keyType\": \"eSndBeatPatternTypeNone\",\n\t\"m_vecPatternKeys\":\n\t[\n\t],\n\t\"m_vecPatternFloats\":\n\t[\n\t],\n\t\"m_vecPatternSndEvts\":\n\t[\n\t],\n\t\"m_vecPatternMidi\":\n\t[\n\t]\n}")]
[NativeMetadata("MPropertyArrayElementNameKey", "m_name")]
[NativeMetadata("MVDataAnonymousNode", "")]
[NativeMetadata("MVDataOutlinerNameExpr", "m_name")]
public partial class CSndBeatPattern
{
    /// <summary>
    ///     Key Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_keyType</c> at offset <c>0x34</c>.
    /// </remarks>
    [NativeOffset(0x34)]
    [NativeName("m_keyType")]
    [NativeMetadata("MPropertyFriendlyName", "Key Type")]
    public SndBeatKeyType KeyType { get; set; }

    /// <summary>
    ///     Launch Track Event Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_launchSyncEventType</c> at offset <c>0x24</c>.
    /// </remarks>
    [NativeOffset(0x24)]
    [NativeName("m_launchSyncEventType")]
    [NativeMetadata("MPropertyFriendlyName", "Launch Track Event Type")]
    [NativeMetadata("MPropertyGroupName", "Launch Track")]
    public SndBeatEventType LaunchSyncEventType { get; set; }

    /// <summary>
    ///     Pattern Launch Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_launchSyncType</c> at offset <c>0xC</c>.
    /// </remarks>
    [NativeOffset(0xC)]
    [NativeName("m_launchSyncType")]
    [NativeMetadata("MPropertyFriendlyName", "Pattern Launch Type")]
    public SndBeatLaunchSyncType LaunchSyncType { get; set; }

    /// <summary>
    ///     Length (beats).
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flLength</c> at offset <c>0x1C</c>.
    /// </remarks>
    [NativeOffset(0x1C)]
    [NativeName("m_flLength")]
    [NativeMetadata("MPropertyFriendlyName", "Length (beats)")]
    public float Length { get; set; }

    /// <summary>
    ///     Looping.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bLooping</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_bLooping")]
    [NativeMetadata("MPropertyFriendlyName", "Looping")]
    public bool Looping { get; set; }

    /// <summary>
    ///     Pattern Name.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_name</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_name")]
    [NativeMetadata("MPropertyFriendlyName", "Pattern Name")]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or sets PatternFloats.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecPatternFloats</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_vecPatternFloats")]
    [NativeMetadata("MPropertySuppressExpr", "m_keyType != eSndBeatPatternTypeKeyedFloats")]
    public CUtlVector__SndBeatEventKeyedFloats_t__ PatternFloats { get; set; }

    /// <summary>
    ///     Gets or sets PatternKeys.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecPatternKeys</c> at offset <c>0x38</c>.
    /// </remarks>
    [NativeOffset(0x38)]
    [NativeName("m_vecPatternKeys")]
    [NativeMetadata("MPropertySuppressExpr", "m_keyType != eSndBeatPatternTypeKeys")]
    public CUtlVector__SndBeatEventKeys_t__ PatternKeys { get; set; }

    /// <summary>
    ///     Gets or sets PatternMidi.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecPatternMidi</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_vecPatternMidi")]
    [NativeMetadata("MPropertySuppressExpr", "m_keyType != eSndBeatPatternTypeKeyedMidi")]
    public CUtlVector__SndBeatEventKeyedMidiNotes_t__ PatternMidi { get; set; }

    /// <summary>
    ///     Gets or sets PatternSndEvts.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecPatternSndEvts</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_vecPatternSndEvts")]
    [NativeMetadata("MPropertySuppressExpr", "m_keyType != eSndBeatPatternTypeKeyedSndEvts")]
    public CUtlVector__SndBeatEventKeyedSndEvts_t__ PatternSndEvts { get; set; }

    /// <summary>
    ///     Play Track Beat/Bar/Phrase/Length Multiplier.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flPlayBeatMult</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_flPlayBeatMult")]
    [NativeMetadata("MPropertyFriendlyName", "Play Track Beat/Bar/Phrase/Length Multiplier")]
    [NativeMetadata("MPropertyGroupName", "Playback Track")]
    public float PlayBeatMult { get; set; }

    /// <summary>
    ///     Play Track Event Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_playEventType</c> at offset <c>0x2C</c>.
    /// </remarks>
    [NativeOffset(0x2C)]
    [NativeName("m_playEventType")]
    [NativeMetadata("MPropertyFriendlyName", "Play Track Event Type")]
    [NativeMetadata("MPropertyGroupName", "Playback Track")]
    public SndBeatEventType PlayEventType { get; set; }

    /// <summary>
    ///     Launch Track Beat/Bar/Phrase/Length Multiplier.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flSyncBeatMult</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_flSyncBeatMult")]
    [NativeMetadata("MPropertyFriendlyName", "Launch Track Beat/Bar/Phrase/Length Multiplier")]
    [NativeMetadata("MPropertyGroupName", "Launch Track")]
    [NativeMetadata("MPropertySuppressExpr", "m_launchSyncEventType == eSndBeatPatternTypeKeys")]
    public float SyncBeatMult { get; set; }

    /// <summary>
    ///     Pattern Launch Priority.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flSyncPriority</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_flSyncPriority")]
    [NativeMetadata("MPropertyFriendlyName", "Pattern Launch Priority")]
    public float SyncPriority { get; set; }

    /// <summary>
    ///     Time Signature.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_timeSignature</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_timeSignature")]
    [NativeMetadata("MPropertyFriendlyName", "Time Signature")]
    public SndBeatTimeSignature TimeSignature { get; set; }
}
