// <auto-generated/>
// CS2OpenSchema — Toolutils2/CAssetWarning
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10677034 — May 21 2026 17:11:59

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Toolutils2;

/// <summary>
///     CAssetWarning.
/// </summary>
/// <remarks>
///     Module: <c>toolutils2</c> — 64 bytes.
/// </remarks>
[NativeSize(64)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_Title\": \"\",\n\t\"m_Message\": \"\",\n\t\"m_Checks\":\n\t[\n\t]\n}")]
public partial class CAssetWarning
{
    /// <summary>
    ///     Gets or sets Checks.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Checks</c> at offset <c>0x28</c>.
    /// </remarks>
    [NativeOffset(0x28)]
    [NativeName("m_Checks")]
    public CAssetWarningCheck[] Checks { get; set; }

    /// <summary>
    ///     Gets or sets Message.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Message</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_Message")]
    public string Message { get; set; }

    /// <summary>
    ///     Gets or sets Title.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Title</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_Title")]
    public string Title { get; set; }
}
