// <auto-generated/>
// CS2OpenSchema — Toolutils2/CVMMDAssetTypeInfo
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Toolutils2;

/// <summary>
///     CVMMDAssetTypeInfo.
/// </summary>
/// <remarks>
///     Module: <c>toolutils2</c> — 256 bytes, align 8.
/// </remarks>
[NativeSize(256)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CVMMDAssetTypeInfo\",\n\t\"m_FriendlyName\": \"\",\n\t\"m_Ext\": \"\",\n\t\"m_IconLg\": \"game:tools/images/assettypes/generic_lg.png\",\n\t\"m_IconSm\": \"game:tools/images/assettypes/generic_sm.png\",\n\t\"m_SuppressSubstrings\":\n\t[\n\t],\n\t\"m_AdditionalExtensions\":\n\t[\n\t],\n\t\"m_EngineCommands\":\n\t[\n\t],\n\t\"m_LimitToMods\":\n\t[\n\t],\n\t\"m_ExcludeFromMods\":\n\t[\n\t],\n\t\"m_HideForRetailMods\":\n\t[\n\t],\n\t\"m_PreviewThumbnailOverlayIcon\": \"\",\n\t\"m_bErrorOnUnrecognizedOutboundRefs\": false,\n\t\"m_UnrecognizedOutboundRefsErrorTypeExceptions\":\n\t[\n\t],\n\t\"m_bHideTypeByDefault\": false,\n\t\"m_bCannotBeShown\": false,\n\t\"m_bIsNontrivialChildAssetType\": false,\n\t\"m_bSuppressFullFingerprintCalculation\": false,\n\t\"m_bIgnoreCompiledState\": false,\n\t\"m_bContentFileIsText\": false,\n\t\"m_bPrefersLivePreview\": false,\n\t\"m_bPresentInGameTree\": false,\n\t\"m_bShouldCompileErrorFallbackToDisk\": false,\n\t\"m_nAssetTypeVersion\": 0,\n\t\"m_Test_InjectSearchable\": \"\"\n}")]
public partial class CVMMDAssetTypeInfo : CSimpleAssetTypeInfo
{
}
