// <auto-generated/>
// CS2OpenSchema — PulseRuntimeLib/CPulseCellTimeline
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.PulseRuntimeLib;

/// <summary>
///     CPulseCell_Timeline.
/// </summary>
/// <remarks>
///     Module: <c>pulse_runtime_lib</c> — 320 bytes, align 8.
/// </remarks>
[NativeSize(320)]
[NativeName("CPulseCell_Timeline")]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"_class\": \"CPulseCell_Timeline\",\n\t\"m_nEditorNodeID\": -1,\n\t\"m_BaseFlow_OnAfterCancel\":\n\t{\n\t\t\"m_SourceOutflowName\": \"\",\n\t\t\"m_nDestChunk\": -1,\n\t\t\"m_nInstruction\": -1\n\t},\n\t\"m_BaseFlow_WhileActive\":\n\t{\n\t\t\"m_SourceOutflowName\": \"\",\n\t\t\"m_nDestChunk\": -1,\n\t\t\"m_nInstruction\": -1\n\t},\n\t\"m_TimelineEvents\":\n\t[\n\t],\n\t\"m_bWaitForChildOutflows\": true,\n\t\"m_OnFinished\":\n\t{\n\t\t\"m_SourceOutflowName\": \"\",\n\t\t\"m_nDestChunk\": -1,\n\t\t\"m_nInstruction\": -1\n\t}\n}")]
public partial class CPulseCellTimeline : CPulseCellBaseYieldingInflow
{
    /// <summary>
    ///     Gets or sets OnFinished.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OnFinished</c> at offset <c>0xF8</c>.
    /// </remarks>
    [NativeOffset(0xF8)]
    [NativeName("m_OnFinished")]
    public CPulseResumePoint OnFinished { get; set; }

    /// <summary>
    ///     Gets or sets TimelineEvents.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_TimelineEvents</c> at offset <c>0xD8</c>.
    /// </remarks>
    [NativeOffset(0xD8)]
    [NativeName("m_TimelineEvents")]
    public CPulseCellTimelineTimelineEvent[] TimelineEvents { get; set; }

    /// <summary>
    ///     Gets or sets WaitForChildOutflows.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bWaitForChildOutflows</c> at offset <c>0xF0</c>.
    /// </remarks>
    [NativeOffset(0xF0)]
    [NativeName("m_bWaitForChildOutflows")]
    public bool WaitForChildOutflows { get; set; }
}
