// <auto-generated/>
// CS2OpenSchema — PulseRuntimeLib/PulseRegisterMap
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.PulseRuntimeLib;

/// <summary>
///     PulseRegisterMap_t.
/// </summary>
/// <remarks>
///     Module: <c>pulse_runtime_lib</c> — 48 bytes.
/// </remarks>
[NativeSize(48)]
[NativeName("PulseRegisterMap_t")]
public partial class PulseRegisterMap
{
    /// <summary>
    ///     Gets or sets InParams.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Inparams</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_Inparams")]
    public string InParams { get; set; }

    /// <summary>
    ///     Gets or sets InParamsWhichCanBeMoved.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_InparamsWhichCanBeMoved</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_InparamsWhichCanBeMoved")]
    public string[]? InParamsWhichCanBeMoved { get; set; }

    /// <summary>
    ///     Gets or sets OutParams.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Outparams</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_Outparams")]
    public string OutParams { get; set; }
}
