// <auto-generated/>
// CS2OpenSchema — Server/CFuncMoverFollowConstraint
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CFuncMover::FollowConstraint_t
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 32-bit — flags.
/// </remarks>
[Flags]
[NativeName("CFuncMover::FollowConstraint_t")]
public enum CFuncMoverFollowConstraint : uint
{
    /// <summary>
    ///     FollowConstraintDistance
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FOLLOW_CONSTRAINT_DISTANCE</c>
    /// </remarks>
    [NativeName("FOLLOW_CONSTRAINT_DISTANCE")]
    FollowConstraintDistance = 0,

    /// <summary>
    ///     FollowConstraintSpring
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FOLLOW_CONSTRAINT_SPRING</c>
    /// </remarks>
    [NativeName("FOLLOW_CONSTRAINT_SPRING")]
    FollowConstraintSpring = 1,

    /// <summary>
    ///     FollowConstraintRatio
    /// </summary>
    /// <remarks>
    ///     Native name: <c>FOLLOW_CONSTRAINT_RATIO</c>
    /// </remarks>
    [NativeName("FOLLOW_CONSTRAINT_RATIO")]
    FollowConstraintRatio = 2
}
