// <auto-generated/>
// CS2OpenSchema — Server/CPathMover
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CPathMover
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 1568 bytes, align 16.
/// </remarks>
[NativeSize(1568)]
public partial class CPathMover : CPathWithDynamicNodes
{
    /// <summary>
    ///     Gets or sets MoverSpawner.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hMoverSpawner</c> at offset <c>0x608</c>.
    /// </remarks>
    [NativeOffset(0x608)]
    [NativeName("m_hMoverSpawner")]
    public CPathMoverEntitySpawner? MoverSpawner { get; set; }

    /// <summary>
    ///     Gets or sets MoverSpawnerName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_iszMoverSpawnerName</c> at offset <c>0x610</c>.
    /// </remarks>
    [NativeOffset(0x610)]
    [NativeName("m_iszMoverSpawnerName")]
    public string MoverSpawnerName { get; set; }

    /// <summary>
    ///     Gets or sets Movers.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecMovers</c> at offset <c>0x5F0</c>.
    /// </remarks>
    [NativeOffset(0x5F0)]
    [NativeName("m_vecMovers")]
    public CFuncMover?[] Movers { get; set; }
}
