// <auto-generated/>
// CS2OpenSchema — Server/CPulseCellSoundEventStart
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Common;

#endregion

namespace CS2OpenSchema.Server;

/// <summary>
///     CPulseCell_SoundEventStart
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 80 bytes, align 8.
/// </remarks>
[NativeSize(80)]
[NativeName("CPulseCell_SoundEventStart")]
public partial class CPulseCellSoundEventStart : CPulseCellBaseFlow
{
    /// <summary>
    ///     Gets or sets Type.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Type</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_Type")]
    public SoundEventStartType Type { get; set; }
}
