// <auto-generated/>
// CS2OpenSchema — Server/CWeaponCZ75a
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     CWeaponCZ75a
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 4192 bytes, align 16.
/// </remarks>
[NativeSize(4192)]
public partial class CWeaponCZ75a : CCSWeaponBaseGun
{
    /// <summary>
    ///     Gets or sets MagazineRemoved.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bMagazineRemoved</c> at offset <c>0x1050</c>.
    /// </remarks>
    [NativeOffset(0x1050)]
    [NativeName("m_bMagazineRemoved")]
    public bool MagazineRemoved { get; set; }
}
