// <auto-generated/>
// CS2OpenSchema — Server/Modifiedconvars
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Server;

/// <summary>
///     modifiedconvars_t
/// </summary>
/// <remarks>
///     Module: <c>server</c> — 384 bytes, align 1.
/// </remarks>
[NativeSize(384)]
[NativeName("modifiedconvars_t")]
public partial class Modifiedconvars
{
    /// <summary>
    ///     Gets or sets Convar.
    /// </summary>
    /// <remarks>
    ///     Native field <c>pszConvar</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("pszConvar")]
    public string Convar { get; set; }

    /// <summary>
    ///     Gets or sets CurrentValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>pszCurrentValue</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("pszCurrentValue")]
    public string CurrentValue { get; set; }

    /// <summary>
    ///     Gets or sets OrgValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>pszOrgValue</c> at offset <c>0x100</c>.
    /// </remarks>
    [NativeOffset(0x100)]
    [NativeName("pszOrgValue")]
    public string OrgValue { get; set; }
}
