// <auto-generated/>
// CS2OpenSchema — SoundsystemVoicecontainers/CSoundContainerReferenceArray
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Resourcesystem;

#endregion

namespace CS2OpenSchema.SoundsystemVoicecontainers;

/// <summary>
///     CSoundContainerReferenceArray
/// </summary>
/// <remarks>
///     Module: <c>soundsystem_voicecontainers</c> — 56 bytes, align 8.
/// </remarks>
[NativeSize(56)]
public partial class CSoundContainerReferenceArray
{
    /// <summary>
    ///     Gets or sets PSounds.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pSounds</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_pSounds")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_bUseReference == 1\"")]
    [NativeMetadata("MPropertyFriendlyName", "\"Vsnd Container\"")]
    public CVoiceContainerBase?[] PSounds { get; set; }

    /// <summary>
    ///     Gets or sets Sounds.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_sounds</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_sounds")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_bUseReference == 0\"")]
    [NativeMetadata("MPropertyFriendlyName", "\"Vsnd File\"")]
    public InfoForResourceTypeCVoiceContainerBase?[] Sounds { get; set; }

    /// <summary>
    ///     Gets or sets UseReference.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bUseReference</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_bUseReference")]
    [NativeMetadata("MPropertyFriendlyName", "\"Use Vsnd File\"")]
    public bool UseReference { get; set; }
}
