// <auto-generated/>
// CS2OpenSchema — Schemasystem/CSchemaSystemInternalRegistration
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Schemasystem;

/// <summary>
///     CSchemaSystemInternalRegistration.
/// </summary>
/// <remarks>
///     Module: <c>schemasystem</c> — 384 bytes.
/// </remarks>
[NativeSize(384)]
public partial class CSchemaSystemInternalRegistration
{
    /// <summary>
    ///     Gets or sets CTransform.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_CTransform</c> at offset <c>0x100</c>.
    /// </remarks>
    [NativeOffset(0x100)]
    [NativeName("m_CTransform")]
    public CTransform CTransform { get; set; }

    /// <summary>
    ///     Gets or sets CUtlBinaryBlock.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_CUtlBinaryBlock</c> at offset <c>0x128</c>.
    /// </remarks>
    [NativeOffset(0x128)]
    [NativeName("m_CUtlBinaryBlock")]
    public byte[] CUtlBinaryBlock { get; set; }

    /// <summary>
    ///     Gets or sets CUtlString.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_CUtlString</c> at offset <c>0x138</c>.
    /// </remarks>
    [NativeOffset(0x138)]
    [NativeName("m_CUtlString")]
    public string CUtlString { get; set; }

    /// <summary>
    ///     Gets or sets CUtlSymbol.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_CUtlSymbol</c> at offset <c>0x140</c>.
    /// </remarks>
    [NativeOffset(0x140)]
    [NativeName("m_CUtlSymbol")]
    public string CUtlSymbol { get; set; }

    /// <summary>
    ///     Gets or sets Color.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Color</c> at offset <c>0xE0</c>.
    /// </remarks>
    [NativeOffset(0xE0)]
    [NativeName("m_Color")]
    public Color Color { get; set; }

    /// <summary>
    ///     Gets or sets DegreeEuler.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_DegreeEuler</c> at offset <c>0x64</c>.
    /// </remarks>
    [NativeOffset(0x64)]
    [NativeName("m_DegreeEuler")]
    public DegreeEuler DegreeEuler { get; set; }

    /// <summary>
    ///     Gets or sets KV3.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_KV3</c> at offset <c>0x168</c>.
    /// </remarks>
    [NativeOffset(0x168)]
    [NativeName("m_KV3")]
    public string KV3 { get; set; }

    /// <summary>
    ///     Gets or sets KeyValues.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pKeyValues</c> at offset <c>0x120</c>.
    /// </remarks>
    [NativeOffset(0x120)]
    [NativeName("m_pKeyValues")]
    public string? KeyValues { get; set; }

    /// <summary>
    ///     Gets or sets Matrix3x4T.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_matrix3x4_t</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_matrix3x4_t")]
    public Matrix3x4 Matrix3x4T { get; set; }

    /// <summary>
    ///     Gets or sets Matrix3x4aT.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_matrix3x4a_t</c> at offset <c>0xB0</c>.
    /// </remarks>
    [NativeOffset(0xB0)]
    [NativeName("m_matrix3x4a_t")]
    public Matrix3x4a Matrix3x4aT { get; set; }

    /// <summary>
    ///     Gets or sets QAngle.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_QAngle</c> at offset <c>0x40</c>.
    /// </remarks>
    [NativeOffset(0x40)]
    [NativeName("m_QAngle")]
    public QAngle QAngle { get; set; }

    /// <summary>
    ///     Gets or sets Quaternion.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Quaternion</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_Quaternion")]
    public Quaternion Quaternion { get; set; }

    /// <summary>
    ///     Gets or sets QuaternionStorage.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_QuaternionStorage</c> at offset <c>0x70</c>.
    /// </remarks>
    [NativeOffset(0x70)]
    [NativeName("m_QuaternionStorage")]
    public QuaternionStorage QuaternionStorage { get; set; }

    /// <summary>
    ///     Gets or sets RadianEuler.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_RadianEuler</c> at offset <c>0x58</c>.
    /// </remarks>
    [NativeOffset(0x58)]
    [NativeName("m_RadianEuler")]
    public RadianEuler RadianEuler { get; set; }

    /// <summary>
    ///     Gets or sets ResourceTypes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_ResourceTypes</c> at offset <c>0x160</c>.
    /// </remarks>
    [NativeOffset(0x160)]
    [NativeName("m_ResourceTypes")]
    public CResourceArray__CResourcePointer__CResourceString____ ResourceTypes { get; set; }

    /// <summary>
    ///     Gets or sets RotationVector.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_RotationVector</c> at offset <c>0x4C</c>.
    /// </remarks>
    [NativeOffset(0x4C)]
    [NativeName("m_RotationVector")]
    public RotationVector RotationVector { get; set; }

    /// <summary>
    ///     Gets or sets StringToken.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_stringToken</c> at offset <c>0x144</c>.
    /// </remarks>
    [NativeOffset(0x144)]
    [NativeName("m_stringToken")]
    public string StringToken { get; set; }

    /// <summary>
    ///     Gets or sets StringTokenWithStorage.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_stringTokenWithStorage</c> at offset <c>0x148</c>.
    /// </remarks>
    [NativeOffset(0x148)]
    [NativeName("m_stringTokenWithStorage")]
    public string StringTokenWithStorage { get; set; }

    /// <summary>
    ///     Gets or sets Vector.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Vector</c> at offset <c>0x8</c>.
    /// </remarks>
    [NativeOffset(0x8)]
    [NativeName("m_Vector")]
    public Vector Vector { get; set; }

    /// <summary>
    ///     Gets or sets Vector2D.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Vector2D</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_Vector2D")]
    public Vector2D Vector2D { get; set; }

    /// <summary>
    ///     Gets or sets Vector4D.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Vector4D</c> at offset <c>0xE4</c>.
    /// </remarks>
    [NativeOffset(0xE4)]
    [NativeName("m_Vector4D")]
    public Vector4D Vector4D { get; set; }

    /// <summary>
    ///     Gets or sets VectorAligned.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_VectorAligned</c> at offset <c>0x20</c>.
    /// </remarks>
    [NativeOffset(0x20)]
    [NativeName("m_VectorAligned")]
    public VectorAligned VectorAligned { get; set; }

    /// <summary>
    ///     Gets or sets VectorWS.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_VectorWS</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_VectorWS")]
    public VectorWS VectorWS { get; set; }
}
