// <auto-generated/>
// CS2OpenSchema — Modellib/CFlexOp
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24662694 — 2026-08-10T23:45:15Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Modellib;

/// <summary>
///     CFlexOp.
/// </summary>
/// <remarks>
///     Module: <c>modellib</c> — 8 bytes, align 4.
/// </remarks>
[NativeSize(8)]
[NativeMetadata("MGetKV3ClassDefaults", "{\n\t\"m_OpCode\": 0,\n\t\"m_Data\": 0\n}")]
public partial class CFlexOp
{
    /// <summary>
    ///     Gets or sets Data.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_Data</c> at offset <c>0x4</c>.
    /// </remarks>
    [NativeOffset(0x4)]
    [NativeName("m_Data")]
    public int Data { get; set; }

    /// <summary>
    ///     Gets or sets OpCode.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_OpCode</c> at offset <c>0x0</c>.
    /// </remarks>
    [NativeOffset(0x0)]
    [NativeName("m_OpCode")]
    public FlexOpCode OpCode { get; set; }
}
