// <auto-generated/>
// CS2OpenSchema — Modellib/CMorphSetData
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24701871 — 2026-08-12T22:20:36Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Resourcesystem;

#endregion

namespace CS2OpenSchema.Modellib;

/// <summary>
///     CMorphSetData.
/// </summary>
/// <remarks>
///     Module: <c>modellib</c> — 152 bytes, align 8.
/// </remarks>
[NativeSize(152)]
[NativeMetadata("MGetKV3ClassDefaults",
    "{\n\t\"m_nWidth\": 0,\n\t\"m_nHeight\": 0,\n\t\"m_bundleTypes\":\n\t[\n\t],\n\t\"m_morphDatas\":\n\t[\n\t],\n\t\"m_pTextureAtlas\": \"\",\n\t\"m_FlexDesc\":\n\t[\n\t],\n\t\"m_FlexControllers\":\n\t[\n\t],\n\t\"m_FlexRules\":\n\t[\n\t]\n}")]
public partial class CMorphSetData
{
    /// <summary>
    ///     Gets or sets BundleTypes.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bundleTypes</c> at offset <c>0x18</c>.
    /// </remarks>
    [NativeOffset(0x18)]
    [NativeName("m_bundleTypes")]
    public MorphBundleType[] BundleTypes { get; set; }

    /// <summary>
    ///     Gets or sets FlexControllers.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_FlexControllers</c> at offset <c>0x68</c>.
    /// </remarks>
    [NativeOffset(0x68)]
    [NativeName("m_FlexControllers")]
    public CFlexController[] FlexControllers { get; set; }

    /// <summary>
    ///     Gets or sets FlexDesc.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_FlexDesc</c> at offset <c>0x50</c>.
    /// </remarks>
    [NativeOffset(0x50)]
    [NativeName("m_FlexDesc")]
    public CFlexDesc[] FlexDesc { get; set; }

    /// <summary>
    ///     Gets or sets FlexRules.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_FlexRules</c> at offset <c>0x80</c>.
    /// </remarks>
    [NativeOffset(0x80)]
    [NativeName("m_FlexRules")]
    public CFlexRule[] FlexRules { get; set; }

    /// <summary>
    ///     Gets or sets Height.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nHeight</c> at offset <c>0x14</c>.
    /// </remarks>
    [NativeOffset(0x14)]
    [NativeName("m_nHeight")]
    public int Height { get; set; }

    /// <summary>
    ///     Gets or sets MorphDatas.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_morphDatas</c> at offset <c>0x30</c>.
    /// </remarks>
    [NativeOffset(0x30)]
    [NativeName("m_morphDatas")]
    public CMorphData[] MorphDatas { get; set; }

    /// <summary>
    ///     Gets or sets TextureAtlas.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_pTextureAtlas</c> at offset <c>0x48</c>.
    /// </remarks>
    [NativeOffset(0x48)]
    [NativeName("m_pTextureAtlas")]
    public CStrongHandle<InfoForResourceTypeCTextureBase> TextureAtlas { get; set; }

    /// <summary>
    ///     Gets or sets Width.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nWidth</c> at offset <c>0x10</c>.
    /// </remarks>
    [NativeOffset(0x10)]
    [NativeName("m_nWidth")]
    public int Width { get; set; }
}
