// <auto-generated/>
// CS2OpenSchema — Scenesystem/ESceneViewDebugOverlaysListenerDataType
// Generated from upstream cs2_schema.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 24537688 — 2026-08-03 2026-08-03T18:18:10Z

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Scenesystem;

/// <summary>
///     ESceneViewDebugOverlaysListenerDataType_t.
/// </summary>
/// <remarks>
///     Module: <c>scenesystem</c> — 32-bit.
/// </remarks>
[NativeName("ESceneViewDebugOverlaysListenerDataType_t")]
public enum ESceneViewDebugOverlaysListenerDataType : uint
{
    /// <summary>
    ///     Unknown.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_Unknown</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_Unknown")]
    Unknown = 0,

    /// <summary>
    ///     Sphere.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_Sphere</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_Sphere")]
    Sphere = 1,

    /// <summary>
    ///     Capsule.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_Capsule</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_Capsule")]
    Capsule = 2,

    /// <summary>
    ///     BoxAngles.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_BoxAngles</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_BoxAngles")]
    BoxAngles = 3,

    /// <summary>
    ///     Line.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_Line</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_Line")]
    Line = 4,

    /// <summary>
    ///     SolidBoxAngles.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_SolidBoxAngles</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_SolidBoxAngles")]
    SolidBoxAngles = 5,

    /// <summary>
    ///     Text3D.
    /// </summary>
    /// <remarks>
    ///     Native name: <c>k_ESceneViewDebugOverlaysListenerDataType_Text3D</c>.
    /// </remarks>
    [NativeName("k_ESceneViewDebugOverlaysListenerDataType_Text3D")]
    Text3D = 6
}
