// <auto-generated/>
// CS2OpenSchema — Particles/CINITInitFromParentKilled
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_INIT_InitFromParentKilled
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 616 bytes, align 8.
/// </remarks>
[NativeSize(616)]
[NativeName("C_INIT_InitFromParentKilled")]
public partial class CINITInitFromParentKilled : CParticleFunctionInitializer
{
    /// <summary>
    ///     Gets or sets AttributeToCopy.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nAttributeToCopy</c> at offset <c>0x1E0</c>.
    /// </remarks>
    [NativeOffset(0x1E0)]
    [NativeName("m_nAttributeToCopy")]
    [NativeMetadata("MPropertyFriendlyName", "\"field to init\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"particlefield\"")]
    public ParticleAttributeIndex AttributeToCopy { get; set; }

    /// <summary>
    ///     Gets or sets EventType.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nEventType</c> at offset <c>0x1E4</c>.
    /// </remarks>
    [NativeOffset(0x1E4)]
    [NativeName("m_nEventType")]
    [NativeMetadata("MPropertyFriendlyName", "\"event type\"")]
    public EventTypeSelection EventType { get; set; }
}
