// <auto-generated/>
// CS2OpenSchema — Particles/CINITVelocityFromCP
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Particleslib;

#endregion

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_INIT_VelocityFromCP
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 2312 bytes, align 8.
/// </remarks>
[NativeSize(2312)]
[NativeName("C_INIT_VelocityFromCP")]
public partial class CINITVelocityFromCP : CParticleFunctionInitializer
{
    /// <summary>
    ///     Gets or sets DirectionOnly.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bDirectionOnly</c> at offset <c>0x904</c>.
    /// </remarks>
    [NativeOffset(0x904)]
    [NativeName("m_bDirectionOnly")]
    [NativeMetadata("MPropertyFriendlyName", "\"direction only\"")]
    public bool DirectionOnly { get; set; }

    /// <summary>
    ///     Gets or sets TransformInput.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_transformInput</c> at offset <c>0x898</c>.
    /// </remarks>
    [NativeOffset(0x898)]
    [NativeName("m_transformInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"local space\"")]
    [NativeMetadata("MParticleInputOptional")]
    public CParticleTransformInput TransformInput { get; set; }

    /// <summary>
    ///     Gets or sets VelocityInput.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_velocityInput</c> at offset <c>0x1E0</c>.
    /// </remarks>
    [NativeOffset(0x1E0)]
    [NativeName("m_velocityInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"velocity\"")]
    public CParticleCollectionVecInput VelocityInput { get; set; }

    /// <summary>
    ///     Gets or sets VelocityScale.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flVelocityScale</c> at offset <c>0x900</c>.
    /// </remarks>
    [NativeOffset(0x900)]
    [NativeName("m_flVelocityScale")]
    [NativeMetadata("MPropertyFriendlyName", "\"velocity scale\"")]
    public float VelocityScale { get; set; }
}
