// <auto-generated/>
// CS2OpenSchema — Particles/CINITRemapParticleCountToNamedModelElementScalar
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Resourcesystem;

#endregion

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_INIT_RemapParticleCountToNamedModelElementScalar
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 560 bytes, align 8.
/// </remarks>
[NativeSize(560)]
[NativeName("C_INIT_RemapParticleCountToNamedModelElementScalar")]
public partial class CINITRemapParticleCountToNamedModelElementScalar : CINITRemapParticleCountToScalar
{
    /// <summary>
    ///     Gets or sets Model.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_hModel</c> at offset <c>0x210</c>.
    /// </remarks>
    [NativeOffset(0x210)]
    [NativeName("m_hModel")]
    public InfoForResourceTypeCModel? Model { get; set; }

    /// <summary>
    ///     Gets or sets ModelFromRenderer.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bModelFromRenderer</c> at offset <c>0x228</c>.
    /// </remarks>
    [NativeOffset(0x228)]
    [NativeName("m_bModelFromRenderer")]
    public bool ModelFromRenderer { get; set; }

    /// <summary>
    ///     Gets or sets OutputMaxName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_outputMaxName</c> at offset <c>0x220</c>.
    /// </remarks>
    [NativeOffset(0x220)]
    [NativeName("m_outputMaxName")]
    [NativeMetadata("MPropertyFriendlyName", "\"output max name\"")]
    public string OutputMaxName { get; set; }

    /// <summary>
    ///     Gets or sets OutputMinName.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_outputMinName</c> at offset <c>0x218</c>.
    /// </remarks>
    [NativeOffset(0x218)]
    [NativeName("m_outputMinName")]
    [NativeMetadata("MPropertyFriendlyName", "\"output min name\"")]
    public string OutputMinName { get; set; }
}
