// <auto-generated/>
// CS2OpenSchema — Particles/COPDecay
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_OP_Decay
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 480 bytes, align 8.
/// </remarks>
[NativeSize(480)]
[NativeName("C_OP_Decay")]
public partial class COPDecay : CParticleFunctionOperator
{
    /// <summary>
    ///     Gets or sets ForcePreserveParticleOrder.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bForcePreserveParticleOrder</c> at offset <c>0x1D9</c>.
    /// </remarks>
    [NativeOffset(0x1D9)]
    [NativeName("m_bForcePreserveParticleOrder")]
    [NativeMetadata("MPropertyFriendlyName", "\"force preserving particle order\"")]
    public bool ForcePreserveParticleOrder { get; set; }

    /// <summary>
    ///     Gets or sets RopeDecay.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bRopeDecay</c> at offset <c>0x1D8</c>.
    /// </remarks>
    [NativeOffset(0x1D8)]
    [NativeName("m_bRopeDecay")]
    [NativeMetadata("MPropertyFriendlyName", "\"Reduce rope popping on decay\"")]
    public bool RopeDecay { get; set; }
}
