// <auto-generated/>
// CS2OpenSchema — Particles/COPMovementMoveAlongSkinnedCPSnapshot
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Particleslib;

#endregion

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_OP_MovementMoveAlongSkinnedCPSnapshot
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 1224 bytes, align 8.
/// </remarks>
[NativeSize(1224)]
[NativeName("C_OP_MovementMoveAlongSkinnedCPSnapshot")]
public partial class COPMovementMoveAlongSkinnedCPSnapshot : CParticleFunctionOperator
{
    /// <summary>
    ///     Gets or sets ControlPointNumber.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nControlPointNumber</c> at offset <c>0x1D8</c>.
    /// </remarks>
    [NativeOffset(0x1D8)]
    [NativeName("m_nControlPointNumber")]
    [NativeMetadata("MPropertyFriendlyName", "\"control point number\"")]
    public int ControlPointNumber { get; set; }

    /// <summary>
    ///     Gets or sets Interpolation.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flInterpolation</c> at offset <c>0x1E8</c>.
    /// </remarks>
    [NativeOffset(0x1E8)]
    [NativeName("m_flInterpolation")]
    [NativeMetadata("MPropertyFriendlyName", "\"Interpolation\"")]
    public CPerParticleFloatInput Interpolation { get; set; }

    /// <summary>
    ///     Gets or sets SetNormal.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bSetNormal</c> at offset <c>0x1E0</c>.
    /// </remarks>
    [NativeOffset(0x1E0)]
    [NativeName("m_bSetNormal")]
    [NativeMetadata("MPropertyFriendlyName", "\"set normal\"")]
    public bool SetNormal { get; set; }

    /// <summary>
    ///     Gets or sets SetRadius.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_bSetRadius</c> at offset <c>0x1E1</c>.
    /// </remarks>
    [NativeOffset(0x1E1)]
    [NativeName("m_bSetRadius")]
    [NativeMetadata("MPropertyFriendlyName", "\"set radius\"")]
    public bool SetRadius { get; set; }

    /// <summary>
    ///     Gets or sets SnapshotControlPointNumber.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nSnapshotControlPointNumber</c> at offset <c>0x1DC</c>.
    /// </remarks>
    [NativeOffset(0x1DC)]
    [NativeName("m_nSnapshotControlPointNumber")]
    [NativeMetadata("MPropertyFriendlyName", "\"snapshot control point number\"")]
    public int SnapshotControlPointNumber { get; set; }

    /// <summary>
    ///     Gets or sets TValue.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_flTValue</c> at offset <c>0x358</c>.
    /// </remarks>
    [NativeOffset(0x358)]
    [NativeName("m_flTValue")]
    [NativeMetadata("MPropertyFriendlyName", "\"Snapshot Index T Value\"")]
    public CPerParticleFloatInput TValue { get; set; }
}
