// <auto-generated/>
// CS2OpenSchema — Particles/COPRemapVectortoCP
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_OP_RemapVectortoCP
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 488 bytes, align 8.
/// </remarks>
[NativeSize(488)]
[NativeName("C_OP_RemapVectortoCP")]
public partial class COPRemapVectortoCP : CParticleFunctionOperator
{
    /// <summary>
    ///     Gets or sets FieldInput.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nFieldInput</c> at offset <c>0x1DC</c>.
    /// </remarks>
    [NativeOffset(0x1DC)]
    [NativeName("m_nFieldInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"input field\"")]
    [NativeMetadata("MPropertyAttributeChoiceName", "\"particlefield_vector\"")]
    public ParticleAttributeIndex FieldInput { get; set; }

    /// <summary>
    ///     Gets or sets OutControlPointNumber.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nOutControlPointNumber</c> at offset <c>0x1D8</c>.
    /// </remarks>
    [NativeOffset(0x1D8)]
    [NativeName("m_nOutControlPointNumber")]
    [NativeMetadata("MPropertyFriendlyName", "\"output control point\"")]
    public int OutControlPointNumber { get; set; }

    /// <summary>
    ///     Gets or sets ParticleNumber.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_nParticleNumber</c> at offset <c>0x1E0</c>.
    /// </remarks>
    [NativeOffset(0x1E0)]
    [NativeName("m_nParticleNumber")]
    [NativeMetadata("MPropertyFriendlyName", "\"particle number to read\"")]
    public int ParticleNumber { get; set; }
}
