// <auto-generated/>
// CS2OpenSchema — Particles/COPSetVariable
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

#region

using CS2OpenSchema.Particleslib;

#endregion

namespace CS2OpenSchema.Particles;

/// <summary>
///     C_OP_SetVariable
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 2776 bytes, align 8.
/// </remarks>
[NativeSize(2776)]
[NativeName("C_OP_SetVariable")]
public partial class COPSetVariable : CParticleFunctionPreEmission
{
    /// <summary>
    ///     Gets or sets FloatInput.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_floatInput</c> at offset <c>0x968</c>.
    /// </remarks>
    [NativeOffset(0x968)]
    [NativeName("m_floatInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"Value\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_variableReference.m_variableType != PVAL_FLOAT\"")]
    public CParticleCollectionFloatInput FloatInput { get; set; }

    /// <summary>
    ///     Gets or sets Input.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_vecInput</c> at offset <c>0x2B0</c>.
    /// </remarks>
    [NativeOffset(0x2B0)]
    [NativeName("m_vecInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"Value\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_variableReference.m_variableType != PVAL_VEC3\"")]
    public CParticleCollectionVecInput Input { get; set; }

    /// <summary>
    ///     Gets or sets PositionOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_positionOffset</c> at offset <c>0x298</c>.
    /// </remarks>
    [NativeOffset(0x298)]
    [NativeName("m_positionOffset")]
    [NativeMetadata("MPropertyFriendlyName", "\"Position Offset\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_variableReference.m_variableType != PVAL_TRANSFORM\"")]
    public Vector PositionOffset { get; set; }

    /// <summary>
    ///     Gets or sets RotationOffset.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_rotationOffset</c> at offset <c>0x2A4</c>.
    /// </remarks>
    [NativeOffset(0x2A4)]
    [NativeName("m_rotationOffset")]
    [NativeMetadata("MPropertyFriendlyName", "\"Rotation Offset\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_variableReference.m_variableType != PVAL_TRANSFORM\"")]
    public QAngle RotationOffset { get; set; }

    /// <summary>
    ///     Gets or sets TransformInput.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_transformInput</c> at offset <c>0x230</c>.
    /// </remarks>
    [NativeOffset(0x230)]
    [NativeName("m_transformInput")]
    [NativeMetadata("MPropertyFriendlyName", "\"Value\"")]
    [NativeMetadata("MPropertySuppressExpr", "\"m_variableReference.m_variableType != PVAL_TRANSFORM\"")]
    public CParticleTransformInput TransformInput { get; set; }

    /// <summary>
    ///     Gets or sets VariableReference.
    /// </summary>
    /// <remarks>
    ///     Native field <c>m_variableReference</c> at offset <c>0x1E0</c>.
    /// </remarks>
    [NativeOffset(0x1E0)]
    [NativeName("m_variableReference")]
    [NativeMetadata("MPropertyFriendlyName", "\"Variable\"")]
    public CParticleVariableRef VariableReference { get; set; }
}
