// <auto-generated/>
// CS2OpenSchema — Particles/ParticleOrientationSetMode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     ParticleOrientationSetMode_t
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 32-bit.
/// </remarks>
[NativeName("ParticleOrientationSetMode_t")]
public enum ParticleOrientationSetMode : uint
{
    /// <summary>
    ///     ParticleOrientationSetNone
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_ORIENTATION_SET_NONE</c>
    /// </remarks>
    [NativeName("PARTICLE_ORIENTATION_SET_NONE")]
    [NativeMetadata("MPropertyFriendlyName", "\"Don't Set\"")]
    ParticleOrientationSetNone = 4294967295,

    /// <summary>
    ///     ParticleOrientationSetFromVelocity
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_ORIENTATION_SET_FROM_VELOCITY</c>
    /// </remarks>
    [NativeName("PARTICLE_ORIENTATION_SET_FROM_VELOCITY")]
    [NativeMetadata("MPropertyFriendlyName", "\"Set From Velocity\"")]
    ParticleOrientationSetFromVelocity = 0,

    /// <summary>
    ///     ParticleOrientationSetFromNormal
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_ORIENTATION_SET_FROM_NORMAL</c>
    /// </remarks>
    [NativeName("PARTICLE_ORIENTATION_SET_FROM_NORMAL")]
    [NativeMetadata("MPropertyFriendlyName", "\"Set From Normal\"")]
    ParticleOrientationSetFromNormal = 1,

    /// <summary>
    ///     ParticleOrientationSetFromRotations
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_ORIENTATION_SET_FROM_ROTATIONS</c>
    /// </remarks>
    [NativeName("PARTICLE_ORIENTATION_SET_FROM_ROTATIONS")]
    [NativeMetadata("MPropertyFriendlyName", "\"Set From Rotations\"")]
    ParticleOrientationSetFromRotations = 2
}
