// <auto-generated/>
// CS2OpenSchema — Particles/ParticleReplicationMode
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     ParticleReplicationMode_t
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 32-bit — flags.
/// </remarks>
[Flags]
[NativeName("ParticleReplicationMode_t")]
public enum ParticleReplicationMode : uint
{
    /// <summary>
    ///     ParticleReplicationmodeNone
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_REPLICATIONMODE_NONE</c>
    /// </remarks>
    [NativeName("PARTICLE_REPLICATIONMODE_NONE")]
    [NativeMetadata("MPropertyFriendlyName", "\"Off\"")]
    ParticleReplicationmodeNone = 0,

    /// <summary>
    ///     ParticleReplicationmodeReplicateForEachParentParticle
    /// </summary>
    /// <remarks>
    ///     Native name: <c>PARTICLE_REPLICATIONMODE_REPLICATE_FOR_EACH_PARENT_PARTICLE</c>
    /// </remarks>
    [NativeName("PARTICLE_REPLICATIONMODE_REPLICATE_FOR_EACH_PARENT_PARTICLE")]
    [NativeMetadata("MPropertyFriendlyName", "\"Replicate for each parent particle\"")]
    ParticleReplicationmodeReplicateForEachParentParticle = 1
}
