// <auto-generated/>
// CS2OpenSchema — Particles/SpriteCardPerParticleScale
// Generated from schemas.json. Regenerate with cs2-sdk-exporter.
// Do not edit this file directly.

// Schema revision: 10641237 — May 07 2026 14:04:19

#nullable enable
#pragma warning disable CS8618 // non-nullable field not initialised
#pragma warning disable CS8714 // nullable type as Dictionary key
#pragma warning disable CS0108 // member hides inherited member (C++ field shadowing)

namespace CS2OpenSchema.Particles;

/// <summary>
///     SpriteCardPerParticleScale_t
/// </summary>
/// <remarks>
///     Module: <c>particles</c> — 32-bit.
/// </remarks>
[NativeName("SpriteCardPerParticleScale_t")]
public enum SpriteCardPerParticleScale : uint
{
    /// <summary>
    ///     SpritecardTexturePpScaleNone
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_NONE</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_NONE")]
    [NativeMetadata("MPropertyFriendlyName", "\"None\"")]
    SpritecardTexturePpScaleNone = 0,

    /// <summary>
    ///     SpritecardTexturePpScaleParticleAge
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_AGE</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_AGE")]
    [NativeMetadata("MPropertyFriendlyName", "\"Animation Time\"")]
    SpritecardTexturePpScaleParticleAge = 1,

    /// <summary>
    ///     SpritecardTexturePpScaleAnimationFrame
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_ANIMATION_FRAME</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_ANIMATION_FRAME")]
    [NativeMetadata("MPropertyFriendlyName", "\"Animation Frame\"")]
    SpritecardTexturePpScaleAnimationFrame = 2,

    /// <summary>
    ///     SpritecardTexturePpScaleShaderExtraData1
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA1</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA1")]
    [NativeMetadata("MPropertyFriendlyName", "\"Shader Extra Data 1\"")]
    SpritecardTexturePpScaleShaderExtraData1 = 3,

    /// <summary>
    ///     SpritecardTexturePpScaleShaderExtraData2
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA2</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_SHADER_EXTRA_DATA2")]
    [NativeMetadata("MPropertyFriendlyName", "\"Shader Extra Data 2\"")]
    SpritecardTexturePpScaleShaderExtraData2 = 4,

    /// <summary>
    ///     SpritecardTexturePpScaleParticleAlpha
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_ALPHA</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_PARTICLE_ALPHA")]
    [NativeMetadata("MPropertyFriendlyName", "\"Alpha\"")]
    SpritecardTexturePpScaleParticleAlpha = 5,

    /// <summary>
    ///     SpritecardTexturePpScaleShaderRadius
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_SHADER_RADIUS</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_SHADER_RADIUS")]
    [NativeMetadata("MPropertyFriendlyName", "\"Radius\"")]
    SpritecardTexturePpScaleShaderRadius = 6,

    /// <summary>
    ///     SpritecardTexturePpScaleRoll
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_ROLL</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_ROLL")]
    [NativeMetadata("MPropertyFriendlyName", "\"Roll\"")]
    SpritecardTexturePpScaleRoll = 7,

    /// <summary>
    ///     SpritecardTexturePpScaleYaw
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_YAW</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_YAW")]
    [NativeMetadata("MPropertyFriendlyName", "\"Yaw\"")]
    SpritecardTexturePpScaleYaw = 8,

    /// <summary>
    ///     SpritecardTexturePpScalePitch
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_PITCH</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_PITCH")]
    [NativeMetadata("MPropertyFriendlyName", "\"Pitch\"")]
    SpritecardTexturePpScalePitch = 9,

    /// <summary>
    ///     SpritecardTexturePpScaleRandom
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_RANDOM</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_RANDOM")]
    [NativeMetadata("MPropertyFriendlyName", "\"Random 0 - 1 Value\"")]
    SpritecardTexturePpScaleRandom = 10,

    /// <summary>
    ///     SpritecardTexturePpScaleNegRandom
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM")]
    [NativeMetadata("MPropertyFriendlyName", "\"Random -1 - 1 Value\"")]
    SpritecardTexturePpScaleNegRandom = 11,

    /// <summary>
    ///     SpritecardTexturePpScaleRandomTime
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_RANDOM_TIME</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_RANDOM_TIME")]
    [NativeMetadata("MPropertyFriendlyName", "\"Random 0 - 1 x Time\"")]
    SpritecardTexturePpScaleRandomTime = 12,

    /// <summary>
    ///     SpritecardTexturePpScaleNegRandomTime
    /// </summary>
    /// <remarks>
    ///     Native name: <c>SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM_TIME</c>
    /// </remarks>
    [NativeName("SPRITECARD_TEXTURE_PP_SCALE_NEG_RANDOM_TIME")]
    [NativeMetadata("MPropertyFriendlyName", "\"Random -1 - 1 x Time\"")]
    SpritecardTexturePpScaleNegRandomTime = 13
}
