// CS2OpenDev.Sdk.Exporter
//
// Reads schemas.json, drives the schema-gen emitters with a disk-writing sink,
// and produces the per-class file layout under src/CS2OpenDev.Sdk/. Includes
// stale-file cleanup so classes removed from the schema disappear from disk.
//
// Usage (from repo root):
//   dotnet run --project src/CS2OpenDev.Sdk.Exporter
//   dotnet run --project src/CS2OpenDev.Sdk.Exporter -- <schemas.json> <outputDir>

#region

using CS2OpenDev.SdkExporter;
using CS2SchemaGen;
using CS2SchemaGen.Diagnostics;
using CS2SchemaGen.Emitters;
using System.Text;
using System.Text.Json;
using CS2SchemaGen.Models;

#endregion

const string namespaceLabel = "CS2OpenSchema";

// Conventional filename for the optional consumer-overrides file (B4). Looked
// for next to the schema first, then in the working directory.
const string overridesFileName = "game-event-overrides.json";

// Discards every previously locked name and re-derives the whole file from the
// current vocabulary. A deliberate, reviewed act: it is the only way an already
// published identifier can change, so it must never be reachable by accident.
bool rebaselineNames = args.Contains("--rebaseline-names", StringComparer.Ordinal);
string[] positional = args.Where(a => !a.StartsWith("--", StringComparison.Ordinal)).ToArray();

string schemaPath = positional.Length > 0
    ? Path.GetFullPath(positional[0])
    : ResolveDefaultSchemaPath();

string outputDir = positional.Length > 1
    ? Path.GetFullPath(positional[1])
    : Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "src/CS2OpenDev.Sdk"));

// Lives beside version.json rather than in the generated tree: it is an input
// to generation, not a product of it, and it must survive the stale-file sweep.
string namesLockPath = Path.GetFullPath(
    Path.Combine(Directory.GetCurrentDirectory(), "names.lock.json"));

if (!File.Exists(schemaPath))
{
    Console.Error.WriteLine($"Schema file not found: {schemaPath}");
    if (schemaPath.Contains("upstream/", StringComparison.Ordinal))
    {
        Console.Error.WriteLine("The upstream submodule appears to be uninitialised.");
        Console.Error.WriteLine("Run: git submodule update --init upstream");
        Console.Error.WriteLine("Or refresh to latest: git submodule update --remote upstream");
    }
    else
    {
        Console.Error.WriteLine("Pass the schema path as the first argument.");
    }

    return 1;
}

Directory.CreateDirectory(outputDir);

string schemaJson;
try
{
    schemaJson = File.ReadAllText(schemaPath);
}
catch (IOException ex)
{
    Console.Error.WriteLine($"Failed to read {schemaPath}: {ex.Message}");
    return 1;
}

SchemaRoot schema;
try
{
    schema = SchemaModel.Parse(schemaJson);
}
catch (NotSupportedException ex)
{
    // Format-version mismatch. Already carries its own diagnostic text (built
    // from Descriptors.UnsupportedSchemaFormat), so report it under that id
    // rather than wrapping it in the generic parse-failure message.
    WriteDiagnosticRaw(Descriptors.UnsupportedSchemaFormat.Id, GeneratorDiagnosticSeverity.Error, ex.Message);
    return 1;
}
catch (Exception ex)
{
    WriteDiagnostic(Descriptors.ParseFailed, ex.Message);
    return 1;
}

// Sweep generator-owned files before writing. The discriminator is the
// `// <auto-generated/>` marker on the first line — every emitted file carries
// it; hand-written partial-class extensions don't. Files without the marker
// survive a regen untouched.
HashSet<string> staleCandidates = new(StringComparer.Ordinal);
foreach (string path in Directory.EnumerateFiles(outputDir, "*.cs", SearchOption.AllDirectories))
{
    if (IsGeneratedFile(path))
    {
        staleCandidates.Add(Path.GetFullPath(path));
    }
}

DiskSink sink = new(outputDir, staleCandidates);

// Second output tree: the generated half of CS2OpenDev.Sdk.GameEvents. Derived
// from the SDK output dir so `dotnet run --project src/CS2OpenDev.Sdk.Exporter`
// with no arguments lands both trees in the right place, and an explicit
// two-argument invocation (custom schema → scratch dir) keeps them together
// rather than writing into the repo.
string gameEventsDir = Path.GetFullPath(
    Path.Combine(outputDir, "..", "CS2OpenDev.Sdk.GameEvents"));
Directory.CreateDirectory(gameEventsDir);

HashSet<string> gameEventsStale = new(StringComparer.Ordinal);
string gameEventsGenerated = Path.Combine(gameEventsDir, "Generated");
if (Directory.Exists(gameEventsGenerated))
{
    foreach (string path in Directory.EnumerateFiles(gameEventsGenerated, "*.cs", SearchOption.AllDirectories))
    {
        if (IsGeneratedFile(path))
        {
            gameEventsStale.Add(Path.GetFullPath(path));
        }
    }
}

Console.WriteLine($"Schema: {schemaPath}");
Console.WriteLine($"Output: {outputDir}");

Dictionary<string, string> nameLock = rebaselineNames
    ? new Dictionary<string, string>(StringComparer.Ordinal)
    : LoadNameLock(namesLockPath);

if (rebaselineNames)
{
    Console.WriteLine("Names: REBASELINING — every identifier re-derived from the vocabulary.");
}
else
{
    Console.WriteLine($"Names: {nameLock.Count} locked from {Path.GetFileName(namesLockPath)}");
}

Console.WriteLine();

WordSplitter.LoadLock(nameLock);

ModuleEmitter.EmitAll(sink, schema, namespaceLabel);

// Game events live in a separate KV1-derived schema file next to cs2_schema.json
// in the upstream submodule. Treat them as an optional input: emit if found,
// silently skip otherwise so users running against a custom schema dump without
// the events file see no failure. Reuses the cs2_schema revision for the file
// stamp so a single `Schema revision: …` line lets consumers tie an event record
// back to the same CS2 build the class projections were generated from.
string? eventsPath = ResolveGameEventsPath(schemaPath);
if (eventsPath is not null && File.Exists(eventsPath))
{
    string eventsJson;
    try
    {
        eventsJson = File.ReadAllText(eventsPath);
    }
    catch (IOException ex)
    {
        Console.Error.WriteLine($"Failed to read {eventsPath}: {ex.Message}");
        return 1;
    }

    GameEventsRoot eventsRoot;
    try
    {
        eventsRoot = GameEventsModel.Parse(eventsJson);
    }
    catch (NotSupportedException ex)
    {
        WriteDiagnosticRaw(Descriptors.UnsupportedSchemaFormat.Id, GeneratorDiagnosticSeverity.Error, ex.Message);
        return 1;
    }
    catch (Exception ex)
    {
        WriteDiagnostic(Descriptors.ParseFailed, ex.Message);
        return 1;
    }

    // Optional consumer overrides (B4). Absent by default; when present it can
    // re-point a KV1 type tag at a consumer's own type. Applied to the records
    // and the factories from the same source, so the two cannot disagree.
    string? schemaDir = Path.GetDirectoryName(schemaPath);
    string workingDir = Directory.GetCurrentDirectory();

    GameEventOverrides overrides = GameEventOverrides.Empty;
    string? overridesPath = SideCarFile.Resolve(overridesFileName, schemaDir, workingDir);
    if (overridesPath is not null)
    {
        try
        {
            overrides = GameEventOverrides.Parse(File.ReadAllText(overridesPath));
        }
        catch (Exception ex) when (ex is JsonException or InvalidOperationException)
        {
            WriteDiagnosticRaw(
                Descriptors.InvalidOverrides.Id,
                GeneratorDiagnosticSeverity.Error,
                Descriptors.InvalidOverrides.Format(overridesPath, ex.Message));
            return 1;
        }

        Console.WriteLine(
            $"Overrides: {overridesPath} ({overrides.FieldTypes.Count} field-type override(s))");
    }

    // Curated events the extractor cannot see (issue #3). Merged here, inside the
    // "events schema was found" branch, so a supplement can only ever *extend* a
    // real extraction — never stand in for one. A run whose events schema is
    // missing preserves the previously emitted records untouched (see the else
    // branch below); letting a supplement emit on its own would turn that
    // preservation into a three-record tree.
    string? supplementPath = GameEventSupplement.ResolvePath(schemaDir, workingDir);
    if (supplementPath is not null)
    {
        GameEventsRoot supplement;
        try
        {
            supplement = GameEventSupplement.Parse(File.ReadAllText(supplementPath));
        }
        catch (Exception ex) when (ex is JsonException or InvalidOperationException or NotSupportedException)
        {
            WriteDiagnosticRaw(
                Descriptors.InvalidSupplement.Id,
                GeneratorDiagnosticSeverity.Error,
                Descriptors.InvalidSupplement.Format(supplementPath, ex.Message));
            return 1;
        }

        try
        {
            eventsRoot = GameEventSupplement.Apply(eventsRoot, supplement);
        }
        catch (InvalidOperationException ex)
        {
            WriteDiagnosticRaw(
                Descriptors.SupplementSuperseded.Id,
                GeneratorDiagnosticSeverity.Error,
                Descriptors.SupplementSuperseded.Format(supplementPath, ex.Message));
            return 1;
        }

        Console.WriteLine(
            $"Supplement: {supplementPath} ({supplement.Events.Length} curated event(s) not in the schema)");
    }

    // Expand the pawn-bearing player-reference types into the wire keys the
    // engine actually emits. After the supplement merge, so curated events get
    // the same treatment — the rule follows the type tag, not the record's
    // provenance — and before both emitters, so the record properties and the
    // factory that fills them are built from one field list.
    int beforeExpansion = eventsRoot.Events.Sum(e => e.Fields.Length);
    eventsRoot = GameEventPawnExpansion.Expand(eventsRoot);
    int afterExpansion = eventsRoot.Events.Sum(e => e.Fields.Length);

    Console.WriteLine($"GameEvents: {eventsPath} ({eventsRoot.Events.Length} events)");
    Console.WriteLine(
        $"GameEvents: pawn expansion added {afterExpansion - beforeExpansion} companion field(s)");
    GameEventsEmitter.EmitAll(sink, eventsRoot, namespaceLabel, schema, overrides);

    // The decoder's factory table and name registry go to a *different* package.
    // They reference protobuf-decoded values, so they cannot live in
    // CS2OpenDev.Sdk without putting Google.Protobuf in every consumer's
    // dependency graph — and that package's zero-dependency footprint is a
    // deliberate, load-bearing property.
    //
    // Its own sink, its own stale sweep: the two output trees are independent,
    // and a file vanishing from one must not be evaluated against the other's
    // candidate set.
    DiskSink gameEventsSink = new(gameEventsDir, gameEventsStale);
    GameEventFactoryEmitter.EmitAll(gameEventsSink, eventsRoot, schema, overrides);
    Console.WriteLine($"GameEvents package: {gameEventsSink.WrittenCount} file(s) to {gameEventsDir}");
    foreach (string path in gameEventsStale)
    {
        File.Delete(path);
    }
}
else
{
    // GameEvents schema is optional input: if the file is missing (e.g. a custom
    // class-schema dump that doesn't ship one), preserve the previously-emitted
    // Events/ bucket instead of letting the stale-sweep below nuke it. Without
    // this carve-out, a temporary submodule-init failure would silently delete
    // 288 event records that the next run would have to fully regenerate.
    string eventsDir = Path.Combine(outputDir, "Events");
    string schemaEventsFile = Path.GetFullPath(Path.Combine(outputDir, "SchemaEvents.cs"));
    int preserved = staleCandidates.RemoveWhere(p =>
        p.StartsWith(eventsDir + Path.DirectorySeparatorChar, StringComparison.Ordinal)
        || string.Equals(p, schemaEventsFile, StringComparison.Ordinal));
    if (preserved > 0)
    {
        Console.WriteLine($"GameEvents: schema absent — preserved {preserved} existing event file(s).");
    }
    else
    {
        // No prior event files exist either. Surface the skip explicitly so a
        // contributor running against a custom class-schema doesn't wonder why
        // the Events/ directory is empty.
        Console.WriteLine("GameEvents: schema not found alongside class schema — skipping events emission.");
    }
}

// ── Name diagnostics ─────────────────────────────────────────────────────────
//
// Drained here rather than inside ModuleEmitter, which is where they used to
// live and where they could not work. WordSplitter accumulates over the whole
// process, but ModuleEmitter.EmitAll is only the first of the two emitters above
// — and the second one, GameEventsEmitter, handles exactly the flat KV1 names
// (`userid`, `attackerinair`) the splitter was written for. Reporting from
// inside the first emitter emptied the bucket before any of those had been
// folded, so every game-event run landed in it afterwards and was never seen.
// A full rebaseline printed zero CS2_GEN_006 lines while genuine near-misses
// were sitting in the bucket unread.
//
// This is the only point that is after all emission and before exit, so it is
// the only correct place for it.
foreach (string run in WordSplitter.UnsegmentedRuns)
{
    sink.ReportDiagnostic(Descriptors.UnsegmentedWord, run);
}

// Locked runs the vocabulary now disagrees with. Reported, never applied: the
// names written above already used the pinned spelling.
foreach ((string run, (string locked, string vocabulary)) in WordSplitter.StaleLockedRuns)
{
    sink.ReportDiagnostic(Descriptors.StaleLockedName, run, locked, vocabulary);
}

// Delete any generator-owned file we tracked before emission that this run did
// not produce — classes that disappeared from the schema since the last regen.
int stale = 0;
foreach (string path in staleCandidates)
{
    File.Delete(path);
    stale++;
}

// Prune empty directories left behind by stale-file deletion. Walk deepest-first
// so child empties are removed before their parents are evaluated.
foreach (string dir in Directory.EnumerateDirectories(outputDir, "*", SearchOption.AllDirectories)
             .OrderByDescending(d => d.Length))
{
    if (!Directory.EnumerateFileSystemEntries(dir).Any())
    {
        Directory.Delete(dir);
    }
}

Console.WriteLine($"Exported {sink.WrittenCount} file(s) to {outputDir}");
if (stale > 0)
{
    Console.WriteLine($"Pruned {stale} stale file(s).");
}

// Write the lock back with this run's decisions folded in. Existing entries are
// never recomputed — WordSplitter returns them verbatim — so the only possible
// diff on a normal run is new names appended, which is exactly what should
// happen when upstream adds a field.
WriteNameLock(namesLockPath, WordSplitter.ResolvedRuns);

IReadOnlyDictionary<string, string> fresh = WordSplitter.UnlockedRuns;
if (fresh.Count > 0)
{
    // Named individually rather than counted. These are the only identifiers
    // this run could have got wrong; everything else was decided and reviewed
    // in an earlier release. It is a short list precisely because the lock
    // holds, and it is the review list for the next release.
    Console.WriteLine();
    Console.WriteLine($"{fresh.Count} name(s) not previously locked — review before release:");
    foreach ((string run, string resolved) in fresh)
    {
        Console.WriteLine($"  {run} -> {resolved}");
    }
}

foreach ((string id, GeneratorDiagnosticSeverity severity, string message) in sink.Diagnostics)
{
    WriteDiagnosticRaw(id, severity, message);
}

return 0;

static Dictionary<string, string> LoadNameLock(string path)
{
    Dictionary<string, string> result = new(StringComparer.Ordinal);
    if (!File.Exists(path))
    {
        return result;
    }

    using JsonDocument doc = JsonDocument.Parse(File.ReadAllText(path));
    if (!doc.RootElement.TryGetProperty("runs", out JsonElement runs))
    {
        return result;
    }

    foreach (JsonProperty entry in runs.EnumerateObject())
    {
        if (entry.Value.ValueKind == JsonValueKind.String)
        {
            result[entry.Name] = entry.Value.GetString()!;
        }
    }

    return result;
}

static void WriteNameLock(string path, IReadOnlyDictionary<string, string> runs)
{
    StringBuilder sb = new();
    sb.AppendLine("{");
    sb.AppendLine("  \"$comment\": [");
    sb.AppendLine("    \"Generated. Do not hand-edit — regenerate with cs2-sdk-exporter.\",");
    sb.AppendLine("    \"\",");
    sb.AppendLine("    \"Every run-together lowercase word the generator has resolved, and what\",");
    sb.AppendLine("    \"it resolved to. A run listed here is returned verbatim and the word\",");
    sb.AppendLine("    \"vocabulary is never consulted for it again.\",");
    sb.AppendLine("    \"\",");
    sb.AppendLine("    \"This exists because the vocabulary is retroactive: adding a word to\",");
    sb.AppendLine("    \"split some new field also re-splits every existing name that word can\",");
    sb.AppendLine("    \"cut. Adding 'base' turned 'Database' into 'DataBase'. Without the lock,\",");
    sb.AppendLine("    \"every vocabulary edit risks renaming published API from a scheduled job\",");
    sb.AppendLine("    \"that regenerates and publishes unattended.\",");
    sb.AppendLine("    \"\",");
    sb.AppendLine("    \"Entries are added, never rewritten. New upstream fields append here on\",");
    sb.AppendLine("    \"the next regen; that diff is expected. A CHANGED entry is not, and means\",");
    sb.AppendLine("    \"someone ran --rebaseline-names, which renames shipped API and needs a\",");
    sb.AppendLine("    \"major version bump.\"");
    sb.AppendLine("  ],");
    sb.AppendLine("  \"runs\": {");

    int i = 0;
    foreach ((string run, string resolved) in runs)
    {
        sb.Append("    ")
          .Append(JsonSerializer.Serialize(run))
          .Append(": ")
          .Append(JsonSerializer.Serialize(resolved))
          .AppendLine(++i < runs.Count ? "," : string.Empty);
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    File.WriteAllText(path, sb.ToString().Replace("\r\n", "\n", StringComparison.Ordinal));
}

static string ResolveDefaultSchemaPath()
{
    // Primary source: the upstream submodule's community-enriched cs2_schema.json,
    // refreshed by `git submodule update --remote upstream`. Falls back to a
    // local schemas.json at the repo root or output/ for offline scenarios and
    // legacy paths. Returns the upstream path even when missing so the caller
    // can emit a submodule-init hint instead of a generic "not found" error.
    string cwd = Directory.GetCurrentDirectory();
    string upstream = Path.GetFullPath(Path.Combine(cwd, "upstream", "docs", "generated",
        "downstream-codegen-schemas", "cs2_schema.json"));
    string outputLocal = Path.GetFullPath(Path.Combine(cwd, "output", "schemas.json"));
    string rootLocal = Path.GetFullPath(Path.Combine(cwd, "schemas.json"));

    if (File.Exists(upstream))
    {
        return upstream;
    }

    bool outputExists = File.Exists(outputLocal);
    bool rootExists = File.Exists(rootLocal);

    if (outputExists && rootExists)
    {
        WriteDiagnostic(Descriptors.MultipleSchemaFiles, outputLocal);
        return outputLocal;
    }

    if (outputExists)
    {
        return outputLocal;
    }

    if (rootExists)
    {
        return rootLocal;
    }

    // Nothing exists — return the preferred upstream path so the not-found
    // branch can recognise it and print the submodule-init instructions.
    return upstream;
}

// Sibling of the class-schema input — the upstream submodule keeps them in the
// same directory. When the user passed a custom class-schema path, look for
// gameevents_schema.json next to it; otherwise default to the upstream layout.
// Returns null when no candidate is sensible so the caller can skip silently.
static string? ResolveGameEventsPath(string classSchemaPath)
{
    string? dir = Path.GetDirectoryName(classSchemaPath);
    if (dir is null)
    {
        return null;
    }

    string sibling = Path.Combine(dir, "gameevents_schema.json");
    return File.Exists(sibling) ? sibling : null;
}

static void WriteDiagnostic(GeneratorDiagnostic diagnostic, params object[] args) =>
    WriteDiagnosticRaw(diagnostic.Id, diagnostic.Severity, diagnostic.Format(args));

static void WriteDiagnosticRaw(string id, GeneratorDiagnosticSeverity severity, string message) =>
    Console.Error.WriteLine($"{severity.ToString().ToLowerInvariant()} {id}: {message}");

static bool IsGeneratedFile(string path)
{
    try
    {
        using StreamReader reader = new(path);
        string? first = reader.ReadLine();
        return first is not null && first.Contains("<auto-generated/>", StringComparison.Ordinal);
    }
    catch (IOException)
    {
        return false;
    }
}
