// CS2OpenDev.Sdk.Exporter
//
// Reads schemas.json, drives the schema-gen emitters with a disk-writing sink,
// and produces the per-class file layout under src/CS2OpenDev.Sdk/. Includes
// stale-file cleanup so classes removed from the schema disappear from disk.
//
// Usage (from repo root):
//   dotnet run --project src/CS2OpenDev.Sdk.Exporter
//   dotnet run --project src/CS2OpenDev.Sdk.Exporter -- <schemas.json> <outputDir>

#region

using CS2OpenDev.SdkExporter;
using CS2SchemaGen;
using CS2SchemaGen.Diagnostics;
using CS2SchemaGen.Emitters;
using System.Text.Json;
using CS2SchemaGen.Models;

#endregion

const string namespaceLabel = "CS2OpenSchema";

// Conventional filename for the optional consumer-overrides file (B4). Looked
// for next to the schema first, then in the working directory.
const string overridesFileName = "game-event-overrides.json";

string schemaPath = args.Length > 0
    ? Path.GetFullPath(args[0])
    : ResolveDefaultSchemaPath();

string outputDir = args.Length > 1
    ? Path.GetFullPath(args[1])
    : Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "src/CS2OpenDev.Sdk"));

if (!File.Exists(schemaPath))
{
    Console.Error.WriteLine($"Schema file not found: {schemaPath}");
    if (schemaPath.Contains("upstream/", StringComparison.Ordinal))
    {
        Console.Error.WriteLine("The upstream submodule appears to be uninitialised.");
        Console.Error.WriteLine("Run: git submodule update --init upstream");
        Console.Error.WriteLine("Or refresh to latest: git submodule update --remote upstream");
    }
    else
    {
        Console.Error.WriteLine("Pass the schema path as the first argument.");
    }

    return 1;
}

Directory.CreateDirectory(outputDir);

string schemaJson;
try
{
    schemaJson = File.ReadAllText(schemaPath);
}
catch (IOException ex)
{
    Console.Error.WriteLine($"Failed to read {schemaPath}: {ex.Message}");
    return 1;
}

SchemaRoot schema;
try
{
    schema = SchemaModel.Parse(schemaJson);
}
catch (NotSupportedException ex)
{
    // Format-version mismatch. Already carries its own diagnostic text (built
    // from Descriptors.UnsupportedSchemaFormat), so report it under that id
    // rather than wrapping it in the generic parse-failure message.
    WriteDiagnosticRaw(Descriptors.UnsupportedSchemaFormat.Id, GeneratorDiagnosticSeverity.Error, ex.Message);
    return 1;
}
catch (Exception ex)
{
    WriteDiagnostic(Descriptors.ParseFailed, ex.Message);
    return 1;
}

// Sweep generator-owned files before writing. The discriminator is the
// `// <auto-generated/>` marker on the first line — every emitted file carries
// it; hand-written partial-class extensions don't. Files without the marker
// survive a regen untouched.
HashSet<string> staleCandidates = new(StringComparer.Ordinal);
foreach (string path in Directory.EnumerateFiles(outputDir, "*.cs", SearchOption.AllDirectories))
{
    if (IsGeneratedFile(path))
    {
        staleCandidates.Add(Path.GetFullPath(path));
    }
}

DiskSink sink = new(outputDir, staleCandidates);

// Second output tree: the generated half of CS2OpenDev.Sdk.GameEvents. Derived
// from the SDK output dir so `dotnet run --project src/CS2OpenDev.Sdk.Exporter`
// with no arguments lands both trees in the right place, and an explicit
// two-argument invocation (custom schema → scratch dir) keeps them together
// rather than writing into the repo.
string gameEventsDir = Path.GetFullPath(
    Path.Combine(outputDir, "..", "CS2OpenDev.Sdk.GameEvents"));
Directory.CreateDirectory(gameEventsDir);

HashSet<string> gameEventsStale = new(StringComparer.Ordinal);
string gameEventsGenerated = Path.Combine(gameEventsDir, "Generated");
if (Directory.Exists(gameEventsGenerated))
{
    foreach (string path in Directory.EnumerateFiles(gameEventsGenerated, "*.cs", SearchOption.AllDirectories))
    {
        if (IsGeneratedFile(path))
        {
            gameEventsStale.Add(Path.GetFullPath(path));
        }
    }
}

Console.WriteLine($"Schema: {schemaPath}");
Console.WriteLine($"Output: {outputDir}");
Console.WriteLine();

ModuleEmitter.EmitAll(sink, schema, namespaceLabel);

// Game events live in a separate KV1-derived schema file next to cs2_schema.json
// in the upstream submodule. Treat them as an optional input: emit if found,
// silently skip otherwise so users running against a custom schema dump without
// the events file see no failure. Reuses the cs2_schema revision for the file
// stamp so a single `Schema revision: …` line lets consumers tie an event record
// back to the same CS2 build the class projections were generated from.
string? eventsPath = ResolveGameEventsPath(schemaPath);
if (eventsPath is not null && File.Exists(eventsPath))
{
    string eventsJson;
    try
    {
        eventsJson = File.ReadAllText(eventsPath);
    }
    catch (IOException ex)
    {
        Console.Error.WriteLine($"Failed to read {eventsPath}: {ex.Message}");
        return 1;
    }

    GameEventsRoot eventsRoot;
    try
    {
        eventsRoot = GameEventsModel.Parse(eventsJson);
    }
    catch (NotSupportedException ex)
    {
        WriteDiagnosticRaw(Descriptors.UnsupportedSchemaFormat.Id, GeneratorDiagnosticSeverity.Error, ex.Message);
        return 1;
    }
    catch (Exception ex)
    {
        WriteDiagnostic(Descriptors.ParseFailed, ex.Message);
        return 1;
    }

    // Optional consumer overrides (B4). Absent by default; when present it can
    // re-point a KV1 type tag at a consumer's own type. Applied to the records
    // and the factories from the same source, so the two cannot disagree.
    GameEventOverrides overrides = GameEventOverrides.Empty;
    string overridesPath = Path.Combine(Path.GetDirectoryName(schemaPath) ?? ".", overridesFileName);
    if (!File.Exists(overridesPath))
    {
        overridesPath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), overridesFileName));
    }

    if (File.Exists(overridesPath))
    {
        try
        {
            overrides = GameEventOverrides.Parse(File.ReadAllText(overridesPath));
        }
        catch (Exception ex) when (ex is JsonException or InvalidOperationException)
        {
            WriteDiagnosticRaw(
                Descriptors.InvalidOverrides.Id,
                GeneratorDiagnosticSeverity.Error,
                Descriptors.InvalidOverrides.Format(overridesPath, ex.Message));
            return 1;
        }

        Console.WriteLine(
            $"Overrides: {overridesPath} ({overrides.FieldTypes.Count} field-type override(s))");
    }

    Console.WriteLine($"GameEvents: {eventsPath} ({eventsRoot.Events.Length} events)");
    GameEventsEmitter.EmitAll(sink, eventsRoot, namespaceLabel, schema, overrides);

    // The decoder's factory table and name registry go to a *different* package.
    // They reference protobuf-decoded values, so they cannot live in
    // CS2OpenDev.Sdk without putting Google.Protobuf in every consumer's
    // dependency graph — and that package's zero-dependency footprint is a
    // deliberate, load-bearing property.
    //
    // Its own sink, its own stale sweep: the two output trees are independent,
    // and a file vanishing from one must not be evaluated against the other's
    // candidate set.
    DiskSink gameEventsSink = new(gameEventsDir, gameEventsStale);
    GameEventFactoryEmitter.EmitAll(gameEventsSink, eventsRoot, schema, overrides);
    Console.WriteLine($"GameEvents package: {gameEventsSink.WrittenCount} file(s) to {gameEventsDir}");
    foreach (string path in gameEventsStale)
    {
        File.Delete(path);
    }
}
else
{
    // GameEvents schema is optional input: if the file is missing (e.g. a custom
    // class-schema dump that doesn't ship one), preserve the previously-emitted
    // Events/ bucket instead of letting the stale-sweep below nuke it. Without
    // this carve-out, a temporary submodule-init failure would silently delete
    // 288 event records that the next run would have to fully regenerate.
    string eventsDir = Path.Combine(outputDir, "Events");
    string schemaEventsFile = Path.GetFullPath(Path.Combine(outputDir, "SchemaEvents.cs"));
    int preserved = staleCandidates.RemoveWhere(p =>
        p.StartsWith(eventsDir + Path.DirectorySeparatorChar, StringComparison.Ordinal)
        || string.Equals(p, schemaEventsFile, StringComparison.Ordinal));
    if (preserved > 0)
    {
        Console.WriteLine($"GameEvents: schema absent — preserved {preserved} existing event file(s).");
    }
    else
    {
        // No prior event files exist either. Surface the skip explicitly so a
        // contributor running against a custom class-schema doesn't wonder why
        // the Events/ directory is empty.
        Console.WriteLine("GameEvents: schema not found alongside class schema — skipping events emission.");
    }
}

// Delete any generator-owned file we tracked before emission that this run did
// not produce — classes that disappeared from the schema since the last regen.
int stale = 0;
foreach (string path in staleCandidates)
{
    File.Delete(path);
    stale++;
}

// Prune empty directories left behind by stale-file deletion. Walk deepest-first
// so child empties are removed before their parents are evaluated.
foreach (string dir in Directory.EnumerateDirectories(outputDir, "*", SearchOption.AllDirectories)
             .OrderByDescending(d => d.Length))
{
    if (!Directory.EnumerateFileSystemEntries(dir).Any())
    {
        Directory.Delete(dir);
    }
}

Console.WriteLine($"Exported {sink.WrittenCount} file(s) to {outputDir}");
if (stale > 0)
{
    Console.WriteLine($"Pruned {stale} stale file(s).");
}

foreach ((string id, GeneratorDiagnosticSeverity severity, string message) in sink.Diagnostics)
{
    WriteDiagnosticRaw(id, severity, message);
}

return 0;

static string ResolveDefaultSchemaPath()
{
    // Primary source: the upstream submodule's community-enriched cs2_schema.json,
    // refreshed by `git submodule update --remote upstream`. Falls back to a
    // local schemas.json at the repo root or output/ for offline scenarios and
    // legacy paths. Returns the upstream path even when missing so the caller
    // can emit a submodule-init hint instead of a generic "not found" error.
    string cwd = Directory.GetCurrentDirectory();
    string upstream = Path.GetFullPath(Path.Combine(cwd, "upstream", "docs", "generated",
        "downstream-codegen-schemas", "cs2_schema.json"));
    string outputLocal = Path.GetFullPath(Path.Combine(cwd, "output", "schemas.json"));
    string rootLocal = Path.GetFullPath(Path.Combine(cwd, "schemas.json"));

    if (File.Exists(upstream))
    {
        return upstream;
    }

    bool outputExists = File.Exists(outputLocal);
    bool rootExists = File.Exists(rootLocal);

    if (outputExists && rootExists)
    {
        WriteDiagnostic(Descriptors.MultipleSchemaFiles, outputLocal);
        return outputLocal;
    }

    if (outputExists)
    {
        return outputLocal;
    }

    if (rootExists)
    {
        return rootLocal;
    }

    // Nothing exists — return the preferred upstream path so the not-found
    // branch can recognise it and print the submodule-init instructions.
    return upstream;
}

// Sibling of the class-schema input — the upstream submodule keeps them in the
// same directory. When the user passed a custom class-schema path, look for
// gameevents_schema.json next to it; otherwise default to the upstream layout.
// Returns null when no candidate is sensible so the caller can skip silently.
static string? ResolveGameEventsPath(string classSchemaPath)
{
    string? dir = Path.GetDirectoryName(classSchemaPath);
    if (dir is null)
    {
        return null;
    }

    string sibling = Path.Combine(dir, "gameevents_schema.json");
    return File.Exists(sibling) ? sibling : null;
}

static void WriteDiagnostic(GeneratorDiagnostic diagnostic, params object[] args) =>
    WriteDiagnosticRaw(diagnostic.Id, diagnostic.Severity, diagnostic.Format(args));

static void WriteDiagnosticRaw(string id, GeneratorDiagnosticSeverity severity, string message) =>
    Console.Error.WriteLine($"{severity.ToString().ToLowerInvariant()} {id}: {message}");

static bool IsGeneratedFile(string path)
{
    try
    {
        using StreamReader reader = new(path);
        string? first = reader.ReadLine();
        return first is not null && first.Contains("<auto-generated/>", StringComparison.Ordinal);
    }
    catch (IOException)
    {
        return false;
    }
}
